### ISSUE TITLE
setHardwareScalingLevel broken on Win32 Playground

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1000]
In experience.js, add `engine.setHardwareScalingLevel(2.5);` with any value bigger than 1, a part of the window is not refreshed at the top. The bigger the value, the bigger the non refreshed area. Might be happening on other platforms. I've tested Android without issue.

**Comment by bghgary** [comment]
This no longer repros with the latest changes.
