### ISSUE TITLE
Mouse input will not work if the mouse is over the window before the app is ready

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#1022]
Once https://github.com/BabylonJS/BabylonNative/pull/1018 is merged, this bug will be visible. The problem is that `onDeviceConnected` event does not handle when existing devices are already connected. This causes the onDeviceConnected event to not fire to the JS side properly. Even after fixing that, there is still a problem. On the JS side, the interaction between NativeDeviceInputSystem and NativeInput has a similar problem with the callback.

This used to work because on the input manager on the JS side used a global `onUserInputChanged` event. Now, it registers for the device connected event before listening to the input changed event on the device source. See [here](https://github.com/BabylonJS/Babylon.js/commit/f3d56f8bd388fbef179300bc83dfe3090244af14#diff-b2f8ea1f7c6d90a160cb60fabd7689dbdefa75ebaefd75fff03aa92ad871982fL852-R906).

**Comment by bghgary** [comment]
The workaround for now is to make sure the mouse is not on top of the window before the app is ready. That will make the mouse work.

**Comment by PolygonalSun** [comment]
PR for BJS: https://github.com/BabylonJS/Babylon.js/pull/12164

**Comment by PolygonalSun** [comment]
Closing as work is complete
