### ISSUE TITLE
Morph targets are broken on Android.

### ISSUE THREAD

**Issue by SergioRZMasson** [BabylonJS/BabylonNative#1049]
## Overview

Morph targets do not work on android, bgfx requires uses (renderer_gl.cpp, 2835):

g_caps.limits.maxTextureLayers   = BX_ENABLED(BGFX_CONFIG_RENDERER_OPENGL >= 31) || BX_ENABLED(BGFX_CONFIG_RENDERER_OPENGLES >= 31) || s_extension[Extension::EXT_texture_array].m_supported ? uint16_t(bx::max(glGet(GL_MAX_ARRAY_TEXTURE_LAYERS), 1) ) : 1;

This does not allow texture arrays to have length bigger than 1.

BGFX_CONFIG_RENDERER_OPENGL  is currently set to 30 in BabylonNative, increasing it to 31 causes it to crash when running in the android emulator. 

Maybe bgfx should be exposes to Babylon.js NativeEngine caps? 

## Tests

This bug affects Android device and emulator only. Testes on iOS simulator and devices and morph targets worked as expected.

**Comment by SergioRZMasson** [comment]
Fixed it by exposing bgfx caps to Babylon.js and appropriately setting MorphTargetManager._canUseTextureForTargets. Fix is implemented in two PRs:

[Babylon Native PR](https://github.com/BabylonJS/BabylonNative/pull/1075)
[Babylon.js PR](https://github.com/BabylonJS/Babylon.js/pull/12515)

**Comment by bghgary** [comment]
Changes have landed.
