### ISSUE TITLE
Issue with building the Android Playground app

### ISSUE THREAD

**Issue by sokolyaka** [BabylonJS/BabylonNative#1070]
Hi!
I am trying to build the Android Playground app using MacBook Pro M1.
I follow the build guide and did all steps mentioned in the guide:

1. Installed CMake 3.19.0 
<img width="515" alt="Screenshot 2022-05-02 at 17 32 39" src="https://user-images.githubusercontent.com/11253928/166252631-e4b6edfe-0849-4b5c-b70d-eb2e30abf91f.png">

2. Ninja 
<img width="686" alt="Screenshot 2022-05-02 at 17 34 19" src="https://user-images.githubusercontent.com/11253928/166252595-a7c23838-1434-49b2-abd8-2b0922489d0d.png">

3. Node.js 14.15.5
<img width="325" alt="Screenshot 2022-05-02 at 17 37 04" src="https://user-images.githubusercontent.com/11253928/166252925-21ade91b-d8ca-4e40-8b0c-97ae56e523ab.png">

4. Cloned the project with git clone --recursive https://github.com/BabylonJS/BabylonNative.git
5. cd Apps 
6. npm install
<img width="262" alt="Screenshot 2022-05-02 at 17 38 45" src="https://user-images.githubusercontent.com/11253928/166253231-fc1199d8-1025-4860-b74c-7ddaf31eed1a.png">

7. Opened project  with Android Studio -> Apps/Playground/Android
8. gradle.properties -> NDK_VERSION=22.1.7171670
9. local.properties -> cmake.dir=/Applications/CMake.app/Contents

When I am syncing the project with Gradle files I receive such a fatal error:
<img width="1297" alt="Screenshot 2022-05-02 at 17 47 04" src="https://user-images.githubusercontent.com/11253928/166254635-63ad5e6c-fb45-410a-b208-1ed6967c6fe7.png">

Would be grateful if somebody can help me to build the project.
Any ideas on how to deal with it?

**Comment by bghgary** [comment]
I don't know anyone has tried to build Babylon Native on Mac for Android. We do build Babylon React Native on Mac for Android but it normally targets JSC or Hermes.

One thing you could try is to disable the v8inspector from the build or use JSC.

**Comment by sokolyaka** [comment]
Hey @bghgary, thanks for the suggestion! It is helped me to build the project, but when I am running the Playground app on my Android device, BabylonNative fails with such an issue:
<img width="1273" alt="Screenshot 2022-05-03 at 12 53 06" src="https://user-images.githubusercontent.com/11253928/166435036-202dba71-6078-47e2-a494-57c0deaf93e8.png">

**Comment by sokolyaka** [comment]
Ok, I was able to build it using a Windows machine.

**Comment by bghgary** [comment]
Sounds good. This is technically still a problem though if we can't build Android on a Mac. If anyone is reading this thread and wants this to work, please reopen.

**Comment by ZhuoYitao** [comment]
Hi @bghgary @sokolyaka , I tried to build the Android Playground app with jsc, but I got the following error, do you have any suggesstions?
```
2 files found with path 'lib/arm64-v8a/libjsc.so' from inputs:
 - {projectPath}/Apps/Playground/Android/app/build/intermediates/merged_jni_libs/debug/out/arm64-v8a/libjsc.so
 - {projectPath}/Apps/Playground/Android/app/build/intermediates/cxx/Debug/4y2u5v3q/obj/arm64-v8a/libjsc.so
```

**Comment by bghgary** [comment]
That doesn't look like an error message. Can you create post on the forum with more of the log?

**Comment by ZhuoYitao** [comment]
> That doesn't look like an error message. Can you create post on [the forum](https://forum.babylonjs.com/) with more of the log?

https://developer.android.com/studio/releases/gradle-plugin#cmake-imported-targets

Hi @bghgary, according to Android's document, the problem happens because the version of gradle plugin used in the playground project is too old. I solve this problem by adding the following config in app/build.gradle.
android {
  packagingOptions {
    pickFirst 'lib/arm64-v8a/libjsc.so'
  }
}

It means using the first matched item for 'lib/arm64-v8a/libjsc.so'. I may propose an PR to solve this problem for developers who use newer version of gradle and gradle plugin.

**Comment by ZhuoYitao** [comment]
> Sounds good. This is technically still a problem though if we can't build Android on a Mac. If anyone is reading this thread and wants this to work, please reopen.

By the way, I have successfully build Android on a Mac with V8. However, I changed part of configs. I may propose an PR for this.

**Comment by bghgary** [comment]
Sounds good. Thanks for investigating!
