### ISSUE TITLE
Build BabylonNative for ChromeOS

### ISSUE THREAD

**Issue by dimitriosp** [BabylonJS/BabylonNative#1074]
Hello, 
we are trying to run our babylon native app on Chrome OS but (of course) keep failing since there is no .so file build for ChromeOS, only for Android 9+. 

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libBabylonNativeJNI.so"`

Any idea how to build it for ChromeOS?

**Comment by bghgary** [comment]
I don't think anyone has tried to do this. I don't think anyone on the team knows much about building for Chrome OS. Will you be willing to try to figure it out? I'm guessing that the CMake files (that produce `libBabylonNativeJNI.so`) are written in a way that doesn't work for Chrome OS.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this.
