### ISSUE TITLE
Memory keeps climbing in specific situations

### ISSUE THREAD

**Issue by HedwigAR** [BabylonJS/BabylonNative#1077]
**Describe the bug**
I am using a dynamic texture to draw text on a texture. However, I'm noticing the memory used going up and not coming down. I've asked on the forum (https://forum.babylonjs.com/t/cant-clear-dynamictexture-to-transparent-in-babylonreactnative/28933), but the conversation ran stale there, so I figured I should make a reproducible project. 

**To Reproduce**
I've created a repository where I've recreated my situation: https://github.com/HedwigAR/BabylonCanvasIssue 
I've found two situations where this memory issue happens, I've put them both in the project you can uncomment/
Situation one: https://github.com/HedwigAR/BabylonCanvasIssue/blob/3c1a6fd854bf0a43f6f59c54cc4519b4b578a250/App.tsx#L183 
Situation two: https://github.com/HedwigAR/BabylonCanvasIssue/blob/3c1a6fd854bf0a43f6f59c54cc4519b4b578a250/App.tsx#L207

**Expected behavior**
I expect to be able to create new textures, disposing the old ones, to maybe have an impact on performance but not on the memory usage. 

**Screenshots**
Here's the situation where the texture isn't being rendered on the mesh, but instead is rendered on the camera
![Screenshot_20220413-135346_BabylonCanvasIssue](https://user-images.githubusercontent.com/4737792/163176502-173d3185-3c14-400d-a865-a507a357d545.jpg)

Here's the profiler with the memory climbing during one of the two scenario's I've put in the project. At the end the whole project crashes.
<img width="1195" alt="Screenshot 2022-04-13 at 13 42 27" src="https://user-images.githubusercontent.com/4737792/163173973-e8b9e39a-9823-4546-9e01-c13a1619f592.png">

**Other**
 - Platform: Android, didn't check on iOS

**Comment by bghgary** [comment]
Let's close this for now. Please re-open if it still repros.
