### ISSUE TITLE
Demo projects take too much memory

### ISSUE THREAD

**Issue by ZhuoYitao** [BabylonJS/BabylonNative#1080]
Either the Android demo project or the iOS demo project takes more than 100MB memory. Considering they simply render a cube, the memory cost is too large. Is there any suggestion to reduce the memory usage?

P.S. I've changed some configs in 'Dependencies/bgfx.cmake/bgfx/src/config.h', such as the 'BGFX_CONFIG_MAX_DRAW_CALLS' definition, but the total memory keeps unchanged.

**Comment by ZhuoYitao** [comment]
Hi @bghgary, do you have any idea about this issues? Let me know if I need to add more information.

**Comment by ryantrem** [comment]
Sounds related to #726 (or at least that issue probably has relevant context).

**Comment by ZhuoYitao** [comment]
@bghgary I will have a look at it.

**Comment by ZhuoYitao** [comment]
Hi @bghgary，I notice that the LoadScript() method in ScriptLoader could cause a huge memory usage. When I comment out all lines in the "app:///Scripts/babylon.max.js" (which means no meaningful JS code will be run), running loader.LoadScript("app:///Scripts/babylon.max.js") still takes about 88MB of memory. Could you have a try at optimizing the loader?

**Comment by ZhuoYitao** [comment]
@bghgary Indeed, using the minified babylon.js can reduce the memory. But the reduced memory is still too large to embed Babylon Native into a mobile app. I guess there is memory leak(s) in the LoadScript() method.

**Comment by bghgary** [comment]
@ZhuoYitao Are you still seeing issues with this? If so, please reopen.
