### ISSUE TITLE
NativeCapture returns a solid color image

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#1103]
**Describe the bug**
NativeCapture has regressed and the rbga8 buffer we get back is now just a solid color. It is not the same solid color each frame though, it seems to alternate between gray and the default clear color.

**To Reproduce**
I tested this in Babylon React Native, so I haven't confirmed it repros in Babylon Native directly but I expect it does.
In that context, create a `CaptureSession` and dump the frame data to a bitmap to see the solid color. I can create a repro branch later also, but getting this issue logged now.

**Expected behavior**
Captured frame has the actual frame data in the rgba byte buffer.

**Other**
Android and iOS

**Comment by bghgary** [comment]
Close since we are not investing in NativeCapture feature.
