### ISSUE TITLE
KHR_texture_transform validation test crashing for D3D12 on BabylonJS 5.17.0

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#1114]
Running validation tests for #1113 is showing an issue with D3D12:
`BGFX ASSERT m_device->CreateGraphicsPipelineState(&desc , IID_ID3D12PipelineState , (void**)&pso ) FAILED`

It occurs when capturing a screenshot for the test:
![bn-d3d12-val-error-ss](https://user-images.githubusercontent.com/4724014/181832308-4e05107e-d7c2-49cf-989a-51c75bad0f03.png)

Debug layers are on and the Visual Studio graphics debugging tool didn't give me anything very enlightening. The only thing I could decipher is that the HRESULT corresponds to the following error message: "The parameter is incorrect."

**Comment by CedricGuillemet** [comment]
Fixed by this PR : https://github.com/BabylonJS/BabylonNative/pull/1113
