### ISSUE TITLE
Properly handle readTextureAsync cancellation in Native Capture

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#1131]
In NativeCapture, we currently do not handle the possibility that readTextureAsync can fail.  It is possible that if NativeCapture is running at the end of the engine lifetime that we will not be able to hand back results to NativeCapture, and improperly handle the return value of the task.

We should add some level of exception handling or pre-emptively end the NativeCapture session and drain all remaining readTextures requests during engine shutdown.

See the changes in #1132 for more info.

**Comment by bghgary** [comment]
NativeCapture is not the long term solution, so we will not likely invest in this feature.
