### ISSUE TITLE
After update to 1.3.4 getting warning "The flags generateDepth/generateStencilBuffer are mismatched. Depth and stencil are combined in one texture"

### ISSUE THREAD

**Issue by brian-hay** [BabylonJS/BabylonNative#1134]
Not a bug but I just updated to Babylon React Native 1.3.4 and am now receiving the warning:

`The flags generateDepth/generateStencilBuffer are mismatched. Depth and stencil are combined in one texture`

Should I be doing something different?

**Comment by CedricGuillemet** [comment]
@brian-hay On which platform do you get this message?

**Comment by brian-hay** [comment]
@CedricGuillemet this warning was on Android, specifically Android 11 on the Samsung Tab Active Pro (SM-T540).

**Comment by nmongiya** [comment]
I am also getting the same with the following packages

`"@babylonjs/core": "5.25.0",
    "@babylonjs/loaders": "5.25.0",
    "@babylonjs/materials": "5.25.0",
    "@babylonjs/react-native": "1.3.5",
    "@babylonjs/react-native-iosandroid-0-69": "1.3.5",
    "@babylonjs/react-native-windows-0-69": "1.3.5",`

and here is my device info 

`System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 17.74 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /var/folders/dq/p19k2lhx641cgr3mb15vd6w80000gn/T/yarn--1664238256034-0.21948768805165497/node
    Yarn: 1.22.19 - /var/folders/dq/p19k2lhx641cgr3mb15vd6w80000gn/T/yarn--1664238256034-0.21948768805165497/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found`

**Comment by CedricGuillemet** [comment]
I've just test on master, RN 0.65 and 0.69 and babylon 5.25 and I don't repro.
@brian-hay / @nmongiya  Do you get the message in the logcat or the console? do you repro with the playground? ar you both on mac?

**Comment by brian-hay** [comment]
Hi @CedricGuillemet I see the warning in both the console and logcat. I'm deploying to Android 11 on the Samsung Tab Active Pro (SM-T540).

The only places in my code I'm explicitly referencing depth are a custom shader and a method to enable/update the depth renderer, similar to:

```
  public updateDepthRenderer(): DepthRenderer | undefined {
    let depthRenderer: DepthRenderer | undefined;
    if (this.scene) {
      this.scene.disableDepthRenderer();
      depthRenderer = this.scene.enableDepthRenderer();
      depthRenderer.forceDepthWriteTransparentMeshes = true;
    }

    return depthRenderer;
  }
```

But as I say, prior to upgrading to Babylon React Native 1.3.4, this hasn't been a problem and that particular code hasn't changed.

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/1142

**Comment by bghgary** [comment]
@brian-hay Thanks for the report. I've merged a fix. The check was bad. It may take some time before it gets to Babylon React Native. Let us know if you need it earlier for some reason.

**Comment by brian-hay** [comment]
Thanks @bghgary & @CedricGuillemet !

**Comment by brian-hay** [comment]
Hi @bghgary and @CedricGuillemet. Just wondering when the next Babylon React Native release is scheduled that includes this fix?

**Comment by bghgary** [comment]
We don't have a schedule for releases at the moment. We do it ad-hoc based on needs. Let us know if you need this fix more urgently and we will try to accommodate.

**Comment by brian-hay** [comment]
Thanks @bghgary . As it's a warning only, it's not a critical blocker, just an annoyance as it pops up every time we launch the app.
