### ISSUE TITLE
Curl transfers not completing

### ISSUE THREAD

**Issue by docEdub** [BabylonJS/BabylonNative#1156]
In [UrlRequest_Unix.cpp](https://github.com/BabylonJS/BabylonNative/blob/d414bcf7263832ed7e7456211132760c3c7e2e71/Dependencies/UrlLib/Source/UrlRequest_Unix.cpp), curl transfers are not always completing. Gary and I looked at this for a while and suspect that we're not using the curl library correctly.

1. On a Linux setup, start a script that runs the unit tests 1000 times.
2. Eventually, one of the unit tests will get stuck and need to be killed manually.

Expected behavior:
The unit tests should never get stuck and need to be killed manually.

Other:
 - Platform: Linux

**Comment by thomlucc** [comment]
@CedricGuillemet - please check with @bghgary

**Comment by CedricGuillemet** [comment]
It's difficult to repro on my side. I'm even able to do 1000 runs without a failure. I let you fix it @docEdub

**Comment by bghgary** [comment]
It's so rare, we are going to wait on fixing it.
