### ISSUE TITLE
About very slow loading with 3MB glb file

### ISSUE THREAD

**Issue by LightYearDeveloper** [BabylonJS/BabylonNative#1159]
I am using SceneLoader.ImportMesh() function to load some glb files.
And it takes about 4 seconds to load a 3MB glb file, so it's about 12 seconds to load three 3MB glb files.
Is this a normal speed of loading?
How could I improve it if it is not normal?
Thank you so much!

**Comment by ryantrem** [comment]
In a debug or release build?

**Comment by bghgary** [comment]
Also, please use the forum to ask questions.
