### ISSUE TITLE
DEPTH_COMPONENT16 and render buffer

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1166]
forum thread : https://forum.babylonjs.com/t/unsupported-texture-format-or-type-format-5-type-2/35694/3

A DEPTH_COMPONENT16 render buffer is created and it's currently unsupported by the engine.

Also, the RGBA16F format is not supported yet but it's quite easy to add.

**Comment by bghgary** [comment]
cc @PolygonalSun

**Comment by PolygonalSun** [comment]
Update:
This issue is the reason why extensions like Iridescence and Transmission aren't working in Babylon Native.  The fix for this would involve updating the NativeEngine to override the `updateRenderTargetTextureSampleCount` function.

**Comment by bghgary** [comment]
This landed in #13697.

**Comment by bghgary** [comment]
The main issue is addressed. MSAA is not working with render targets which is a separate issue.
