### ISSUE TITLE
#error "ARC is off" on Apple M1 mac mini

### ISSUE THREAD

**Issue by lvdpower** [BabylonJS/BabylonNative#1179]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

There is error 
[ 52%] Built target spirv-cross-msl
[ 52%] Building CXX object Dependencies/UrlLib/CMakeFiles/UrlLib.dir/Source/UrlRequest_Apple.mm.o
/Users/timur/dev/BabylonNative/Dependencies/UrlLib/Source/UrlRequest_Apple.mm:2:2: error: "ARC is off"
#error "ARC is off"
 ^
1 error generated.]

Mac mini m1 silicon

**Comment by bghgary** [comment]
Please use the forum for this.
