### ISSUE TITLE
Window resizing issues

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#118]
Because of this crash on macos: https://github.com/BabylonJS/BabylonNative/issues/151
now bgfx::frame is called when resizing, replacing a call to bgfx::touch
Crash is fixed and no strange behavior appearing on win32/Android.

- [x] On UWP a flickering was experienced before, now the refresh happens 0.5s after resizing, without flickering.

On iOS, there is a Metal exception when a bgfx::touch(0) is not performed once a frame.

**Comment by bghgary** [comment]
Blocked on the rendering rework (#345)

**Comment by bghgary** [comment]
No, it possibly has made it behave differently, but there are still issues.

**Comment by bghgary** [comment]
I need to check if there are still issues.

**Comment by CedricGuillemet** [comment]
Resize and resume tested OK on Android, win32, uwp, ios and mac. Closing.
