### ISSUE TITLE
Dynamic Texture context.drawImage does not work with context.clip

### ISSUE THREAD

**Issue by SergioRZMasson** [BabylonJS/BabylonNative#1184]
## Overview

When using context.drawImage after a context.clip the image is not properly drawn using the curve previously set.  This bug was reported on the [forum](https://forum.babylonjs.com/t/context-clip-not-working-on-babylon-react-native-dynamic-texture-context/36825). 

**To Reproduce**
Using a dynamic texture construct a path than call context.clip and context.drawImage:

```
//Create path
textureContext.beginPath();
textureContext.moveTo(75*2, 25*2);
textureContext.quadraticCurveTo(25*2, 25*2, 25*2, 62.5*2);
textureContext.quadraticCurveTo(25*2, 100*2, 50*2, 100*2);
textureContext.quadraticCurveTo(50*2, 120*2, 30*2, 125*2);
textureContext.quadraticCurveTo(60*2, 120*2, 65*2, 100*2);
textureContext.quadraticCurveTo(125*2, 100*2, 125*2, 62.5*2);
textureContext.quadraticCurveTo(125*2, 25*2, 75*2, 25*2);
textureContext.strokeStyle = "white";
textureContext.stroke();

//Clip and draw image.
textureContext.clip();
textureContext.drawImage(this, 0, 0);
```

**Expected behavior**
Expected behavior should match the following playground: https://playground.babylonjs.com/#FU0ES5#25

**Comment by thomlucc** [comment]
fixed
