### ISSUE TITLE
Texture destroyed while being used

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1193]
Broken nightly:

a texture copy is asked from JS : https://github.com/BabylonJS/BabylonNative/blob/9c69a24801edae3996418ef771a09f39538a23a7/Plugins/NativeEngine/Source/NativeEngine.cpp#L1093
but between that call and this one (where the copy is actually performed) https://github.com/BabylonJS/BabylonNative/blob/9c69a24801edae3996418ef771a09f39538a23a7/Plugins/NativeEngine/Source/NativeEngine.cpp#L1101

the destination texture is destroyed. I won't discussed why the texture is destroyed, if it's necessary or not. the fact that we can run process related to textures and it can be destroyed before is problematic

I think it's the same as https://github.com/BabylonJS/BabylonNative/issues/810
Depending on the work and time it takes, resource is destroyed too early.

**Comment by bghgary** [comment]
Closing in favor of #1420
