### ISSUE TITLE
Ninja dependency cycle error: Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by giraphics** [BabylonJS/BabylonNative#1194]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
Building Babylon Native for Ubuntu 20.04.5 LTS gives ninja dependency cycle error.

**To Reproduce**
Following directions:-
1. https://github.com/BabylonJS/BabylonNative/blob/master/BUILDING.md#building-on-ubuntu-targeting-linux
2. Running `ninja` command gives the following error.
`
ninja: error: dependency cycle: Apps/Playground/Scripts/experience.js -> Apps/Playground/Scripts/experience.js`

I am using node version v18.10.0.

**Comment by bghgary** [comment]
I've recently followed the instructions and didn't get this error. Can you post the whole log?

**Comment by giraphics** [comment]
Hi @bghgary ,

I am able to replicate the problem. The root cause looks on my system is CMake's `build`. In my steps, I have not created the `build` folder and executed CMake command assuming it should work however I am getting the reported error above.

I assume you have created the `build` folder as recommended in https://github.com/BabylonJS/BabylonNative/blob/master/BUILDING.md#all-development-platforms resolves the problem. 

Below are the precise steps that reproduce the error:-
```
git clone --recursive https://github.com/BabylonJS/BabylonNative.git
cd BabylonNative/Apps/
npm install
cd ..
sudo apt-get install libgl1-mesa-dev libcurl4-openssl-dev clang-9 libc++-9-dev libc++abi-9-dev lld-9 ninja-build
sudo apt-get install libjavascriptcoregtk-4.0-dev
cmake -G Ninja -D JSCORE_LIBRARY=/usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so -D NAPI_JAVASCRIPT_ENGINE=JavaScriptCore
sudo apt-get install libv8-dev
cmake -G Ninja -D NAPI_JAVASCRIPT_ENGINE=V8
ninja
```

Now, after creating the build folder, the ninja does not complain, but I wonder why the build system fails in the current directory.

**Comment by bghgary** [comment]
Yes, I don't know why, but ninja expects everything to be in a folder called `build`. It has to be lowercase as well IIRC. Maybe we can note it in the README. Feel free to make a contribution to the text. :-)
