### ISSUE TITLE
Add support for triangle fan (MATERIAL_TriangleFanDrawMode)

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#1216]
glTF supports this, but bgfx doesn't. One solution is to generate the indices on glTF load. It might not be worth adding support to bgfx since triangle fans are rarely used.

**Comment by CedricGuillemet** [comment]
https://learn.microsoft.com/en-us/windows/win32/direct3d9/triangle-fans?redirectedfrom=MSDN

Triangle fans are not supported in Direct3D 10 or later. Same for Metal and, I guess, Vulkan.

**Comment by bghgary** [comment]
Not supporting this unless someone needs it.
