### ISSUE TITLE
NativeCamera AVCaptureVideoOrientation Deprecated with iOS 17

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1248]
iOS17 suspected to  be released in September 2023

**Comment by zxffffffff** [comment]
Is there a plan to fix this issue?  :)

'AVCaptureVideoOrientation' is deprecated: first deprecated in macOS 14.0 - Use AVCaptureDeviceRotationCoordinator instead
'AVCaptureVideoOrientationLandscapeLeft' is deprecated: first deprecated in macOS 14.0 - Use AVCaptureDeviceRotationCoordinator instead
'AVCaptureVideoOrientationLandscapeRight' is deprecated: first deprecated in macOS 14.0 - Use AVCaptureDeviceRotationCoordinator instead

**Comment by CedricGuillemet** [comment]
plan is to fix it for Babylon.js 7.0 release which is due for March 24.
We accept PR so you can submit your changes and we will be glad to review it.

**Comment by zxffffffff** [comment]
> plan is to fix it for Babylon.js 7.0 release which is due for March 24. We accept PR so you can submit your changes and we will be glad to review it.

This is just a minor issue; it only requires modifying the SDK version on Xcode.

I am currently studying the documentation and source code of Babylon Native. I will actively participate once I feel confident enough to contribute code. Currently, I am still relatively young. 

I really appreciate the software architecture of Babylon Native, especially the combination of JS and C++ development, which impresses me. Thank you for the open source!
