### ISSUE TITLE
Error when building for Win32 using V8

### ISSUE THREAD

**Issue by alexchuber** [BabylonJS/BabylonNative#1256]
```
CMake Error at build/win32/_deps/jsruntimehost-src/Core/Node-API/CMakeLists.txt:98 (message):
  Unsupported JavaScript engine: V8
```

**Comment by bghgary** [comment]
@CedricGuillemet I didn't add V8 support for Windows in JsRuntimeHost, so when we integrated it over, V8 support disappeared.

**Comment by CedricGuillemet** [comment]
self assigning, I can add that support at the same time as CMake install PR.

**Comment by CedricGuillemet** [comment]
https://github.com/BabylonJS/JsRuntimeHost/pull/41

**Comment by bghgary** [comment]
The JsRuntimeHost integration has been reverted, so this should work again.
