### ISSUE TITLE
CMake npm install function ignores package.lock file in Apps folder

### ISSUE THREAD

**Issue by alexchuber** [BabylonJS/BabylonNative#1257]
If you run cmake at the time of writing, it will pull 6.11.2.
But, if you run npm install, it will use 6.4.1.

**Comment by bghgary** [comment]
@CedricGuillemet This is because we are ignoring the lock file in the npm install function.

**Comment by CedricGuillemet** [comment]
Yes, it's explicit in the command line to not use the package lock. 
Does it make sense to remove package lock in the repo?

**Comment by ryantrem** [comment]
Why not use the package lock file? Usually this is kind of an anti pattern since build behavior can change without making any changes to any files in the repo.

**Comment by bghgary** [comment]
We should use the package lock file here. I added it for a different purpose for JsRuntimeHost.

**Comment by CedricGuillemet** [comment]
Fixed with https://github.com/BabylonJS/BabylonNative/pull/1260
