### ISSUE TITLE
Update to latest version of glslang

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#128]
See https://github.com/KhronosGroup/glslang/issues/1976 for context. It would be good to update <strike>and remove [`ENABLE_HLSL` define](https://github.com/BabylonJS/BabylonNative/blob/master/Library/CMakeLists.txt#L30) to avoid future layout issue</strike>(`ENABLE_HLSL` should still be set to off).

**Comment by CedricGuillemet** [comment]
draft PR https://github.com/BabylonJS/BabylonNative/pull/129
