### ISSUE TITLE
Compilation fails on newer versions of Xcode

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#1281]
**Describe the bug**
With newer versions of Xcode, a newer version of clang is used, which results in a compilation error in Dependencies/SPIRV-Cross/spirv_common.hpp. Specifically, line 665 contains `move(expr)` which needs to be `std::move(expr)`. This has already been [fixed](https://github.com/KhronosGroup/SPIRV-Cross/commit/0eda71c40936586ea812d0d20d93c11a3e9af192) in SPIRV-Cross, so ideally we should just update to a newer commit that has this fix.

**To Reproduce**
1. Install the latest version of Xcode
2. Follow the steps in the README to build for iOS (probably repros for Mac too, but I haven't tried)

**Expected behavior**
Compilation succeeds.

**Other**
 - Platform: iOS

**Comment by ryantrem** [comment]
It is fixed, I linked the commit that it was fixed in above 🙂

**Comment by bghgary** [comment]
@SergioRZMasson I think you updated the dependencies. Is this fixed?

**Comment by SergioRZMasson** [comment]
This should be fixed!

**Comment by bghgary** [comment]
Can you link to the PR and close this issue?
