### ISSUE TITLE
mac m2 pro compile BabylonNative error

### ISSUE THREAD

**Issue by looweex** [BabylonJS/BabylonNative#1331]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
mac m2 pro compile BabylonNative error

**To Reproduce**

**Expected behavior**
I set the xcode compile option as the pic below, still two errors ,how solved it

**Screenshots**
![c3db9fafb3ef17925986742681cc02c9](https://github.com/BabylonJS/BabylonNative/assets/47051545/1f3990c1-0236-4264-a15a-12702ee54662)
![87d8ba589ebcc3365e9d6e85b9d33031](https://github.com/BabylonJS/BabylonNative/assets/47051545/f59e131b-87ff-4278-bf90-0005e9b5cd13)

**Other**
 - Platform: [e.g. Win32, UWP, HoloLens, Android, iOS]

**Comment by bghgary** [comment]
@SergioRZMasson

**Comment by SergioRZMasson** [comment]
Hey @looweex , how are you doing? Sorry for taking so long to reply to you.

We currently have a known issue on MacOS regarding the NativeCamera plugin (that can be mitigated by disabling the NativeCamera plugin). When trying to repro on my machine I only got the NativeCamera issue, not the ones you are showing. 

Can you share what is your XCode and MacOS version and which settings have you used when running CMake config?

**Comment by thomlucc** [comment]
Closing. Feel free to re-open if needed
