### ISSUE TITLE
[CPPUnitTest] Page flip and backbuffer

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1337]
https://github.com/BabylonJS/BabylonNative/pull/1336

BN rendering should follow WebGL principles: rendering and flip after rendering.
Make sure this always happens by doing rendering of 1 frame then reading front buffer and ensuring rendering is visible.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
