### ISSUE TITLE
Implement `napi_add_finalizer` function

### ISSUE THREAD

**Issue by mattbirman** [BabylonJS/BabylonNative#1351]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Is your feature request related to a problem? Please describe.**
We are using the `napi` [Rust package](https://docs.rs/napi/latest/napi/) and calling [add_finalizer](https://docs.rs/napi/latest/src/napi/js_values/object.rs.html#31) on `JsObject`. This call fails at runtime because [napi_add_finalizer](https://nodejs.org/api/n-api.html#napi_add_finalizer) is not implemented in BabylonJS.

**Describe the solution you'd like**
An native implementation of `napi_add_finalizer` in BabylonJS.

**Describe alternatives you've considered**
No alternatives to this function. We have considered not adding the finalizer to the object and allowing the object to not be garbage-collected.

**Additional context**
N/A

**Comment by CedricGuillemet** [comment]
Can we close this issue @bghgary ?
