### ISSUE TITLE
JavaScript Engine choices

### ISSUE THREAD

**Issue by Armasyll** [BabylonJS/BabylonNative#137]
Could we switch over to Chrome's V8 instead of Chakra, or have a choice of JavaScript engines?

**Comment by bghgary** [comment]
Yes, V8 is supported. You can set the CMake variable [NAPI_JAVASCRIPT_ENGINE](https://github.com/BabylonJS/BabylonNative/blob/master/Library/Dependencies/napi/CMakeLists.txt#L12) to do this.

**Comment by Armasyll** [comment]
Thank you!
