### ISSUE TITLE
Improve performance of mipmaps creation for some texture formats

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1392]
Related : https://github.com/BabylonJS/BabylonNative/pull/1391

For some texture formats are converted to RGBA8 or RGBA32F before computing mipmaps because of bgfx limitations. Add support for most(all?) texture formats.

see https://github.com/BabylonJS/BabylonNative/blob/efb8fb207d449e3245dd101519a9516dec73ddc4/Plugins/NativeEngine/Source/NativeEngine.cpp#L214

**Comment by bghgary** [comment]
No one has asked for this, we noticed this while adding some formats. We can improve memory usage and possibly CPU cost if we do this work.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
