### ISSUE TITLE
Support XR teleportation and more sophisticated inputs

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#140]
Among other things, this will require implementing the more advanced features of [`XRReferenceSpace`](https://immersive-web.github.io/webxr/#xrreferencespace-interface); this is what several `TODO` lines in the `XRReferenceSpace` implementation are referring to.

**Comment by bghgary** [comment]
@PolygonalSun Can you check if this is something you want to tackle?

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
