### ISSUE TITLE
Build Fail for Xcode Build for iOS Development

### ISSUE THREAD

**Issue by ellie-bb** [BabylonJS/BabylonNative#1400]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
Xcode build using iOS simulator failing. Building on MacOS, targeting iOS. 

**To Reproduce**
Follow the steps in Building.MD. Under section Building on MacOS, targeting iOS

1. Fresh pull of repo from Github
2. Launch project in Xcode
3. Build Playground

**Screenshots**

Here is the error message: 
`Building for 'iOS-simulator', but linking in dylib (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Cryptexes/OS/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore.tbd) built for 'iOS'`

In addition to: 

Showing All Issues
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:56:94: Unused parameter 'cf'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImageView.h:50:42: 'UIImageDynamicRange' is only available on iOS 17.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImageView.h:52:42: 'UIImageDynamicRange' is only available on iOS 17.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UINavigationBar.h:161:4: 'UINavigationBarNSToolbarSection' is only available on iOS 16.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPress.h:55:43: 'UIKey' is only available on iOS 13.4 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextCursorDropPositionAnimator.h:21:58: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextCursorDropPositionAnimator.h:38:4: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIWindowSceneGeometryPreferencesMac.h:16:50: 'UIWindowSceneGeometryPreferences' is only available on iOS 16.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPointerStyle.h:20:29: 'UIHoverStyle' is only available on iOS 17.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructureTypes.h:11:9: Anonymous structs are a GNU extension

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructureTypes.h:11:9: Anonymous types declared in an anonymous union are an extension

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructure.h:838:5: 'MTLMotionBorderMode' is only available on iOS 15.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructure.h:844:5: 'MTLMotionBorderMode' is only available on iOS 15.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructure.h:888:5: 'MTLResourceID' is only available on iOS 16.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructure.h:916:5: 'MTLResourceID' is only available on iOS 16.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructure.h:934:5: 'MTLMotionBorderMode' is only available on iOS 15.0 or newer

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLAccelerationStructure.h:940:5: 'MTLMotionBorderMode' is only available on iOS 15.0 or newer

**Other**
 - Platform: [e.g. Win32, UWP, HoloLens, Android, iOS]

**Comment by CedricGuillemet** [comment]
Please use the forum for this kind of issue.

It looks like a deployment version issue. Can you run it again with a more recent ios target like:
```
cmake .. -G Xcode -D IOS=ON -D DEPLOYMENT_TARGET=17.2
```

Or change the version in project using Xcode.
