### ISSUE TITLE
Android. Problems with launching the app that comes with the engine 

### ISSUE THREAD

**Issue by andorxornot** [BabylonJS/BabylonNative#1444]
Hi devs,

I like Babylon.js a lot and have had positive experience with it. However, my attempts to build a native application for Android gave me the opposite experience.

My actions: I cloned the master branch (had issues with cloning repositories through git, I think it's better to use curl or git without history since cloning many large repositories often fails for me), created a native build on windows, and it works. Then i opened the project in Android Studio - it builds the project very slowly, the first build on my machine with i7 takes about 30 minutes! After that, the application crashes both on the Android x64 emulator and on my mobile device with Android 8 arm64.

I'm completely frustrated. Does it even work on android or is the project more focused on ios?

Here is the last part of call stack:
```
_dl_notify_gdb_of_load 0x0000007801dd9524
_dl_ZN6soinfo10link_imageERK10LinkedListIS_19SoinfoListAllocatorES4_PK17android_dlextinfo 0x0000007801dcd3d8
_dl_Z14find_librariesP19android_namespace_tP6soinfoPKPKcmPS2_PNSt3__16vectorIS2_NS8_9allocatorIS2_EEEEmIPK17android_dlextinfobb 0x0000007801dc9488
_dl_Z9do_dlopenPKciPK17android_dlextinfoPKv 0x0000007801dcae94
_dl_Z20__android_dlopen_extPKciPK17android_dlextinfoPKv 0x0000007801dc7d44
android_dlopen_ext 0x00000077febec190
art::DlOpenOatFile::DlOpen(const std::string &, unsigned char *, std::string *) 0x00000077fd3487e4
art::OatFileBase::OpenOatFile<...>(const std::string &, const std::string &, const std::string &, unsigned char *, unsigned char *, bool, bool, bool, const char *, std::string *) 0x00000077fd3498b8
art::OatFile::Open(const std::string &, const std::string &, unsigned char *, unsigned char *, bool, bool, const char *, std::string *) 0x00000077fd3495b4
art::OatFileAssistant::OatFileInfo::GetFile() 0x00000077fd350c2c
art::OatFileAssistant::OatFileInfo::Status() 0x00000077fd34ee08
art::OatFileAssistant::IsUpToDate() 0x00000077fd34ed78
```

**Comment by bghgary** [comment]
@andorxornot This type of question is better suited for [our forum](https://forum.babylonjs.com/). Can you move this question there?

**Comment by thomlucc** [comment]
Please @andorxornot , move this question to the forum. Closing the issue
