### ISSUE TITLE
test app sometime fails to render one of the faces of the box

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/BabylonNative#15]
Screenshot:

![image](https://user-images.githubusercontent.com/3753071/61076105-540a5880-a3d0-11e9-860e-fe56a47488a8.png)

Happens about 1/5 times I run the app

**Comment by syntheticmagus** [comment]
Fixed in commit 2759935c851538afcdbde8fef748b861abdfdf92. Problem was that the index buffer was being kept as a reference to a temporary variable, which was then being lost and overwritten some of the time.
