### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Schr3da** [BabylonJS/BabylonNative#171]
Hey, 

first of all thanks for the great and excellent work! I like a lot how babylonjs constantly improved over time and I know this is not a simple task. However please add Linux support as well to the list. I know on the market Linux usage is still quite low and you even can port games using the webgl version with a container e.g. electron but native performance is much better :D

Thanks 
Schreda

**Comment by CedricGuillemet** [comment]
I started taking a look at a Linux port and ran into 1 big issue with the JS engine.
No recent V8 engine is available as a prebuilt package (most recent is from 2016).
Binaries for Chakracore are available but Chakracore napi is using specific APIs and is not compatible with MS GitHub release available here : https://github.com/microsoft/ChakraCore/releases
@bghgary does it seem doable to you to port Chakracore napi to use those packages?

**Comment by bghgary** [comment]
Chakra is not the same as ChakraCore. The version we have is one that I modified from the ChakraCore version. If we bring in the ChakraCore version, it should work. You can find a [link](https://github.com/nodejs/node-chakracore/blob/master/src/node_api_jsrt.cc) the the main README.

**Comment by CedricGuillemet** [comment]
@bghgary I'm testing with JSC now.

**Comment by CedricGuillemet** [comment]
A WIP draft PR : https://github.com/BabylonJS/BabylonNative/pull/185

**Comment by CedricGuillemet** [comment]
Linux playground and validation tests compile with gcc and clang. The missing bit is this issue for OpenGL shader compilation. Closing.
