### ISSUE TITLE
Plugin Refactor Cleanup

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#175]
#157 was a large change that moved a lot of things around, so to avoid making that change any larger than it absolutely needed to be, we decided to clean up several relevant patterns and APIs later, in separate PRs. The most prominent of these tasks is to get all the plugins aligned on an initialization pattern, as much as possible/makes sense. Another task was that we wanted to evaluate whether to split NativeXr and NativeEngine into separate entities. Finally, it's likely worthwhile to do a quick pass through the CMakes and Include folders for every plugin to try to get them as uniform and coherent as possible.

**Comment by CedricGuillemet** [comment]
Talked to @syntheticmagus . Closing.
