### ISSUE TITLE
Full featured Playground app for Babylon Native

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/BabylonNative#182]
(From 4.2 Brainstorm)

**Comment by CedricGuillemet** [comment]
I've been thinking about this one and it might be a good opportunity to test with with Qt.
My main concern is about the text editor. What do you have in mind for that?
It can be a component like https://qscintilla.com/#intro/introduction but it would lack latest features of the online PG.
Or a web view with playground text edit (we would then find a way to grab the edited text and run it with native)
Anything else? @bghgary @thomlucc @syntheticmagus

**Comment by bghgary** [comment]
> My main concern is about the text editor. What do you have in mind for that?

I don't know if we want a text editor in the native playground. When we've discussed this before, we have always said that we would use vscode to edit a file on disk. I think it would nice if the playground app detects when the file changes and updates accordingly. That said, this is limited to a desktop scenario. I'm not sure there is a story for mobile.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to do this.
