### ISSUE TITLE
NativeEngine may be doing more copying than is necessary

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#19]
In a number of places, NativeEngine.cpp is using bgfx::copy to create locally owned copies of data from Babylon.js ([this line](https://github.com/BabylonJS/BabylonNative/blob/2759935c851538afcdbde8fef748b861abdfdf92/Library/Source/NativeEngine.cpp#L461), for example). This is probably redundant, as Babylon.js is already keeping copies to deal with device loss and other problems, so it should be possible to have the NativeEngine operate on refs alone so long as it's given access to the permanently-stored versions of data on the JavaScript side, not temporary copies. Fixing will require changes on both managed and native sides.

**Comment by CedricGuillemet** [comment]
It's unclear for me if the typed array will still be available when the function exists.
https://github.com/BabylonJS/BabylonNative/blob/2759935c851538afcdbde8fef748b861abdfdf92/Library/Source/NativeEngine.cpp#L460
does it create a new typedarray or keeps a reference on an existing one?

**Comment by bghgary** [comment]
Not sure. We need to find out. Typed arrays in JavaScript are intended to be backed by a native array.

**Comment by CedricGuillemet** [comment]
Does it make sense to close this issue?

**Comment by bghgary** [comment]
Closing as we have to copy now due to security restrictions.
