### ISSUE TITLE
Playground demo: crash on MacOS/iOS in NAPI_THROW_IF_FAILED for OSX Mojave and iOS 12

### ISSUE THREAD

**Issue by imbrig** [BabylonJS/BabylonNative#199]
Related to https://github.com/BabylonJS/BabylonNative/issues/165

Commit:922b1eebd59b58ae2618f54141d491ff55f3ff43 [922b1ee] but it was still occurring several commits back.
MacBook Pro (15-inch, 2018)
MacOS Mojave 10.14.6
XCode Version 11.3
Python 3.7.7
cmake version 3.17.0
Followed the directions on the Readme.

Running Playground app from Xcode both iOS and OSX, `loader.LoadScript("babylon.max.js");` is called. `NAPI_THROW_IF_FAILED(env, napi_run_script(env, Napi::String::New(env, string), sourceUrl, &result));` throws at `OpaqueJSValue *retValue = const_cast<OpaqueJSValue*>(JSEvaluateScript(env->m_globalContext, statement, nullptr, JSStringCreateWithUTF8CString(sourceUrl), 1, &exception));`

![Screen Shot 2020-03-31 at 3 19 09 PM](https://user-images.githubusercontent.com/47464835/78080447-1933c080-7363-11ea-9775-eb155e6bc621.png)

Since I have bootcamp and Windows 10 VS2019, I tried it there and the Playground worked.
Someone I know has the same hardware but on Catalina(10.15.4) and XCode 11.4 and the Playground worked without issues on both OSX and iOS.

**Comment by bghgary** [comment]
This is odd. It works fine for me.

**Comment by bghgary** [comment]
I'm confused by this.

1. The address with EXC_BAD_ACCESS is not any of the values of the variables. So what is the code trying to access?
2. The sourceUrl is "" and it should be "babylon.max,js" if it's loading "babylon.max.js"

I suspect this is crashing when calling `loader.Evel("document = {}", ""` in ViewController.mm.

**Comment by bghgary** [comment]
@imbrig Can you send a screenshot with the value of env->m_globalContext?

**Comment by imbrig** [comment]
@bghgary I'm sorry, but I've updated to Catalina 10.15.4 and with just that, everything works and nothing is being thrown on OSX. I'm going to test iOS but I think that it'll also work there.

**Comment by imbrig** [comment]
@bghgary I celebrated too early, while OSX did work I got the same throw on iOS. Here's the value of env->m_globalContext
![Screen Shot 2020-03-31 at 6 06 29 PM](https://user-images.githubusercontent.com/47464835/78088955-aa626180-737a-11ea-8a9e-ea03b2f1cd8c.png)

**Comment by imbrig** [comment]
![Screen Shot 2020-03-31 at 6 14 30 PM](https://user-images.githubusercontent.com/47464835/78089220-92d7a880-737b-11ea-8a8a-dad65b151798.png)

**Comment by CedricGuillemet** [comment]
@imbrig Are you in sync with master branch? Fix has been pushed to master regarding JSC and I hoped it would prevent that crash.

**Comment by bghgary** [comment]
The first comment said commit 922b1ee which is the tip of master.

**Comment by ptc-rgrasset** [comment]
retested on my side with tip, same issue (ScriptLoader::Eval -> NAPI::Eval -> napi_run_script() -> crash).
If I comment `loader.Eval("document = {}", "");` in ViewController.mm, it will crash later at the same place in napi_run_script() but now called from ScriptLoader::LoadScript.

**Comment by CedricGuillemet** [comment]
I'm taking a look!

**Comment by imbrig** [comment]
@bghgary My test device is an iphone 8 with (12.2) which was running into that throw. I tried my personal iphone XS with (13.3) and it worked and did not encounter the throw.

So the take away for me was on OSX Mojave and iOS (12) run into the throw, while OSX Catalina and iOS (13) work perfectly.

**Comment by imbrig** [comment]
So I've just tested on the device which was throwing iPhone 8 iOS (12.2) and it's still throwing. Can't test on OSX Mojave since I've updated to Catalina and that works. On the iPhone XS iOS (13.3) the playground works fine and doesn't throw. I guess there are some os restrictions, but I did hope that iOS 12 would be supported. For now I'll continue on iOS 13.

Thank you all for the quick responses and the awesome work on Babylon!

**Comment by bghgary** [comment]
Thanks for helping with testing @imbrig! One of things that this project can use more of is testing. In general, I think we would like to support as many versions as possible, so we will look into this more.

**Comment by bghgary** [comment]
I think I found the issue. I ran into this problem on Windows (of all places) trying to run Android with JSC. The issue stems from https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/napi/source/js_native_api_JavaScriptCore.cc#L902 which is casting a JSValueRef to a JSStringRef which is illegal. I changed this to call JSValueToStringCopy and that fixed the issue. I'll submit a PR shortly.

**Comment by bnolan** [comment]
Thanks @bghgary - I put that fix in:

```
napi_status napi_run_script(napi_env env,
              napi_value script,
              const char* sourceUrl,
              napi_value* result) {
  JSStringRef statement = JSValueToStringCopy(env->m_globalContext, reinterpret_cast<JSValueRef>(script), nullptr);
  JSValueRef exception;
  OpaqueJSValue *retValue = const_cast<OpaqueJSValue*>(JSEvaluateScript(env->m_globalContext, statement, nullptr, JSStringCreateWithUTF8CString(sourceUrl), 1, &exception));
  if (!retValue) {
    DumpException(env, exception);
  }
  *result = reinterpret_cast<napi_value>(retValue);
  return napi_ok;
}
```

And the playground runs without crashing on Mojave (10.14.6).

**Comment by CedricGuillemet** [comment]
Don't forget to add:
```
JSStringRelease(statement);
```

**Comment by ptc-rgrasset** [comment]
Tested with the change from @bnolan, also works for me !
