### ISSUE TITLE
Playground doesn't initialize the console

### ISSUE THREAD

**Issue by bnolan** [BabylonJS/BabylonNative#204]
The playground doesn't call `Babylon::Polyfills::Console::Initialize(env, ...);` so all the console log statements don't log out to stdout.

**Comment by syntheticmagus** [comment]
@bnolan I think this has something to do with Safari's debugging capabilities; `Console` was removed from Apple targets because you can use Safari to debug JS there, which will provide its own `console.log` implementation. @CedricGuillemet, is that correct?

**Comment by CedricGuillemet** [comment]
Yes @syntheticmagus , you are right. The Safari console provides more display options.

**Comment by CedricGuillemet** [comment]
Closing.
