### ISSUE TITLE
drawElementsType and drawArrayType should be more robust

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#216]
Make sure uninindexed draw calls work.

**Comment by CedricGuillemet** [comment]
unindexed drawcalls work. Tested with pointcloud rendering.

**Comment by CedricGuillemet** [comment]
drawElements is now robust enough to be able to run multiple PG (PP, point cloud, RTT,...). More work on draw call will appear but it will be related to a more complex use case. Closing.
