### ISSUE TITLE
Add a JavaScript way of loading scripts

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#219]
Perhaps replace Tools.LoadScript with a custom implementation for Babylon Native.

**Comment by syntheticmagus** [comment]
My understanding from a long time ago was that the plan for this was to get the text of the desired JS file via network request, then just `eval` it. Does this solution still seem viable? If so, is this a change we should make to `Tools.LoadScript` on the Babylon.js side?

**Comment by CedricGuillemet** [comment]
Yes, I'm starting to think it would be better to do the work only on the js side. I'll try to do that instead.

**Comment by CedricGuillemet** [comment]
Fixed with this PR : https://github.com/BabylonJS/Babylon.js/pull/8998 Closing.
