### ISSUE TITLE
Investigate JSI as replacement for NAPI

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#225]
<strike>Implement a version of NAPI that will support React Native's JSI interface.</strike>
Implementing NAPI against JSI is a nightmare.

Currently investigating implementing JSI directly instead of NAPI.

For reference, JSI already has implementations for multiple JS VMs:
- [Chakra](https://github.com/microsoft/react-native-windows/blob/master/vnext/JSI/Shared/ChakraRuntime.h)
- [V8](https://github.com/microsoft/v8-jsi)
- [JSC](https://github.com/facebook/react-native/tree/ede2c5031f93068c93786a550ef4def9f84e6b16/ReactCommon/jsi)
- [Hermes](https://github.com/facebook/hermes)

TODOs:
- [X] Prototype NativeEngine with JSI instead of NAPI
- [ ] Measure performance of NativeEngine with JSI compared to NAPI

**Comment by ryantrem** [comment]
Some JSI experiments/tests are available here:
- https://github.com/BabylonJS/Babylon.js/blob/62359f77e9ac03081a4c0ffc2e856f6e7a5c9f69/src/Engines/Extensions/index.ts#L16-L18
- https://github.com/BabylonJS/Babylon.js/blob/eecd7be9356caabef655429a2ac0fc2447bdb640/src/index.ts#L12
