### ISSUE TITLE
Handle BOM and other encoding in url request

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#228]
For Android:
- https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Dependencies/UrlLib/Source/Android/UrlRequest.cpp#L74
- https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Dependencies/UrlLib/Source/Android/UrlRequest.cpp#L108

For Apple:
- https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Dependencies/UrlLib/Source/Apple/UrlRequest.mm#L76

UWP appears to be okay for BOM but still should do something about content-type.

TODO:
- [ ] Handle BOM correctly for Android / Apple
- [ ] Investigate handling of content-type for HTTP
- [ ] Investigate file encoding on Win32. See [UrlRequest_Win32.cpp:68-85](https://github.com/BabylonJS/UrlLib/blob/0cd1dcae12fbf8943e81e496af3e4047f20c32b0/Source/UrlRequest_Win32.cpp#L68-L85).

**Comment by bghgary** [comment]
One possible example where this would break is if a glTF file has a BOM, some platforms would not be able to parse it.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
