### ISSUE TITLE
Polyfills::Window destroyed while evaluating script

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#236]
When running Win32 ValidationTests App, polyfills::Window is destroyed when loading babylon.material.js
I (kinda) fixed it by adding a reference Window::Initialize
```
        napi_ref result;
        napi_create_reference(env, jsWindow, 1, &result);
```
This doesn't happen with the Linux Validation App.

**Comment by bghgary** [comment]
#235 probably fixes this, but I haven't tested. The issue is in https://github.com/nodejs/node-addon-api/pull/714.

**Comment by CedricGuillemet** [comment]
I did another try today. I still get the crash win x86 but not x64. Windows + Chakra.
To experience it, compile and run ValidationTests in 32bits mode on Windows.
