### ISSUE TITLE
Android Playground Example animated glb models are not loading

### ISSUE THREAD

**Issue by atul109** [BabylonJS/BabylonNative#254]
After loading the model completely log will show loaded and then crashes
[Loaded GLB model](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/BrainStem/glTF-Binary/BrainStem.glb)

`A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18892 (tive.playground), pid 18724 (tive.playground)`

**Comment by CedricGuillemet** [comment]
Hi @atul109 
What's the platform (OS) you tried to load with?

**Comment by atul109** [comment]
@CedricGuillemet OS: Android 10, phone model : SM-G965F/DS

**Comment by CedricGuillemet** [comment]
The crash you experience is related to this issue : https://github.com/BabylonJS/BabylonNative/issues/211
Once that issue is resolved, loading that glb will be fine.
Closing.
