### ISSUE TITLE
Mismatch in sampler "stage" indices

### ISSUE THREAD

**Issue by acoget** [BabylonJS/BabylonNative#260]
Test case: Load marble.js with BabylonNative. Tested on Windows by replacing ShaderCompilerD3D by ShaderCompilerOpenGL and switching init.type to bgfx::RendererType::OpenGL in NativeEngine.cpp.
Expected: The file loads and displays the model.
Result: While displaying the first frame, GL_INVALID_OPERATION is thrown by the reflection texture binding operation.

The line throwing the error is in renderer_gl.cpp. The texture object for a given stage has the correct binding target, but the program info for that stage has a different binding target. Since the program info target is the one used in the function call, if there's a mismatch, GL_INVALID_OPERATION gets thrown. In this case, the reflection texture needs GL_TEXTURE_CUBE_MAP_EXT but gets GL_TEXTURE_2D.
https://github.com/syntheticmagus/bgfx/blob/aac758b7c1c6b671135b99595a921c8bcc27cf73/src/renderer_gl.cpp#L7781

The problem isn't the target data, but the indexing of samplers into bgfx, which is called "stages". Which texture is linked to which stage is controlled by SetTexture(). Tracking down exactly where that comes from was difficult, since it goes back and forth between C++ and JS a bunch of times. The actual source location is createProgram(), specifically CreateSampler() in NativeEngine. Here, the stage index comes from **the layout binding location from SPIRV-Cross**.
https://github.com/BabylonJS/BabylonNative/blob/83c0f4a45be97a403c066f78119f6e88b6bb123b/Plugins/NativeEngine/Source/NativeEngine.cpp#L121

Meanwhile, the program info in bgfx is set internally. The stage or index for a given sampler is **the order in which it's encountered while iterating through indices with glGetProgramResourceiv()**. That order, as far as I can tell, is completely implementation-dependent and under no obligation to match with binding locations, which the Babylon shaders are not specifying explicitly anyway.
https://github.com/syntheticmagus/bgfx/blob/aac758b7c1c6b671135b99595a921c8bcc27cf73/src/renderer_gl.cpp#L4940

A workaround for the crash is to use the texture's target instead of the program info's target. But that still results in a lot of black pixels, so I suspect the mismatch is causing a lot of issues inside bgfx. I'd argue bgfx is doing things wrong here, but the problem is only showing up because Babylon is sourcing those indices from elsewhere. The issue probably doesn't occur or at least not in the same way if ARB_program_interface_query isn't available.

**Comment by bghgary** [comment]
> the file does not work with D3D either

I just loaded the marble.js with the Win32 build using D3D and it works fine. What is wrong with the D3D version?

**Comment by acoget** [comment]
It now loads properly so that might just have been a bad sync. I'll edit the main description.

**Comment by CedricGuillemet** [comment]
Closing thanks to the glslang approach fixes
