### ISSUE TITLE
Session is being stored as a shared_ptr rather than unique_ptr

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#265]
This was introduced as part of my change #263. We are making use of Arcana to make the creation of the XR Session asynchronous, however as part of this change we had to declare the pointer that is returned as a shared_ptr rather than a unique_ptr, because arcana does not properly handle returning expected values as const refs, and is instead defaulting to the copy constructor implementation of expected.result.

The new declaration of CreateAsync in XR.h is here:
static arcana::task<std::shared_ptr<Session>, std::exception_ptr> CreateAsync(System& system, void* graphicsDevice);

The expected declaration would be:
static arcana::task<std::shared_ptr<Session>, std::exception_ptr> CreateAsync(System& system, void* graphicsDevice);

The current declaration of the consumer in nativexr.cpp is:
        return xr::System::Session::CreateAsync(m_system, bgfx::getInternalData()->context).then(arcana::inline_scheduler, m_cancellationSource, [this](std::shared_ptr\<xr::System::Session\> session) {
            m_session = std::move(session);
        });

The expected declaration in nativexr.cpp is:
        return xr::System::Session::CreateAsync(m_system, bgfx::getInternalData()->context).then(arcana::inline_scheduler, m_cancellationSource, [this](std::unique_ptrr\<xr::System::Session\> session&&) {
            m_session = std::move(session);
        });

**Comment by Alex-MSFT** [comment]
When addressing this, we should also be sure to move the Session constructor to private rather than Public.  Right now it is currently being kept public for usage with make_shared

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
