### ISSUE TITLE
Attach an existing prebuilt NAPI addon as plugin.

### ISSUE THREAD

**Issue by dcerisano** [BabylonJS/BabylonNative#271]
I have a pre-built NAPI addon (built using `node-addon-api`)  that I want to load into V8 as a javascript module. I can't use NodeJS for this "because reasons".

Creating NAPI addons is extremely labour intensive - it would be great if existing addons could be leveraged in BN as plugins (which are also `node-addon-api` based).

Does the BN Plugin architecture support loading pre-built NAPI addons?

Also, thanks very much for the Linux port!

**Comment by bghgary** [comment]
It depends. If you use strictly the JS part of NAPI (i.e. you don't use any of the node specific things), then it should work. If this is the case, the documentation [here](https://github.com/BabylonJS/BabylonNative#build-system-and-extensions) should help you get started.

**Comment by dcerisano** [comment]
Thanks very much for your reply.

I am on Linux. The current Linux build for BN targets the JavaScriptCore engine. Will BN run with V8 on Linux?

**Comment by bghgary** [comment]
I know V8 works on Android/Windows. I'm not sure what steps are necessary to get V8 to work on Linux. @CedricGuillemet may know more.

**Comment by CedricGuillemet** [comment]
V8 should be supported on Linux with limited change to the cmake scripts. I didn't add V8 to Linux because I didn't find a repo with prebuilt binaries. If you know a repo/npm/... with v8 binaries, I'd be happy to add support for it.

**Comment by dcerisano** [comment]
@CedricGuillemet thanks very much. We just happen to have exactly what you are looking for.

[Here is a link to our public GitLab repo with v8 binaries.](https://gitlab.com/Distributed-Compute-Protocol/dcp-foss/v8-build/uploads/fc3e8755455ff0117088e13d3c4e7dd8/v8-7.5.288.23-4-Linux.zip)

**Comment by thomlucc** [comment]
Answered
