### ISSUE TITLE
Some shaders load as infinitely large black textures when loading from GLTF

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#279]
When loading certain models some shaders are loading as infinitely large black textures.

Repro steps:

1.) Uncomment the following line in the Playground test app:
BABYLON.SceneLoader.AppendAsync("https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf")

2.) Run the app

Potentially relevant Traces from the ARCore session
[https://app.zenhub.com/files/189081889/a9b2c6a7-8957-480a-9336-e78bab8f01aa/download](https://app.zenhub.com/files/189081889/a9b2c6a7-8957-480a-9336-e78bab8f01aa/download)

**Comment by CedricGuillemet** [comment]
I did the test but didn't get any error. Does it happen on a device? Can you check that your emulator opengl settings has opengl es 3+ enabled?

**Comment by Alex-MSFT** [comment]
This repros for me on device.  Might be more apparent if you enter XR mode.
