### ISSUE TITLE
OpenGL(ES) and uniforms

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#29]
Some problems I encountered:
- shader uniforms inside a struct named 'Frame' when linking shader, the size of that struct differs between VS and FS resulting in a non linking shader. I did a string replace for now to remove it as bgfx doesn't support uniform struct
- bgfx only supports mat4x4 and vec4 uniform I get a driver error when trying to set a vec4 on a vec3 uniform
- for now, I tweak the shader string instead of passing in glslang. It might not be useful to pass the shader with glslang on Android. I see multiple benefits: smaller binary, faster shader loading. Might evaluate that in the future.

**Comment by CedricGuillemet** [comment]
No vertex attribute remap in glslcompiler like with hlslcompiler ?

**Comment by CedricGuillemet** [comment]
face culling seems inverted on opengl

**Comment by CedricGuillemet** [comment]
open gl needs version #430 before sending to bgfx
no version needed for opengl es

**Comment by CedricGuillemet** [comment]
Biggest issue so far: converting non-vec4 uniform to vec4 or the call to set the value will fail. I'm wondering it a simple GLSL AST parser will do the job instead of glslang.

**Comment by bghgary** [comment]
Babylon.js has a shader processor specific for the native implementation that can handle most of these issues. Let's discuss offline.

**Comment by CedricGuillemet** [comment]
Fixed thanks to the shader preprocessor!
