### ISSUE TITLE
UWP with broad file system access in libcurl fails

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#3]
For UWP, we have `<rescap:Capability Name="broadFileSystemAccess" />` set in the [manifest](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions) and have enabled in [the settings to allow the app](https://www.tenforums.com/tutorials/104030-allow-deny-apps-access-file-system-windows-10-a.html).

libcurl eventually calls the [C open API](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen) (which eventually calls CreateFileW), but this returns -1.

We currently have a fallback mechanism to use Windows::Storage::StorageFile::GetFileFromPathAsync instead, but it would be nice to see if we can get libcurl to work with `broadFileSystemAccess`.

**Comment by CedricGuillemet** [comment]
CURL issues centralized here : https://github.com/BabylonJS/BabylonNative/issues/96
