### ISSUE TITLE
Remove dependency on SPIRV-Cross for OpenGL scenarios

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#300]
When the target rendering path is OpenGL, SPIRV-Cross should not actually be necessary because glslang should be sufficient to do all our required conversions on its own. Note that to make this change, all of the logic in `NativeEngine::CreateProgram` that depends on SPIRV-Cross types will need to be rewritten to use glslang instead; that logic should probably also be pulled out of `NativeEngine`, too. This is therefore expected to be a fairly large change that will affect behavior in every rendering path because it will change how the bgfx shader representations are created.

**Comment by bghgary** [comment]
Reopen if we have a need to make this work.
