### ISSUE TITLE
Enable rendering to an externally-provided render target

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#315]
Rendering to external RTTs is already supported by and implemented in the NativeXr plugin, but it's an implementation detail. Create a new Plugin or other mechanism to allow an arbitrary external RTT to be used as a render target.

NOTE: It is possible that this may disappear inside the alternative initialization options for `NativeEngine`, at which point it would not be a plugin but just an implementation detail of `NativeEngine`.

**Comment by syntheticmagus** [comment]
If this does end up being a plugin (lots of remaining investigation to figure out if that's the right answer), should it live in this repo? Or should that be something that lives off somewhere else to be brought in for specialized use cases?

**Comment by bghgary** [comment]
This is covered by the [ExternalTexture](https://github.com/BabylonJS/BabylonNative/blob/master/Plugins/ExternalTexture/Readme.md) feature.
