### ISSUE TITLE
Add CI to ingest Babylon.js nightly

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#316]
A few times, we've encountered issues where a change was introduced to Babylon.js which broke the integration with Babylon Native, but we didn't catch it quickly (sometimes not for months) because our FI from Babylon.js is a manual process currently undertaken only when we need a new feature. An automatic FI with validation tests will help us know quickly when the integration with Babylon.js master is broken so that we can address the problem in a timely manner.

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/397

**Comment by bghgary** [comment]
Done.
