### ISSUE TITLE
Consider non-thread-owning AppRuntime alternative

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#317]
`AppRuntime` currently encapsulates both JavaScript thread creation and JavaScript context initialization. Consider splitting these behaviors, or creating an `AppRuntime` alternative that contains only the context initialization, for scenarios where apps want `AppRuntime`-like encapsulation without creating a new thread.

**Comment by bghgary** [comment]
Reopen if this is still useful.
