### ISSUE TITLE
Error while running on HoloLens 2 Emulator

### ISSUE THREAD

**Issue by Chalghouma** [BabylonJS/BabylonNative#327]
When running an UWP app built for the HL2 Emulator, it gets stuck.
![image](https://user-images.githubusercontent.com/17048203/87479517-85d97f00-c623-11ea-80cd-f899cfa5f44a.png)

**Steps to reproduce**
1. Clone the repository
2. Run this command `cmake -D CMAKE_SYSTEM_NAME=WindowsStore -D CMAKE_SYSTEM_VERSION=10.0 -A x64 ..` from a new child folder
3. Update the `vr` and `ar` booleans inside `experience.js` to `true`
4. Launch the app in debug mode. (or sideload it and upload the .msix through the portal)

**Used OS**
- Desktop: 64-bit - Windows 10 Pro with OS.Build: 19041.329
- HoloLens 2 Emulator version: 19041.1106
`

**Comment by bghgary** [comment]
We've figure out some things. It seems our WebXR controllers support is broken. For now, if I comment out this [line of code](https://github.com/BabylonJS/BabylonNative/blob/master/Core/AppRuntime/Source/AppRuntimeChakra.cpp#L51) and disable controllers in the HL2 emulator, I was able to get the cube to render in the HL2 emulator.

**Comment by syntheticmagus** [comment]
#328 is expected to fix this.

**Comment by Chalghouma** [comment]
Yes, I'm able to enter the XR experience on HL2.
Thank you for your reactivity @syntheticmagus and @bghgary
