### ISSUE TITLE
Babylon.VideoTexture.CreateFromWebCamAsync should work

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonNative#334]
Babylon.VideoTexture's [CreateFromWebCamAsync](https://doc.babylonjs.com/api/classes/babylon.videotexture#createfromwebcamasync) should work so that a RN app can use BabylonJS/BabylonReactNative for non-XR scenarios.

**Comment by bghgary** [comment]
@hendryems We moved this to the icebox since it's not needed for 4.2 (Nov release). Let us know if you want it back in the backlog.

**Comment by CedricGuillemet** [comment]
Current state:
- [x] iOS functional
- [ ] Android in progress
- [ ] Win32/UWP not started

First PR to be reviewed when Android and iOS will be functional.
To do after the 1st PR:
- [ ] support front/back camera (need some changes in bjs)
- [ ] test and improve camera lost device/app switch while streaming
- [ ] win32/uwp if any interest
- [ ] MacOS if any interest
- [ ] Linux if any interest

iOS version is pretty simple with texture override and BGRA32 texture provided by the API.
Android version needs a surface and provides an OES texture that might need a conversion for bgfx. Surface + Surface texture created at runtime using JNI. Still working on that part.

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/614

**Comment by bghgary** [comment]
Closing for now. Support for API level 24 is in. If we need API level 21, we can open a new issue.
