### ISSUE TITLE
Logic in NativeXr.cpp and XR.cpp should be split into multiple files

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#343]
Looking into NativeXr.cpp and XR.cpp, a lot of classes are currently defined in a single file. This does not make for great legibility. For example, function definitions in XR.cpp (OpenXR) for System::Sesssion, System and System::Session::Frame are mixed in order throughout. I believe it would improve legibility if we started splitting this logic into separate files.

**Comment by bghgary** [comment]
Reopen if we find this to be annoying and want to split.
