### ISSUE TITLE
[NativeXR] RenderTargets lifecycle

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#344]
When a color texture is destroyed (rotation on iOS for example), the rendertarget linked to that texture is also destroyed:
https://github.com/BabylonJS/BabylonNative/blob/38aa6f455357932b31c4ef56860393b68a1d1453/Plugins/NativeXr/Source/NativeXr.cpp#L305
The issue happens when that rendertarget is still bound in NativeEngine. We end up with a dangling pointer https://github.com/BabylonJS/BabylonNative/blob/38aa6f455357932b31c4ef56860393b68a1d1453/Plugins/NativeEngine/Source/NativeEngine.h#L279

To mitigate this issue, I unbind the rendertarget to be destroyed if it's bound. And do not assert here https://github.com/BabylonJS/BabylonNative/blob/38aa6f455357932b31c4ef56860393b68a1d1453/Plugins/NativeEngine/Source/NativeEngine.h#L261

My first thought was to use a smartpointer so the rendertarget will only be destroyed when it's unbound. This *might* not be the good approach because the textures bound to that rendertarget are already destroyed and bgfx will assert at some point...or overriding bgfx render target texture with a dummy one until it's released.

**Comment by syntheticmagus** [comment]
This seems odd. As I understand it, framebuffer binding and unbinding should always happen in pairs, so a non-default framebuffer state should never happen except when the JS thread is actively rendering, and frame transitions should only occur between rendering cycles. Have I gotten myself confused somewhere? If not, then any encounter with a bound framebuffer during frame transition (which is the only time, I think, that textures should be getting deleted) may be indicative a deeper/weirder problem.

**Comment by ryantrem** [comment]
If sounds like one of the symptoms of this was leaked memory when the display is rotated. I will check this scenario with the latest code as part of my overall current work looking for and trying to fix memory leaks.

**Comment by rgerd** [comment]
Here's the callback that should be run to unbind the framebuffer (and clear the pointer reference in the frame buffer manager) when the texture is destroyed:
https://github.com/BabylonJS/BabylonNative/blob/b766c35f2bc6a42c2b26d672fbcebe9c4c0eaaad/Plugins/NativeXr/Source/NativeXr.cpp#L390-L402

The PR that introduced it is #342.

It seems like this callback essentially fixes this issue, although as you mentioned @CedricGuillemet there's a definite possibility for improvement with smart pointers.

**Comment by ryantrem** [comment]
@rgerd I see that code executing when I rotate the device (for example). Is there anything else you think needs to be checked for this, or shall we close this out?

**Comment by rgerd** [comment]
@CedricGuillemet It seems like the bug is mostly resolved. Did you want to investigate further?

**Comment by CedricGuillemet** [comment]
Tested and it works for me. Closing.
