### ISSUE TITLE
PointCloudSystem crashes BabylonNative when calling BuildMeshAsync

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#347]
The PointCloudSystem does not work on BabylonNative due to a failure in CreateIndexBuffer

1.) Add the following 3 lines to the sample app experience.js (or use attached experience.js file)
```
var pcs= new BABYLON.PointsCloudSystem("pcs", 1, scene);
pcs.addPoints(10000);
pcs.buildMeshAsync();
```

2.) Run the sample app, and observe it crashes on an assert in NativeEngine::CreateIndexBuffer

[experience.txt](https://github.com/BabylonJS/BabylonNative/files/5003570/experience.txt)

**Comment by CedricGuillemet** [comment]
Thanks for the repro, Alex. The first issue is 0sized IndexBuffer. I fixed it with a check in the JS code. But I have another issue deeper in the code related to shader compilation...Investigating.

**Comment by CedricGuillemet** [comment]
I've fixed the shader compilation but now some functions in the native engine JS are missing...
