### ISSUE TITLE
Thread resume for UWP and other platforms

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#35]
Done for WIN32
missing for
- [x] UWP
- [x] Android
- [ ] iOS
- [ ] MacOS

Just a reminder here
https://github.com/microsoft/arcana.cpp/issues/4

**Comment by CedricGuillemet** [comment]
@syntheticmagus : Specifically, a reminder to switch over to using dispatcher features to suspend and resume as soon as such features are available.

**Comment by bghgary** [comment]
@CedricGuillemet Can you verify this is working now? If so, please close.

**Comment by CedricGuillemet** [comment]
It's not fixed for MacOS. When minimizing the window, I get a crash and this error in the log:
```
libc++abi: terminating with uncaught exception of type std::runtime_error: SafeTimespanGuarantor can only be locked from a closed state
```

**Comment by bghgary** [comment]
@CedricGuillemet Can you see if this is still an issue?
