### ISSUE TITLE
Improve Vertex Buffer Binding

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#361]
Vertex array record and binding are using index buffer https://github.com/BabylonJS/Babylon.js/blob/a6f95436b9e6e8483997211e8fa405db3121f104/src/Engines/nativeEngine.ts#L372
As Gary said:
'Technically speaking, a VAO (at least for WebGL) doesn't include the index buffer. Maybe we should separate these into separate functions like it is in WebGL.'
More over, bindBuffers destroys and recreate a new vertexarray doing too many allocations and destructions https://github.com/BabylonJS/Babylon.js/blob/a6f95436b9e6e8483997211e8fa405db3121f104/src/Engines/nativeEngine.ts#L400

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
