### ISSUE TITLE
Left eye rendering seems broken for the Playground app on HoloLens 2

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#362]
Right eye rendering seems to work as expected. Left eye rendering fails to draw content in the center of the display.

**Comment by bnolan** [comment]
I get this same bug on Odyssey Plus WMR. Right eye works fine, left eye works ok but when you move your head in certain orientations it's like a clipping plane moves through the cube or something and the cube disapears in the left eye, right eye keeps rendering properly.

**Comment by syntheticmagus** [comment]
@chrisfromwork, can you confirm this no longer repros after #386?

**Comment by chrisfromwork** [comment]
Yeah, this now looks a lot better. Thanks! :)
