### ISSUE TITLE
Support for hardware camera - to get pose/projection matrix, etc

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonNative#363]
BabylonNative should support/expose out the hardware camera so that clients will be able to get the pose/projection of the AR camera.

E.g.
- [Babylon.Camera.getViewMatrix](https://doc.babylonjs.com/api/classes/babylon.camera#getviewmatrix)
- [Babylon.Camera.getProjectionMatrix](https://doc.babylonjs.com/api/classes/babylon.camera#getprojectionmatrix)

This is to get parity to the following:
- [Camera.cameraToWorldMatrix](https://docs.unity3d.com/ScriptReference/Camera-cameraToWorldMatrix.html)
- [Camera.projectionMatrix](https://docs.unity3d.com/ScriptReference/Camera-projectionMatrix.html)

**Comment by bghgary** [comment]
These should already be working. Would be good to verify.
