### ISSUE TITLE
Setting AbstractMesh.showBoundingBox to true crashes BabylonNative

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#368]
Repro steps:
1.) Add this line to the experience.js playground:
`scene.meshes[0].showBoundingBox = true;`
2.) Run the app it will crash with on the below line:
![image](https://user-images.githubusercontent.com/27031140/90074865-ec989980-dcb0-11ea-8f5f-36c0a0b0ca1d.png)

Observations:
Callstack seems to be related to the fact that the _gl (WebRenderingContext) is undefined.

**Comment by bghgary** [comment]
Yup, that function (and probably related functions) needs to be overridden in the nativeEngine.ts

**Comment by CedricGuillemet** [comment]
I'm taking a quick look. It should be pretty easy to fix.
