### ISSUE TITLE
Missing Lighting Estimation from ARKit/ARCore

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonNative#369]
WebXR Lighting Estimation [specs](https://github.com/immersive-web/lighting-estimation/blob/master/lighting-estimation-explainer.md)

This need to get exposed (or some forms of it) such that [ARKit](https://developer.apple.com/documentation/arkit/arlightestimate) and [ARCore](https://developers.google.com/ar/develop/unity/light-estimation) implementations can get surfaced.

**Comment by bghgary** [comment]
Please include @chrisfromwork when implementing this.

**Comment by bghgary** [comment]
Similar work item on the Babylon.js side: https://github.com/BabylonJS/Babylon.js/issues/8904

**Comment by bghgary** [comment]
@RaananW Do you have an idea of when the Babylon.js side will be implemented?

**Comment by andrewmo2014** [comment]
Looks like light estimation on Babylon.js side has been completed since https://github.com/BabylonJS/Babylon.js/pull/11117 CC @bghgary, @RaananW

In summary, introducing xr light estimation and exposing brightness/intensity will help detect if the environment is "too dark"

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
