### ISSUE TITLE
Normals map not rendering correctly with BabylonReactNative demo app

### ISSUE THREAD

**Issue by RonnieAshlock** [BabylonJS/BabylonNative#371]
Rendering like this in the demo app:

![image.png](https://images.zenhubusercontent.com/5efb7d8ce397006536736e73/210d2dd3-58b9-44a2-ae50-6b658159f49f)

Same asset loaded in Sandbox:

![image.png](https://images.zenhubusercontent.com/5efb7d8ce397006536736e73/590623ac-befe-4b73-bcf7-1d8feb04d20f)

To repro, use this asset:
https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/Head/Head_512Tex.glb

**Comment by ryantrem** [comment]
May be related to #339
