### ISSUE TITLE
GLBs using ORM map in BabylonReactNative demo app will not render properly

### ISSUE THREAD

**Issue by RonnieAshlock** [BabylonJS/BabylonNative#372]
Possibly related to #371

It looks like the OcclusionRoughnessMetallic map is not being rendered when loaded in the BabylonReactNative demo app.

In Sandbox:
![image.png](https://images.zenhubusercontent.com/5efb7d8ce397006536736e73/54d6166a-f355-4410-ac2e-2486c2f8877d)

In the demo app:
![Screenshot_20200818-095403.jpg](https://images.zenhubusercontent.com/5efb7d8ce397006536736e73/29281685-774b-4b26-bc45-ae8e2675faca)

![Screenshot_20200818-095411](https://user-images.githubusercontent.com/60451995/90544349-e173bc80-e13b-11ea-8a45-9e25c26adcef.jpg)

Here's the asset used in the test:
https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/air_compressor_512_ORM.glb

**Comment by bghgary** [comment]
Caused by the same underlying issue:
https://github.com/BabylonJS/BabylonReactNative/issues/61
https://github.com/BabylonJS/BabylonReactNative/issues/70
