### ISSUE TITLE
NativeRenderTargetProvider creates more RTTs than necessary in some cases

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#377]
As currently implemented, `NativeRenderTargetProvider` proactively creates one RTT per eye at the moment when it's constructed, even when only one eye will ever be used. This should probably be switched to a lazy approach: populate the initial array with invalid values and only create them when they're first requested.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
