### ISSUE TITLE
Enable surface reconstruction for windows mixed reality + OpenXR 

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#392]
We want to be able to draw meshes obtained through windows mixed reality spatial surface observers and open xr. We do not believe that this feature will have a webxr counterpart and would like to enable the functionality in a new component within the babylon native codebase.

**Comment by blairmacintyre** [comment]
This should have a webxr counterpart, eventually.  See the discussion at https://github.com/immersive-web/real-world-geometry ... it would be great to have folks here push for features in WebXR that are needed.

**Comment by chrisfromwork** [comment]
@blairmacintyre that is the current plan. :)

Right now at Microsoft, we have folks working in the OpenXR group to define what a native application contract can look like for real world geometries (plane detection, mesh detection, object identification, etc.). Once this is figured out, we will be able to build a BabylonNative component to facilitate this functionality for native applications. That is what this task is tracking.

After agreeing upon a real world geometry OpenXR extension for native applications, folks will reach out to the WebXR group to talk through web vs native application security concerns. We would like to see real world geometry facilitated through WebXR in some form to unblock Babylon.js developers building for the web. My guess is that we all have a common interest in getting some form of these features into WebXR. :)

**Comment by chrisfromwork** [comment]
@blairmacintyre  If you're interested in tracking the current state of real world geometries in OpenXR, the scene understanding preview extension is in the process of reaching a public location (If I understand correctly, the Khronos working group has had a variety of feedback, so nothing is a 100% agreed upon), but documentation on XR_MSFT_scene_understanding_preview can be found here:
https://github.com/microsoft/OpenXR-MixedReality/blob/yl/scene_understanding_extension_preview/openxr_preview/specs/openxr.html

It seems that you have to download and view the html file locally as github doesn't currently support viewing such a large file.

**Comment by chrisfromwork** [comment]
As an update, we are going to prototype a WebXRMeshDetector feature in the Babylon.js codebase. We will define the xr BabylonNative API contract after getting buy in on this API.

**Comment by chrisfromwork** [comment]
we have some initial pull requests for this issue out now:

https://github.com/BabylonJS/Babylon.js/pull/9307
https://github.com/BabylonJS/BabylonNative/pull/476

**Comment by chrisfromwork** [comment]
Scene understanding work for UWP + OpenXR is now checked in. We have internal logic working for surface reconstruction winrt APIs. If anyone is interested in surface reconstruction compared to OpenXR's scene understanding API, feel free to reach out.
