### ISSUE TITLE
Implement blob and object url support

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#4]
https://github.com/BabylonJS/Babylon.js/blob/120cdb8cec65f678af92e37b319b87eb54fd079a/src/Engines/nativeEngine.ts#L265-L275

Object URL and blobs are currently not supported in the Native Engine; they are "hacked out," as shown at the link. Implement in order to achieve feature parity, enabling load progress.

**Comment by bghgary** [comment]
Blob and object url support was originally for GLB support, but Blob or object url isn't needed for GLB anymore.
