### ISSUE TITLE
Handle 3x3 matrices in the shader traversers

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#401]
Per the comment from @CedricGuillemet on #370, the existing scoping of symbol replacement in the shader traversers may be overly restrictive, excluding 3x3 matrices when really we need those matrices to be replaced. We should seek out a shader that requires a 3x3 matrix, confirm that replacement is required, then modify the shader traverser to correctly replace the 3x3 matrix with a 4x4 equivalent.

**Comment by bghgary** [comment]
Check if webgl supports 3x3 matrix. I seem to remember it's not, but I'm not sure.

**Comment by bghgary** [comment]
Pretty sure we don't have 3x3 matrix in Babylon.js. Reopen if we need this.
