### ISSUE TITLE
Mesh.MergeMeshes does not work correctly with multiple materials

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#408]
If you create two meshes (e.g. `Mesh.CreateBox`) and they each have a different material, and then you merge them with `Mesh.MergeMeshes([box1, box2], true, true, undefined, undefined, true)` the geometry merges as expected, but you end up with a single material which looks kind of like one of the original materials but without the alpha (or something like that). Same thing works fine in the Babylon.js Playground.

**Comment by CedricGuillemet** [comment]
Can you provide a playground so I can test it quickly?
