### ISSUE TITLE
[APPLE] Screenshots and bgfx reset flags

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#424]
In order to have screenshots working with Metal (for Validation tests), the bgfx reset flag with contain BGFX_RESET_CAPTURE or request screenshot will result in nothing to be done. Callback is not performed as well and validation tests will hang.
I don't want to add this flag for now on Apple platform until proper tests are being done.
This is annoying as bgfx Metal implementation differs from OpenGL/Direct3D.

**Comment by bghgary** [comment]
Can we fix it in bgfx?

**Comment by CedricGuillemet** [comment]
It should be fixed in bgfx so all platforms behave the same.

**Comment by bghgary** [comment]
Maybe file a bug on bgfx.

**Comment by CedricGuillemet** [comment]
With the bgfx version in this PR https://github.com/BabylonJS/BabylonNative/pull/467
The callback is performed but the data provided by bgfx are unusable.

**Comment by CedricGuillemet** [comment]
screenshots now works on iOS but not on MacOS.

**Comment by CedricGuillemet** [comment]
Issue created on bgfx repo : https://github.com/bkaradzic/bgfx/issues/2327

**Comment by CedricGuillemet** [comment]
It works with this fix: https://github.com/bkaradzic/bgfx/pull/2329 
I'll close this issue when bgfx update is done.
