### ISSUE TITLE
[TESTUNITS] XmlHTTPRequest polyfill

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#427]
XmlHTTPRequest is an essential part of Babylon Native is has a different implementation for each platform.
Make Unittest (playground that will be reference in browser) to test the various schemas (file, app, http, https), validate error handling (non existing local resource, error 40X, 50X) and fiability (large files)
And fix encountered issue like this one  : https://github.com/BabylonJS/BabylonNative/issues/292

Also, check the number of times the downloaded buffer is copied (from java to c++ on Android, can we take care of buffer refcount on iOS/MacOS ?)

**Comment by bghgary** [comment]
Related: https://github.com/BabylonJS/BabylonNative/issues/213

**Comment by CedricGuillemet** [comment]
xmlhttprequest does not handle times out properly. there is an exception on Apple and I'm not sure it's properly reported to the JS with an exception.

**Comment by darraghjburke** [comment]
#802 is tracking progress on unit testing

**Comment by bghgary** [comment]
Most of the testing is already implemented.
