### ISSUE TITLE
Android XMLHttpRequest makes too many byte buffer copies

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#445]
The Android implementation of `XMLHttpRequest` makes too many byte buffer copies and will likely limit the size of models we can download and load (e.g. in any of the Babylon.js model loading functions).
- We attempt to pre-allocate the right size buffer when reading the http response input stream, but we won't always know the right size (such as when the stream is compressed, or a size is simply not returned at all). In these cases, the Java `ByteArrayOutputStream` will be overly aggressive in resizing its internal byte buffer which will cause a lot of memory pressure.
- After we finish writing to the `ByteArrayOutputStream`, we call `ToArray` which makes a copy of the final byte buffer.
- When returning this byte array to native code, we make another copy into native memory.
- Not sure if we make more copies when passing back to the JavaScript side.

I'm not sure if we do better on iOS.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
