### ISSUE TITLE
What is the timeline for production-ready support for ReactNative?

### ISSUE THREAD

**Issue by ar-g** [BabylonJS/BabylonNative#446]
Hi folks, we're currently evaluating different options to render and interact with GLTF models. We have a ReactNative application. We're considering to implement this within the WebView and later add ReactNative support. We've tried Three.JS and it works well within WebView, but we couldn't make expo-gl and expo-three work to bridge into ReactNative.

We're wondering if we should pick BabylonJS for the time being and later add native support. What would be the timeline for production-ready support for ReactNative? We've tried the current version and it was much slower than rendering within a WebView. We've also experienced issues rendering some of the models on the WebView but not on the desktop browser.

**Comment by bghgary** [comment]
Thanks for your interest! We are planning on releasing a dot version of [BabylonReactNative](https://github.com/BabylonJS/BabylonReactNative) as part of the Babylon.js 4.2 release in Nov. Many features will be working, but there will be some gaps. It would great if you can try it out and let us know how it goes.

**Comment by bghgary** [comment]
If you have further questions, feel free to reach out to the team on the [forum](https://forum.babylonjs.com/) for faster responses.
