### ISSUE TITLE
BabylonNative solution generation should create Visual Studio solutions that support multiple platform flavors (x64, arm64, etc)

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#447]
Right now to develop for both x64 and arm64 we need to generate multiple Visual Studio solutions with cmake. It's unclear whether cmake supports generating a Visual Studio solution for multiple platform flavors. If it is possible, we should enable generating a single Visual Studio solution for multiple platform flavors. Visual Studio developers already doing cross platform development may have an expectation for this to just work.

**Comment by CedricGuillemet** [comment]
I'm not sure this is possible with MSVC
see https://gitlab.kitware.com/cmake/cmake/-/issues/18450
on MacOS, this is done with -DCMAKE_OSX_ARCHITECTURES=x86_64;arm64 but msvc seems more limited with its toolchain.

**Comment by bghgary** [comment]
Maybe investigate VS cmake support and see if that does anything for multi-platform.

**Comment by bghgary** [comment]
This is not possible with CMake.
