### ISSUE TITLE
Immersive BabylonNative experiences should work as expected with HoloLens 2 emulators

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#448]
Code that works correctly on physical HoloLens 2 devices does not appear to work correctly on HoloLens 2 emulators. It seems that on emulators we fail to correctly create an OpenXR session. 

Note: we will need to update hololens setup documentation when this issue is resolved.

**Comment by chrisfromwork** [comment]
installing the newest version of openxr through the windows store may unblock this issue for anyone that really needs emulators and is currently blocked.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
