### ISSUE TITLE
XR mode does not work without an internet connection

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#454]
The Babylon.js XR layer tries to download some kind of input device profile, and if you don't have an internet connection it throws an exception and fails. I tried the parameter to disable this behavior, but it still failed. This seems doubly broken, in that it should work by default without an internet connection without having to specify special params, and if you do specify those params it should definitely not fail. I haven't had a chance to dig in deeper, but as I said I'm pretty sure this is an issue in the Babylon.js layer.

**Comment by ryantrem** [comment]
@RaananW this is the issue we talked about last week. I didn't log it in the Babylon.js repo because I haven't had a chance to dig in any deeper.

**Comment by RaananW** [comment]
I'll take care of this later today or tomorrow.

**Comment by bghgary** [comment]
@ryantrem Babylon.js side is updated, can you validate this?

**Comment by ryantrem** [comment]
Validation is blocked on #465.
