### ISSUE TITLE
BabylonNative instructions for iOS development on Mac did not result in a successful build

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#475]
I have cloned the repo, initialized submodules and generated the Xcode project with the cmake command provided in BabylonNative setup instructions. I was able to iterate on/verify changes that I was making to the XR component in BabylonNative, but when attempting to build and deploy the Playground solution, I experienced linker errors (see attached).

I am using macOS Catalina 10.5 and Xcode 11.5.

Are there instructions for how to fix these build issues that we could also add to the documentation?

[iOS.BuildFailure.BabylonNativePlayground.txt](https://github.com/BabylonJS/BabylonNative/files/5461153/iOS.BuildFailure.BabylonNativePlayground.txt)

**Comment by bghgary** [comment]
@CedricGuillemet?

**Comment by CedricGuillemet** [comment]
The frameworks are not found. My guess is that you are targeting an iOS version (13.5) but you don't have that version installed.
To verify that, type `xcodebuild -showsdks`

If you don't see ios sdk 13.5, then install it and you should be able to build.
ping me on chat if it's present.

**Comment by chrisfromwork** [comment]
updating to xcode 12.1 and targetting a generic ios device seems to have fixed things.

**Comment by bghgary** [comment]
What version of xcode were you using before? Our readme says to use xcode 11 or higher. Do we need to update it?
