### ISSUE TITLE
GLB texture loading issue in BabylonNative

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#477]
I noticed inconsistent loading for GLB textures in BabylonNative on Android when loading a particular model from our test assets, but I'm guessing this is not specific to the model itself:  https://raw.githubusercontent.com/microsoft/experimental-pcf-control-assets/master/endcap_with_product.glb

When loading the model textures will often load incorrectly.  I have seen the way textures load incorrectly change occasionally as well.

Babylon.js: 
![image](https://user-images.githubusercontent.com/27031140/97736651-43846280-1a99-11eb-8477-b657c7438d81.png)

3D Viewer:
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/27031140/97736712-572fc900-1a99-11eb-8c7e-40ab2b6dd95e.png)

BabylonNative:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/27031140/97736728-5ac35000-1a99-11eb-9e5e-8f9710c3a341.png)

**Comment by Drigax** [comment]
Interesting, I'll start looking into this.

@Alex-MSFT your description states `When loading the model textures will often load incorrectly. I have seen the way textures load incorrectly change occasionally as well.`

Is "often" every time or intermittently?

**Comment by Alex-MSFT** [comment]
Intermittently.  I would say about 9/10 times.

**Comment by Alex-MSFT** [comment]
This is confirmed fixed with @Drigax's changes applied.

**Comment by Drigax** [comment]
Thanks for confirming!
