### ISSUE TITLE
Graphics holds onto a lot of resources even after the NativeEngine is disposed

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#486]
When I load a big model or something (where memory usage is most noticeable), after the `NativeEngine` is disposed, a lot of memory is still in use. If I do some hackery to manually call bgfx::shutdown, *most* of the resources are released. We should dig into this more and make sure most resources are released when the `NativeEngine` is disposed.

**Comment by CedricGuillemet** [comment]
AFAIK, bgfx::shutdown doesn't destroy resources except clear quad and framebuffers. If you don't have leaks reported by bgfx, then it might be something else.
Do you know the amount of memory still in use? or the type of resources? Any thing reported by bgfx leak check?

**Comment by ryantrem** [comment]
It was a lot (I want to say like 100mb after loading an 80mb model that was mostly vertex data). I don't think I did enough analysis to know what type of resources were released after I forced a call to `bgfx::shutdown`. My hacks to test this out are in this branch: https://github.com/ryantrem/BabylonReactNative/commit/4eadcf7d5854ccd65ebc7356c4435b8257b7b8ad

**Comment by CedricGuillemet** [comment]
Also can you try to call bgfx::frame() after calling dispose on the engine. Maybe the destructions are pushed on the command buffer and would really be destroyed until the frame is happening.

**Comment by ryantrem** [comment]
This has been addressed by https://github.com/BabylonJS/BabylonNative/pull/506 and https://github.com/BabylonJS/BabylonReactNative/pull/120.
