### ISSUE TITLE
bgfx update for vertex layout leak fix

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#494]
fix is in bgfx.
An update is in progress in babylon native.

**Comment by CedricGuillemet** [comment]
1st issue found on Android.
Thanks to this change : https://github.com/bkaradzic/bgfx/commit/9d369ab4a09c7d3523d69e7cf1bcef7c627a51ae#diff-a1a0473b3338942652dfe4319075a1e5ce1f594b3f2b4fdbdfd2a50a3298738a
MSAA is now detected on opengles 3.0 device (that means MSAA was not active before that change) but, on my device and I guess on others, `glRenderbufferStorageMultisample` is unimplemented : 
`com.android.babylonnative.playground E/libEGL: called unimplemented OpenGL ES API`
resulting in incomplete framebuffer and an assert in bgfx.
The extension is properly detected but I didn't find any way to check for valid implementation. The function is said to be present for any opengl es 3.0 compliant device.
I see no other choice than disabling MSAA for Android devices. No performance or visual difference but yet another `#ifdef` in the code.
@bghgary @ryantrem

**Comment by ryantrem** [comment]
Sounds like there is no regression in behavior, so seems ok to me. Maybe worth having another issue to track MSAA on Android though? Maybe there is some solution if we investigate more in the future?

**Comment by CedricGuillemet** [comment]
MSAA + Android issue : https://github.com/BabylonJS/BabylonNative/issues/507

**Comment by CedricGuillemet** [comment]
After more investigation, I've found SPIRV latest version breaks texture/sampler assignment for Metal. Glslang update works fine (so far) but we will have to take extra cares when updating SPIRV.
