### ISSUE TITLE
HoloLens WebXR anchor creation should not fail fast when an anchor can't be created

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#502]
We're starting to see different scenarios where an OpenXR session can get into idle state which results in failed anchor creation. Idle session states are an expected/understood behavior. We should avoid crashing when anchors can't successfully be created, which is the current BabylonNative behavior on HoloLens/mixed reality vr headsets.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
