### ISSUE TITLE
Open XR does not expose tracking state

### ISSUE THREAD

**Issue by CoPrez** [BabylonJS/BabylonNative#505]
BabylonJS has the ability to expose tracking information so the consumer can detect when tracking has started or if tracking is lost during an XR session. The current implementation for BabylonNative does not update the Frame::IsTracking() method when tracking is gained/lost so in BabylonJS it appears that the OpenXR implementation always has tracking.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
