### ISSUE TITLE
[APPLE]Heap corruption when loading Cubemap w/mipmaps

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#510]
with automaticRendering on on mac and validation tests, I got a recurring crash with napi here: https://github.com/BabylonJS/BabylonNative/blob/cb2f58449157f78c56109787d247c67f732e84ed/Plugins/NativeEngine/Source/NativeEngine.cpp#L1162
I recoded the lambda to something like this:
```
                auto* pointer = static_cast<uint8_t*>(typedArray.ArrayBuffer().Data()) + typedArray.ByteOffset();
                std::vector<uint8_t> memory(pointer, pointer + typedArray.ByteLength());
                tasks[(face * numMips) + mip] = arcana::make_task(arcana::threadpool_scheduler, m_cancelSource, [this, memory = std::move(memory)]() {
                    bimg::ImageContainer* image = bimg::imageParse(&m_allocator, memory.data(), memory.size());
                    FlipY(image);
                    return image;
                });
```
And crash disappeared.
I wanted to make a capture of the callstack of the crash for this issue but once my code discarded, I get random crash with heap corruption.
At this point, I don't know if the code is the culprit or moving/replacing code will hide the memory corruption.

I finally managed to get a callstack with the crash in napi:
![image](https://user-images.githubusercontent.com/1312968/99986572-9fe45480-2daf-11eb-994f-e651e77f77cf.png)

**Comment by bghgary** [comment]
One thing I noticed right off the bat is that we fixed the lifetime management issue with LoadTexture regarding holding on the the input buffer, but we didn't fix LoadCubeTexture which has the same issue. I wonder if that's the whole problem?

**Comment by CedricGuillemet** [comment]
@bghgary The code for texture loading (2d, cubemaps, CM+mipmaps) follows the same principle with persistent ref on the array.

**Comment by bghgary** [comment]
@CedricGuillemet Yeah, I thought it didn't, so I deleted my comment.

**Comment by CedricGuillemet** [comment]
Could not repro anymore. Closing.
