### ISSUE TITLE
[APPLE]Metal/bgfx concurrency with renderAutomatically off

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#512]
I'm trying ValidationTests on Mac.
With renderAutomatically on, everything works as expected.
When it's off, I do the rendering in the MTKView delegate, it works fine for some scenes and then it crashes.
The callstacks I get for main and JS threads look like this:
![image](https://user-images.githubusercontent.com/1312968/99984820-d620d480-2dad-11eb-9c96-939a792a4261.png)
Basically, a shader is created on the JS thread while the UI thread responsible for rendering is decoding and uploading a texture. It looks like both threads are accessing Metal resources which leads to a crash.
My guess is to use a rendering encode in the JS thread to not have direct access to graphic API.
What's your thoughts @syntheticmagus ?

**Comment by CedricGuillemet** [comment]
I think this issue can be closed. Do you confirm @bghgary @syntheticmagus @ryantrem  ?

**Comment by bghgary** [comment]
This shouldn't be an issue anymore.

**Comment by CedricGuillemet** [comment]
Closing.
