### ISSUE TITLE
Runtime Diagnostics

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#518]
Follow up to this : https://github.com/BabylonJS/BabylonNative/pull/467#discussion_r529739995
A method has been added to Graphics for bgfx traces. particularly leak output.
This should be part of a global configuration maybe with other infos (performances, load timings, memory footprints,...)

**Comment by bghgary** [comment]
Bucket with other perf issues and maybe split into separate issues.

**Comment by thomlucc** [comment]
related to #911
