### ISSUE TITLE
Make XR begin and end session asynchronous

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#52]
Work will require the XrPlugin to have access to the task chain, so should be undertaken after the work to switch NativeEngine to us runtime global state stored with NAPI so that XrPlugin can take advantage of the same mechanism.

**Comment by ryantrem** [comment]
Begin session was made async as part of https://github.com/BabylonJS/BabylonNative/commit/45a1944f9403ec1f96daf3e11e451ce2eddcb6c6.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to fix this.
