### ISSUE TITLE
Rendering stops working if an XR session starts+stops without getting tracking

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#522]
On both Android and iOS, rendering gets in a bad state if you start then stop XR without XR ever actually getting tracking. This can easily be reproed by just starting XR with the device laying flat on a desk. If you rotate the device 90 degrees (and the view/window is reset), then it starts rendering correctly again. This behavior was introduced with https://github.com/BabylonJS/BabylonNative/commit/23f066b567d5eb7054c984a0726e6bc59fe74d06.

**Comment by Drigax** [comment]
When in the repro state, I can see that we are now drawing the equivalent of multiple frames in a single frame:

![image](https://user-images.githubusercontent.com/3952729/101378707-49bfe880-3868-11eb-8006-5c903187bd1d.png)


Compared with a working frame, we may be drawing hundreds of times:
![image](https://user-images.githubusercontent.com/3952729/101379004-9efbfa00-3868-11eb-962d-9d3f4042d6f9.png)
