### ISSUE TITLE
Thread check assertion when exiting win32 playground

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#529]
I get this error when I quit the app:
![image](https://user-images.githubusercontent.com/1312968/101174250-ed7c7f00-3643-11eb-9919-2a680fbcc035.png)
Any idea what's causing that @syntheticmagus

**Comment by ryantrem** [comment]
Perhaps we should store the jsRuntime and have the destructor dispatch the call to DisableRendering?

**Comment by CedricGuillemet** [comment]
Fixed by https://github.com/BabylonJS/BabylonNative/pull/591 . Closing.

**Comment by bghgary** [comment]
I searched all over for this bug and couldn't find it, lol.
