### ISSUE TITLE
Implement NAPI for JavaScriptCore

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#53]
JSC needs more work:
- [x] handle dispose & destructor callback
- [x] find a way to link externals and c++ object on the JSC side, without another map
- [x] private object on class instead of std::map
- [x] test with gltf loading
- [x] reference counting
- [x] define_class is the Hotpoint for all the method and properties definition.

**Comment by syntheticmagus** [comment]
Added two more stubs in a recent check-in.

- [New object creation](https://github.com/BabylonJS/BabylonNative/blob/master/Library/Dependencies/napi/source/js_native_api_JavaScriptCore.cc#L327-L330)
- [To-object coercion](https://github.com/BabylonJS/BabylonNative/blob/master/Library/Dependencies/napi/source/js_native_api_JavaScriptCore.cc#L802-L807)
