### ISSUE TITLE
Prototype support for stereo-instanced AR Occlusion on HoloLens

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#533]
As developers become increasingly interested in occlusion (https://github.com/BabylonJS/BabylonReactNative/issues/39) with ARKit/ARCore/OpenXR exposing their own possibilities, we should attempt to find a method for occluding virtual content that is both efficient and secure.

The WebXR group has a repo for tracking ideas, and we have an issue posted there that goes over the current state of occlusion support across different vendors and offers a below-the-line approach to occlusion rendering:
https://github.com/immersive-web/occlusion/issues/1

We already have changes in-flight to add mesh detection support (#476), and we currently have the option of adding the detected meshes to the scene with the BJS occlusion material (https://github.com/BabylonJS/Babylon.js/pull/9387), but this doesn't necessarily work from a security perspective with WebXR, as there are still many data privacy concerns around exposing real-world data.

Even if we weren't worried about WebXR compatibility, this is still a good opportunity for us to explore adding stereo instancing support to BabylonNative without needing to do anything on the BJS side. This would be a huge performance win on XR, especially on HoloLens, where framerate will be the first to flag when we begin creating more complex scenes.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
