### ISSUE TITLE
Using a mixture of 16-bit and 32-bit dynamic index buffers causes incorrect rendering

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#536]
Repro:
1. Download [Temp.zip](https://github.com/BabylonJS/BabylonNative/files/5676554/Temp.zip) and unzip.
2. Launch Playground app with the location of the Temp.js file.

Result:
![image](https://user-images.githubusercontent.com/19158740/101849621-eb676400-3b0c-11eb-9425-c1e9f142cbac.png)

Expected:
![image](https://user-images.githubusercontent.com/19158740/101849638-f6ba8f80-3b0c-11eb-8745-ed8a89020de7.png)

See playground: https://playground.babylonjs.com/debug.html#62GK3E#1

**Comment by bghgary** [comment]
This appears to be a bug in bgfx. The index buffers have a flag on them. Bgfx tries to be efficient and it merges the two buffers together, but the flag on the second buffer is lost resulting in bgfx using a 16-bit flag for a 32-bit array.

**Comment by CedricGuillemet** [comment]
@bghgary Assign me this issue if you won't fix it next week. I also have some fix to do in bgfx.

**Comment by bghgary** [comment]
Asked on the forum for suggested fix: https://discord.com/channels/712512073522872352/712512073522872355/786769798993936394

**Comment by CedricGuillemet** [comment]
Repro and issue opened on bgfx repo : https://github.com/bkaradzic/bgfx/issues/2330
