### ISSUE TITLE
Implement WebXRMeshDetector for ARCore/ARKit

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#542]
Right now we have support for WebXRMeshDetector in UWP applications. ARKit currently supports scene geometry/mesh detection with its new lidar sensors. ARCore does not currently support scene geometry/mesh detection. We should add support for both platforms once possible.

For ARKit, this work likely requires the following:
Update Babylon.js object type definitions to support scene objects supported by ARKit here:
https://github.com/BabylonJS/Babylon.js/blob/b69d1f4094b9b8d4d3488e3cabbc25e4a7dd5ddf/src/LibDeclarations/webxr.nativeextensions.d.ts#L5
Update ARKit BabylonNative logic to start reporting scene objects here:
https://github.com/BabylonJS/BabylonNative/blob/e287187c0fa2503f1dde277eaa46534e69ef3a63/Dependencies/xr/Source/ARKit/XR.mm#L1202

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
