### ISSUE TITLE
Support Raw textures in Babylon Native 

### ISSUE THREAD

**Issue by dyleatha** [BabylonJS/BabylonNative#543]
Support raw textures in Babylon Native to enable RGBA buffers to be used as textures on shaders/materials. 

Should currently work in Babylon already, work is to bring support to Babylon Native.

**Comment by CedricGuillemet** [comment]
bjs PR : https://github.com/BabylonJS/Babylon.js/pull/9612
BN PR : https://github.com/BabylonJS/BabylonNative/pull/546
