### ISSUE TITLE
Establish and adhere to CMake platforms pattern

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#55]
We currently have a mixture of patterns for checking platforms throughout our CMakeLists.txt files, mixing variables like WINDOWS_STORE and APPLE in with our usage of BABYLON_NATIVE_PLATFORM. Let's discuss (here in this issue?) what the preferred pattern should be, then propagate pattern everywhere that makes sense and, if there are exceptions where the pattern should be broken, clearly designate these exceptions with comments.

**Comment by CedricGuillemet** [comment]
defined :

ANDROID
APPLE
  IOS
  TVOS
  WATCHOS
WINDOWS
  UWP 

IOS,TVOS,WATCHOS defined by the ios-cmake toolchain
ANDROID, APPLE,WINDOWS defined automatically
UWP is the only one specified by BABYLON_NATIVE_PLATFORM.

**Comment by CedricGuillemet** [comment]
https://github.com/BabylonJS/BabylonNative/pull/80

**Comment by CedricGuillemet** [comment]
PR merged. Can I close it? @syntheticmagus

**Comment by bghgary** [comment]
Yes, this can be closed.
