### ISSUE TITLE
Switch to fullscreen

### ISSUE THREAD

**Issue by crmabs** [BabylonJS/BabylonNative#552]
I'm quite certain it's in front of me, but I wasn't able to work it out: how can I switch to fullscreen mode?
We are talking about a native playground here.

**Comment by bghgary** [comment]
Assuming you mean exclusive fullscreen mode, this isn't directly supported at the moment. It appears [bgfx doesn't support this](https://github.com/bkaradzic/bgfx/issues/695) either.

**Comment by crmabs** [comment]
well, apart from it's too bad, is there a way to have a borderless fullscreen window?

**Comment by bghgary** [comment]
Sure. If you don't need exclusive fullscreen, you can create the window for the targeted platform to be windowless. That isn't technically part of the Babylon Native library and more on the app/UI side.

**Comment by crmabs** [comment]
Is there a documentation somewhere about this? 
 Maybe I shall continue reading bgfx docs?

**Comment by bghgary** [comment]
> Is there a documentation somewhere about this?

What platform are you targeting?

> Maybe I shall continue reading bgfx docs?

Only if you are planning to contribute a fix to Babylon Native or bgfx.

**Comment by crmabs** [comment]
Well, back then I thought there will be a generic "in-babylon-native" call to switch to fullscreen. So I thought I'll cover all the supported platforms. 
 
arm64 is the most important one currently. I'm trying to build stuff that runs on an Nvidia Jetson Nano.

**Comment by crmabs** [comment]
one more, I know it's not the right place, but since we are in a conversation:
void Graphics::Impl::DisableRendering()
     {
-        assert(m_renderThreadAffinity.check());

If I leave this line in the source in Core/Graphics/Source/Graphics.cpp then the app crashes on each exit.

**Comment by bghgary** [comment]
> a generic "in-babylon-native" call to switch to fullscreen

That's why I assumed you mean exclusive fullscreen and even then it only makes sense for desktop. A generic fullscreen feature probably doesn't make much sense for Babylon Native.

> arm64 is the most important one currently. I'm trying to build stuff that runs on an Nvidia Jetson Nano running Ubuntu.

Linux is what I was looking for :-) The CPU architecture doesn't really matter. As for the specifics, I don't know how to do it in Linux, but a search for "x11 make window fullscreen" seems to have some relevant results.

> Core/Graphics/Source/Graphics.cpp then the app crashes on each exit.

Yeah, we know about this one. It's an assert though, not a crash. We will fix it soon. It's rather annoying. ;-)

**Comment by crmabs** [comment]
Many thanks. The picture is clear now.
Many thanks for this awesome product!
