### ISSUE TITLE
Shader compiler traverser doesn't handle conditionals with uniforms for D3D

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#554]
If you have a shader with something like:
```glsl
uniform bool isFoo;
...
vec4 outColor = isFoo ? foo : bar;
// or
vec4 outColor;
if (isFoo)
    outColor = foo;
else
    outColor = bar;
```

This error gets thrown:
https://github.com/BabylonJS/BabylonNative/blob/2227c1ce4f197c585505f555595274b206d51bad/Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp#L70

This is because the traverser hits a parent node of type `TInterimSelection`, which has a condition that contains the uniform that needs to be replaced with a struct member. 

Possible solutions include finding a way to properly replace the symbol in `makeReplacements` (by adding something like `else if (auto* branch = parent->getAsSelectionNode())`), or potentially adding another special case in [`visitSymbol`](https://github.com/BabylonJS/BabylonNative/blob/2227c1ce4f197c585505f555595274b206d51bad/Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp#L112).

**Comment by CedricGuillemet** [comment]
Ping @syntheticmagus and @Drigax

**Comment by Drigax** [comment]
Cool, thanks for the info. Looking into this now, I have a test scene here: https://playground.babylonjs.com/#QPA82A that I'll be using to try to hit these paths in the transpiler.
