### ISSUE TITLE
RenderTargets and order of rendering

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#559]
framebuffers (for shadows, rtt,..) have a viewId superior to the backbuffer viewid.
Thus, drawcalls in FB are performed after drawcalls in backbuffer.
So, for example, the validation test scene 'point light shadows' needs 1 frame for warming up before the shadow map is rendered and usable.

**Comment by bghgary** [comment]
My frame buffer fixes will likely address this problem. Will need to check it out when I'm done.

**Comment by CedricGuillemet** [comment]
@bghgary Tested with latest master. VT scenes like `Point light shadows` #U2F7P9#4 still need at least 2 rendered frames.

**Comment by bghgary** [comment]
I'm assuming this is not true for a browser?

**Comment by CedricGuillemet** [comment]
No because, I guess, drawcalls are performed in-order per frame as bgfx drawcalls are in-order per view target (thanks to SEQUENTIAL flag).

**Comment by bghgary** [comment]
Ok, I don't understand the specifics. Maybe we can chat offline to explore options.
