### ISSUE TITLE
BabylonNative does not provide a mechanism to get access to its frame buffer

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonNative#562]
What's the mechanism for an React Native app to be able to get the frame/(back) buffer for the purposes of streaming out the contents of EngineView in real time?

**Comment by dylanleatham** [comment]
Tech Assist has a need for this feature to support our calling and video recording scenarios. For our asset capture feature, we want to access the video frame buffer (with mixed reality annotations) and combine that with captured audio data to produce a video file of the scenario. In a call, we will be streaming the video buffer through IC3 to other call participants as well as capturing it to produce a video file.

**Comment by bghgary** [comment]
Fixed in #180
