### ISSUE TITLE
model takes a long time to load

### ISSUE THREAD

**Issue by waverider404** [BabylonJS/BabylonNative#567]
repost from 
https://forum.babylonjs.com/t/demo-app-babylonjs-native/17314/20

My glb model takes a while to load. 
This is the link to the model file:

https://cdn.glitch.com/81c23426-9d40-44fa-821a-5284243cd7a7%2Fsubmariner.gltf?v=1579822070355

**Comment by CedricGuillemet** [comment]
I did a quick test on this asset (win32 build). Textures are stored inside this .gltf as base64 encoded. So, no cache issue with many unnecessary requests.
Textures are  1 256x256, 4 1024x1024 and 3 2048x2048.
I guess it's a debug build and mipmaps taking a long time to compute.
@waverider404 did you explicitely set `Release variant` in Android Studio when you built the .apk?

**Comment by waverider404** [comment]
yes I did

**Comment by waverider404** [comment]
I believe it was the device I tested it on, I run the same apk on another device, it loads almost immediately

**Comment by waverider404** [comment]
This is a release build and it should load fast, model is included in file path and not being downloaded from the internet

https://cdn.glitch.com/c9e2f109-17ee-4937-bdaf-b65c3829c52f%2FbabylonJSDemo.apk?v=1610565473391
