### ISSUE TITLE
Freeze while creating AdvancedDynamicTexture

### ISSUE THREAD

**Issue by Armasyll** [BabylonJS/BabylonNative#575]
Applcation Playground freezes while trying to create AdvancedDynamicTexture instance. [https://imgur.com/a/TiFJh1i](https://imgur.com/a/TiFJh1i)

**Comment by bghgary** [comment]
Sorry, this somehow slipped through the cracks. We will look at it ASAP.

**Comment by CedricGuillemet** [comment]
This issue is related to GUI/Canvas and dynamic texture. It will be fixed once the work on Canvas polyfill is done. Closing.
