### ISSUE TITLE
Determine whether UWP HMDs should have autoClear behavior by default

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#577]
Currently we have to manually set autoClear = true for HMDs after entering xr or we get strange rendering behaviors. Mobile devices draw the camera feed into the buffer effectively clearing the previous frame, but HMDs do not. It's not clear whether browsers will autoClear buffers by default/whether BabylonNative should be doing something differently for HMDs.

**Comment by chrisfromwork** [comment]
This seems to be a problem with immersive-ar, it may not be an issue with immersive-vr

**Comment by bghgary** [comment]
As far as I can tell, the code is should be trying to clear to black in NativeXr.cpp, and thus setting autoClear on the scene shouldn't be necessary. I'll have to test this.

**Comment by bghgary** [comment]
That said, autoClear is on by default for a scene, so I don't understand why setting it does anything for HoloLens.
