### ISSUE TITLE
OpenXR generates errors when attempting to enter immersive vr when no headset is plugged in

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#579]
Repro:
1. Run a UWP experience
2. Attempt to launch into xr when no headset is plugged in

Outcome
Failure to launch into xr crashes the application

Expected Outcome:
Failure to launch into xr doesn't crash the application

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this.
