### ISSUE TITLE
[Nightly] Texture bindings and validation tests

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#581]
The crash reported by d3d11 when running UnindexedMesh PG is:
```
D3D11 ERROR: ID3D11DeviceContext::DrawIndexed: The Shader Resource View dimension declared in the shader code (TEXTURE2D) does not match the view type bound to slot 0 of the Pixel Shader unit (TEXTURECUBE).  This mismatch is invalid if the shader actually uses the view (e.g. it is not skipped due to shader code branching). [ EXECUTION ERROR #354: DEVICE_DRAW_VIEW_DIMENSION_MISMATCH]
D3D11: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #354: DEVICE_DRAW_VIEW_DIMENSION_MISMATCH ]
```
The Fresnel PG must be run before UnindexedMesh.
It seems like Fresnel binds some TextureCubes that are not unbound or replaced by new 2D textures. When rendering UnindexedMesh, the shader is expecting a different texture type and crashes.

To repro, you have to use the same Preprocessor as the nightly when building solution: -DBGFX_CONFIG_MEMORY_TRACKING=ON -DBGFX_CONFIG_DEBUG=ON

I tried : 
- discard bindings after bgfx::submit but subsequent drawcalls that share the same state will fail
- bind invalidHandle to each texture slot used by the shader when setProgram is called
- call bgfx::discard when binding a new program

**Comment by CedricGuillemet** [comment]
I've tried to revert some commits and I've found the cause:
If I replace these lines:
```
    NativeEngine.prototype.getHardwareScalingLevel = function () {
        return this._native.getHardwareScalingLevel();
    };
    NativeEngine.prototype.setHardwareScalingLevel = function (level) {
        this._native.setHardwareScalingLevel(level);
    }
```
with previous version:
```
NativeEngine.prototype.getHardwareScalingLevel = function () {
        return 1.0;
    }
```

Then validation test works fine.
I do not understand how this leads to a shader and texture attribution error.

**Comment by Drigax** [comment]
Interesting...I just ran the validation test with the current repo state, but the issue persists. The current babylon.max.js script that the validation test runs agains does NOT have the changes that you reverted @CedricGuillemet.
