### ISSUE TITLE
.babylon loading issue 1

### ISSUE THREAD

**Issue by filippograssi** [BabylonJS/BabylonNative#585]
This .babylon file loads fine on the playground (https://playground.babylonjs.com/#CU2WRV#5) but has issues when I run it on Babylon Native. The model looks like it’s inside out and the bricks are black instead of red.

**Comment by CedricGuillemet** [comment]
I'm taking a look.

**Comment by CedricGuillemet** [comment]
@filippograssi I can repro the back face culling issue but the textures appear with the good colors on my side (Windows d3d11). On which platform did you test this .babylon?

**Comment by filippograssi** [comment]
@CedricGuillemet sorry for the late reply, I tested it both on an Android emulator (via Android Studio on Windows 10) and on a physical device (Galaxy A51)
