### ISSUE TITLE
.babylon loading issue 2

### ISSUE THREAD

**Issue by filippograssi** [BabylonJS/BabylonNative#586]
This .babylon file loads fine on the playground (https://playground.babylonjs.com/#CU2WRV#6) but doesn't load on Babylon Native. I also tried to load the same .babylon file in experience.js and run it, and this error is printed in the console

> I/BabylonNative: Unsupported buffer type createTexture@app:///Scripts/babylon.max.js:39055:36
    Texture@app:///Scripts/babylon.max.js:97413:54
    app:///Scripts/babylon.max.js:97856:42
    Parse@app:///Scripts/babylon.max.js:141938:43
    Parse@app:///Scripts/babylon.max.js:97808:97
    Parse@app:///Scripts/babylon.max.js:141960:80
    Parse@app:///Scripts/babylon.max.js:88329:98
    loadAssetContainer@app:///Scripts/babylon.max.js:64513:93
    load@app:///Scripts/babylon.max.js:65035:47
    app:///Scripts/babylon.max.js:65902:39
    dataCallback@app:///Scripts/babylon.max.js:65524:22
    successCallback@app:///Scripts/babylon.max.js:65544:29
    onReadyStateChange@app:///Scripts/babylon.max.js:143344:38

**Comment by CedricGuillemet** [comment]
Also taking a look.

**Comment by CedricGuillemet** [comment]
Tested OK on my Android device with this PR : https://github.com/BabylonJS/BabylonNative/pull/590
@filippograssi  Can you check now it's been merged into master?

**Comment by filippograssi** [comment]
Hello @CedricGuillemet , as for issue #585 everything is loading perfectly now. This model however (https://playground.babylonjs.com/#CU2WRV#6) I still can't load either on the Emulator and on my Android device.

**Comment by CedricGuillemet** [comment]
I can repro! Trying to fix it now.

**Comment by bghgary** [comment]
This is fixed.
