### ISSUE TITLE
CreateSpheresAsync test renders black (ish) with IBL enabled

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#59]
Spheres rendering differently than expected.

https://github.com/BabylonJS/BabylonNative/blob/master/TestApp/Scripts/experience.js#L12-L26

**Comment by CedricGuillemet** [comment]
I get a bgfx warning : 
BGFX WARNING: Failed to allocate vertex buffer handle (BGFX_CONFIG_MAX_VERTEX_BUFFERS, max: 4096).

Maybe some buffers are not created properly (normals?) and we get a wrong rendering.

**Comment by CedricGuillemet** [comment]
https://www.babylonjs-playground.com/#VBFCHN
default env + standard material = black because no lighting
if you replace the standardMAterial with PBRSpecularGlossinessMaterial, you get a lit box.

**Comment by CedricGuillemet** [comment]
Not a bug. Closing.
