### ISSUE TITLE
NativeInput should accept negative pointer positions

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#596]
Right now NativeInput pointer values are passed around as uint32_t values. This doesn't support negative values when dragging a mouse cursor out of the input region/core window.

**Comment by chrisfromwork** [comment]
When this is fixed, we should also update BabylonReactNative EngineView to submit negative pointer values:

https://github.com/BabylonJS/BabylonReactNative/blob/ddf1b0b38fb5765f09ea8ba613f5152518bfb8f2/Modules/%40babylonjs/react-native/windows/BabylonReactNative/EngineView.cpp#L102

**Comment by PolygonalSun** [comment]
Change is in PR: https://github.com/BabylonJS/BabylonReactNative/pull/362

**Comment by bghgary** [comment]
Okay to close?

**Comment by PolygonalSun** [comment]
PR is merged
