### ISSUE TITLE
Feature Backlog

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#6]
**BROWSER CAPABILITIES**
- [x] Complete implementation of XMLHttpRequest
- [x] Investigate Web workers
- [x] Investigate WebAssembly

**ARCHITECTURE**
- [x] Propose and implement proper InputManager

**NATIVE ENGINE**
- [x] Finalize Babylon Native contract
- [x] Correctly support device loss
- [x] Skyboxes
- [x] Fix stub for URL.createObjectURL in engine
- [x] Fix stub for URL.revokeObjectURL in engine
- [x] Fix stub for Blob in engine
- [x] Investigate BGFX multi-threading
- [x] drawElementsType and drawArrayType should be more robust
- [x] Refactor NativeEngine.ts to share more with other engines
- [x] Implement setViewport
- [x] Fix TODO's in NativeEngine.ts
- [x] Complete implementation of NativeEngine.createTexture
- [x] Implement instancing support
- [x] Implement XHR progress support
- [x] Implement GLB support
- [x] Ensure proper support for Unicode file paths
- [x] Revise `Tools.LoadScript` to not depend on `document`
- [x] Handle backbuffer, depth, and stencil in ViewClearState
- [x] Ensure BindFrameBuffer is setting all the necessary state
- [x] Investigate limiting frame buffer SetUpView to only happen after reset (may not have meaningful perf impact)
- [x] Refactor OpenXR support to minimize/eliminate per-frame allocations

**TEST INFRASTRUCTURE**
- [x] Continuous integration
- [x] Pass all asset generator tests
- [x] Pass all Babylon.js tests
- [x] Create test automation

**DOCUMENTATION**
- [x] Create React Native sample project
- [x] Create Vue sample project
- [x] Create InputManager sample project
- [x] Automate documentation (if API is large enough?)
- [x] Document Babylon Native contract
- [x] Investigate XAML example

**CROSS PLATFORM**
- [x] Support Android
- [x] Support iOS
- [x] Support macOS
- [x] Support XAML by implementing [ISwapChainPanel constructor](https://github.com/BabylonJS/BabylonNative/blob/ab9fd87a212eb574bd3c187f2eb46afaa22c57b5/Library/Include/Babylon/RuntimeUWP.h#L15-L16)
- [x] Ensure proper support for used texture types across platforms

**JAVASCRIPT INFRASTRUCTURE**
- [x] Enable V8 debugging
- [x] Correctly propagate and handle JavaScript errors
- [x] Investigate JSI support

**Comment by foxnoodles** [comment]
Why was this unpinned? It is nice to keep track of the progress. 
I'm waiting for the first fully-featured alpha to start using this in production. 
Prolly will be able to throw in some PRs then.

**Comment by bghgary** [comment]
It isn't terribly accurate right now. We will be more organized once we make a bit more progress.

**Comment by bghgary** [comment]
All of the items in this list now have issues.
