### ISSUE TITLE
scene.createDefaultCamera(true, true, true) does not enable input handling

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#605]
`ArcRotateCamera` (among other parts of Babylon.js that deal with input) are now built on top of `DeviceInputSystem`, so `scene.createDefaultCamera(true, true, true)` *should* work (in terms of handling input) in Babylon Native, but does not for several reasons:
1. `sceneHelper.ts` does this:
```ts
const canvas = this.getEngine().getInputElement();
if (attachCameraControls && canvas) {
    camera.attachControl();
}
```
But `canvas` is `undefined` in the context of Babylon Native.

2. `scene.InputManager.ts` similarly does this:
```ts
if (!elementToAttachTo) {
    elementToAttachTo = scene.getEngine().getInputElement();
}
if (!elementToAttachTo) {
    return;
}
```
Which again exits due to `getInputElement` returning `undefined`.

3. It looks like `isDeviceAvailable` was added to the browser version of `DeviceInputSystem` but not the native version, so that probably also needs to be implemented.

This is as far as I got in my investigation. We should fix the above issues and then check this again. Perhaps `getInputElement` should return the `window` polyfill in Babylon Native, not sure.

**Comment by bghgary** [comment]
@PolygonalSun

**Comment by PolygonalSun** [comment]
The work on the JS side for this is technically done.  The Native side is waiting for this PR: https://github.com/BabylonJS/BabylonNative/pull/953

Since this is part of a bigger issue (https://github.com/babylonjs/babylonnative/issues/742), I'm going to close this.
