### ISSUE TITLE
WebXRFeatureName.IMAGE_TRACKING support

### ISSUE THREAD

**Issue by saidmoya12** [BabylonJS/BabylonNative#619]
Can you allow tracking with a image?

BabylonJs support WebXRFeatureName.IMAGE_TRACKING  but I didn't found this functionality here.

Thanks for your comments!

**Comment by bghgary** [comment]
@RaananW Do you have any thoughts on this? Is this even supported by Babylon.js yet?

**Comment by RaananW** [comment]
Yes, it is. The image tracking feature was added when released by the browsers and work on mobile browsers:

https://github.com/BabylonJS/Babylon.js/pull/9512

https://twitter.com/RaananW/status/1333437510840705024

**Comment by bghgary** [comment]
Thanks. The next question is whether this feature is supported by the platforms we support (OpenXR, ARCore, ARKit). @RaananW How well supported is this feature on WebXR across devices?

**Comment by RaananW** [comment]
Only supported on chrome for android. Its basic image recognizer, i would guess that both arcore and arkit support it naively, at least for marker recognition

**Comment by bghgary** [comment]
Any ideas on OpenXR?

**Comment by RaananW** [comment]
Not supported (yet?), AFAIK. couldn't find any reference online as well.

**Comment by bghgary** [comment]
@saidmoya12 Is the feature still useful for you if it doesn't work everywhere?

**Comment by HedwigAR** [comment]
I came across this issue when trying to find out why image tracking didn't work in Babylon ReactNative. Image recognition is supported in both ARCore and ARKit so I assumed this implementation would work with those as well. Are there any plans to implement image recognition for native android and ios in BabylonNative and BabylonReactNative?

**Comment by bghgary** [comment]
We don't have any plans right now. Would this be useful if it only works for Android and iOS? It doesn't seem like there is support in OpenXR. Also, would you be capable/willing to contribute?

**Comment by HedwigAR** [comment]
Ah, thanks for responding on that. I can't say I'm ready to contribute. I'm currently just exploring the Babylon libraries to see what the capabilities are. In previous project I've found image tracking to be a good starting point for experiences since people can't 'lose' it when it's attached to a physical marker. Or you can start the experience with some extra data based on which marker is scanned.

**Comment by mmehmetAliIzci** [comment]
Hi @bghgary could you give some pointers to look in order to add this capability to the platform ?

**Comment by Alex-MSFT** [comment]
Hi @mmehmetAliIzci - To add image tracking to the platform there are a three main things that would need to be implemented

1. The NAPI implementation of the WebXR interface as described by the proposed webXR spec [here](https://github.com/immersive-web/marker-tracking/blob/main/explainer.md), and implemented in Babylon.js BabylonJS/Babylon.js#9512 this work will primarily be in the "NativeXR" file in BabylonNative, and defines the way in which we transfer data between the native XR session and  the Babylon.js engine.

2/3. The ARCore and ARKit specific implementations of the features to register and update the image tracking state against the underlying native XR sessions, this code will primarily be written against [xr.cpp](https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/xr/Source/ARCore/XR.cpp) and [xr.mm](https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/xr/Source/ARKit/XR.mm) for ARCore and ARKit respectively.  This implementation would utilize the [ARAugmentImage API for ARCore](https://developers.google.com/ar/develop/c/augmented-images/guide), and the [ARReferenceImage API for ARKit]
(https://developer.apple.com/documentation/arkit/content_anchors/detecting_images_in_an_ar_experience).  Also it should be noted that wile the WebXR spec allows for any Bitmap, ARCore currently only supports grayscale images so we would also need to convert the inputted image to grayscale before registering it with the augment image database.

For reference in #335 I implemented Plane detection support for both ARCore and ARKit, which would be similar in overall structure to this change.

**Comment by ThomasNigro** [comment]
Hello,

speaking on behalf of the Minsar team, we will need the Image Tracking capability and are willing to contribute if needed. I believe the proper approach would be to leverage ARCore and ARKit here... We will do some investigations in the coming weeks to evaluate the amount of work that's needed.

**Comment by ThomasNigro** [comment]
We're tentatively roadmapping this work for this summer (probably August/September), we will keep you posted.

**Comment by HedwigAR** [comment]
Hey @tinanigro I was wondering if you have any updates of your try at imagetracking?

**Comment by ryantrem** [comment]
Some work has been done on image tracking. We don't have an ETA for when it will be "done" yet. If anyone wants to contribute, let us know!

**Comment by HedwigAR** [comment]
@ryantrem I'm no native guru, but if there's a list of tasks somewhere, I could check if there's something I can pick up.

**Comment by ryantrem** [comment]
Hey @HedwigAR thank you for the offer! I created the #987 to track part of the work that has not been started. Let me know if you'd be interested in trying to take this on!

**Comment by HedwigAR** [comment]
Hi @ryantrem I feel like it's a bit rude to not answer but I took a look at the list and I very much doubt I could add anything of value. I'll keep checking it to see if something pops up that I can help with.

**Comment by ryantrem** [comment]
Sounds good. Likewise I will update this thread when more progress is made.

**Comment by papadako** [comment]
Hi @RaananW 

I used to have a running image tracking example. Unfortunately, currently, it does not work on android with chrome 99, Babylon 5.0.0-rc11, and the latest AR services. Nothing exceptional in the logs too. 

Are there any changes that I have to consider? Btw http://arimg.glitch.me/ works as expected.

Best

**Comment by RaananW** [comment]
Sorry, just to be sure - @papadako - are you referring to a web-based application or a native application?

**Comment by papadako** [comment]
web-based application

**Comment by papadako** [comment]
It seems to be a problem with rc2 and upwards. At least beta-11 works

**Comment by Alex-MSFT** [comment]
Taking a look now, I suspect the change is probably here:
https://github.com/BabylonJS/Babylon.js/blob/97c5bc5bbcccbeb6834b1ec70a25f67c1226afb4/packages/dev/core/src/XR/features/WebXRImageTracking.ts#L264

This was changed from an await to a synchronous call, which matched the definition in webxr.d.ts, but does not match the explainer here:
https://github.com/immersive-web/marker-tracking/blob/main/explainer.md

So this probably still needs to handle async resolution.

**Comment by Alex-MSFT** [comment]
@papadako - Thanks for bringing this to my attention!
I have a fix pending here PR https://github.com/BabylonJS/Babylon.js/pull/12176

**Comment by papadako** [comment]
Thanks! I will wait for a new rc to test and report back

**Comment by papadako** [comment]
Thanks! 5.0.0 has my issue resolved

**Comment by Alex-MSFT** [comment]
With #1059 and Babylon.JS 5.2.0 WebXR Image Tracking now supported on iOS and Android.

**Comment by ryantrem** [comment]
@tinanigro, @HedwigAR ☝🏻
