### ISSUE TITLE
XR mode does not work on Oculus

### ISSUE THREAD

**Issue by bdbelevate** [BabylonJS/BabylonNative#626]
Currently, XR mode does not work on Oculus. It appears that the XR code is expecting Google's ARCore if it's an android device (which Oculus is). 

https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/xr/CMakeLists.txt

```
if (ANDROID)
    set(SOURCES ${SOURCES}
        "Source/ARCore/XR.cpp") # does not exist for Oculus
elseif (IOS)
    set(SOURCES ${SOURCES}
        "Source/ARKit/XR.mm")
else()
    ...
    if(WIN32)
        set(SOURCES ${SOURCES} "Source/OpenXR/Windows/XrPlatform.h")
    else()
        message(FATAL_ERROR "OpenXR support not available for platform ${CMAKE_SYSTEM_NAME}")
    endif()
    ...
endif()
```

It looks like OpenXR needs to be implemented for more than just the Windows platform. I will take a look and see if I can figure out how to make that work, but much of the code in `Source/OpenXR` is Windows specific. Most likely the Dependency on `OpenXR-SDK` will need to be `OpenXR-SDK-Source` as well.

**Comment by bghgary** [comment]
Related: https://github.com/BabylonJS/BabylonNative/issues/231

We haven't tested on Occulus yet.

**Comment by yuripourre** [comment]
Bump!

**Comment by bghgary** [comment]
Closing for now. Reopen if the community wants to contribute.

**Comment by bghgary** [comment]
Also closing in favor of #231.
