### ISSUE TITLE
Rendering inconsistently draws to both eyes for HoloLens 2 in immersive xr mode

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#637]
It isn't a consistent repro, but we are seeing rendering behaviors where the left eye draws consistently but the right eye flashes on HoloLens 2 devices when running in BabylonReactNative. It is prone to happening when a debugger is attached.

**Comment by bghgary** [comment]
I think the first thing to check is whether my [big PR](https://github.com/BabylonJS/BabylonNative/pull/591) caused this issue. If it does, then maybe it's related to the clear changes or the render target texture changes.

See [this](https://github.com/BabylonJS/Babylon.js/pull/9943) for the clear changes on the Babylon.js side
See [this](https://github.com/BabylonJS/BabylonNative/pull/591/files?file-filters%5B%5D=.cpp#diff-6a85469b65c210d4a4927721cacfd211d2f31f27ec0729e20693d7e90242f437R316-R317) and follow the code for creating / destroying the render target textures and [this](https://github.com/BabylonJS/BabylonNative/pull/591/files?file-filters%5B%5D=.cpp#diff-6a85469b65c210d4a4927721cacfd211d2f31f27ec0729e20693d7e90242f437R320) for getting the render target textures every frame.

**Comment by rgerd** [comment]
Pretty sure the texture arrays fix has fixed this
