### ISSUE TITLE
Android AR rendering broken on some devices

### ISSUE THREAD

**Issue by davidebaltieri31** [BabylonJS/BabylonNative#647]
Hi, 
I've recently update my local copy with the latest version, something has broken rendering on some Android devices (most notably Samsung phones, I've tried the S8 and a S10 Plus) with AR enabled:
the camera is rendered but 3d objects aren't. Or rather sometimes they flicker in existence for milliseconds, like the android view on which the 3d part is rendered appear for a single frame and then disappear, at random.

I've just grabbed a new clone of the current repo and built the demo app enabling AR and the bug appear.

I've also tested a Xiaomi Mi9 and a Samsung Galaxy Tablet S6 and rendering works fine there.

**Comment by ryantrem** [comment]
@davidebaltieri31 can you capture and share a video showing the behavior?

**Comment by davidebaltieri31** [comment]
Video: https://youtu.be/EIrrqVLRPDs

**Comment by ryantrem** [comment]
Thank you, we’re investigating!

**Comment by davidebaltieri31** [comment]
It happens both on Debug and Release. That video specifically is in Debug.
I've tested another device (Huawei P30) and I get the same problem there.

I'll try reverting back commit by commit this afternoon.

**Comment by davidebaltieri31** [comment]
Hi, after some testing it seems the problem start with commit 720b2dc2da8393aad4893a1661dd71bef1aa6fdc

**Comment by ryantrem** [comment]
@davidebaltieri31 it would be great if you could verify this fixes the issue for you!

**Comment by davidebaltieri31** [comment]
Hi, I can confirm it works correcly now on all the devices I've tested. 
Thanks.
