### ISSUE TITLE
Correctly handle DPI changes

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#65]
https://github.com/BabylonJS/BabylonNative/blob/master/TestApp/Source/UWP/App.cpp#L240L243

DPI changes should likely be handled inside the platform-specific Runtime extensions (RuntimeWin32, RuntimeUWP, etc.) and only get communicated down to lower layers as resolution changes.

**Comment by CedricGuillemet** [comment]
Fix in this PR https://github.com/BabylonJS/BabylonNative/pull/116
also duplicate with issue https://github.com/BabylonJS/BabylonNative/issues/103
Closing.

**Comment by bghgary** [comment]
PR #116 fixes this issue for UWP. Need to ensure it works on all platforms.

**Comment by bghgary** [comment]
We should also consider moving the logic of this inside the Runtime class after determining how to do it for all the platforms.

**Comment by CedricGuillemet** [comment]
@Drigax I assigned you this taks as I think it can be closed once your work on DPI is done.

**Comment by Drigax** [comment]
Currently Babylon.js is not responsive to DPI changes, outside of DOM driven canvas resizing. 
If we want to support this in Native, we should figure out what is proper behavior for the JS engine as well.

**Comment by bghgary** [comment]
The current way is that apps must explicitly call UpdateSize and/or SetHardwareScalingLevel to deal with size and DPI changes.
