### ISSUE TITLE
CreateGraphics from native context

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#657]
Until now, we can create a new `Graphics` from a platform window (HWND, UIView,...)
For some use cases (one OpenGL context that is bound to various Surface on Android for example) it lacks the ability to create a `Graphics` instance from a Platform context.

Some parts of the code like `UpdateDevicePixelRatio`

https://github.com/BabylonJS/BabylonNative/blob/8371b79805f2647dc7c43aa1f3e0a5552f23e2f6/Core/Graphics/Source/Win32/GraphicsPlatform.cpp#L20

need a NativeWindow. How can it work with a context only?

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/674

**Comment by bghgary** [comment]
PR is merged and fixed in Babylon React Native.
