### ISSUE TITLE
Empty Project

### ISSUE THREAD

**Issue by Schr3da** [BabylonJS/BabylonNative#658]
Hi, 

I would have a quick question regarding project creation. Is there a simple way to just setup a new project? 

Any Feedback would be appreciated.

Thank you 

Happy Easter

Schr3da

**Comment by bghgary** [comment]
Our story here for pure Babylon Native is a bit weak right now. The playground app is the closest to an empty project, but it may not be what you are looking for. Adding good samples is something we need to do in the future.

If you are using React Native, there are prebuilt npm packages you can use to bring it into a React Native project.

**Comment by Schr3da** [comment]
Thanks for the quick reply - made it work in react native - just was thinking about an alternative way - I might start video blog based on a game Im currently developing so Im currently evaluating potential engine I want to use. I looked already in the popular one e.g. Unity, Unreal but I want to treat web as first class without all the overhead :D So babylon seems to be a good alternative.

**Comment by Schr3da** [comment]
just added a quick tweet about how to set it up  :D https://twitter.com/schreda
