### ISSUE TITLE
[CI] Configure CMake version used

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#666]
By default, the latest version of CMake is used to build on the CI.
This can lead to unexpected issues : https://github.com/BabylonJS/BabylonNative/issues/654
We should provide in the `azure-pipelines.yml` file the CMake version that is guaranted to work with BabylonNative.
Also, once set up, update `readme.md` to reflect the chosen version.

**Comment by ryantrem** [comment]
It looks like we can also declare a *max* CMake version: https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html

**Comment by bghgary** [comment]
Mac machine building Android are failing now. We need to fix this ASAP.

https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=12130&view=logs&jobId=d66521f2-2604-5247-d473-9047b94cc802&j=d66521f2-2604-5247-d473-9047b94cc802&t=65b047d1-a3de-5bb4-653c-7436a51bf6eb

**Comment by bghgary** [comment]
This is what @ryantrem did for BabylonReactNative which uses GitHub actions. https://github.com/BabylonJS/BabylonReactNative/pull/193

We don't use GitHub actions, so I'm not sure if this will work for us.

**Comment by CedricGuillemet** [comment]
CMake version for Linux & Mac agents : https://github.com/BabylonJS/BabylonNative/pull/673

**Comment by CedricGuillemet** [comment]
@ryantrem Android build with CMake policy max version set to 3.19.8 and installed CMake 3.20.1 leads to the same null pointer exception. No error/warning on the currently used version.
