### ISSUE TITLE
UWP xr session context should have its lifecycle managed by the xr system compared to a static object

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#672]
we should add additional checks to not create the underlying xr system if xr isn't supported

**Comment by syntheticmagus** [comment]
We should try to get this to fall back into Babylon.js's default behaviors for browsers that don't support WebXR, since that should handle the situation gracefully from the JavaScript side in a way that will match the Web.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
