### ISSUE TITLE
Setup a UWP validation test and run through napi-jsi validation scenarios

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#678]
We should setup uwp tests to run through initialization and basic xr scenarios. At the same time we could benefit from having test coverage of napi jsi

**Comment by CedricGuillemet** [comment]
@chrisfromwork When building and running UWP Playground, I get this error : 
`Uncaught Error: 'chromeDevTools' is not defined`
Any idea on how to fix this issue?

**Comment by bghgary** [comment]
This is because we added `chromeDevTools` to the playground. We should check if `chromeDevTools` exists first before using it.

Personally, I don't think this should be a JS contract. See https://github.com/BabylonJS/BabylonNative/issues/689.

**Comment by chrisfromwork** [comment]
@bghgary is there a suggested fix for the playground? are we missing a line in experience.js? @CedricGuillemet are you unblocked?

**Comment by bghgary** [comment]
The fix is simple. Change this:

https://github.com/BabylonJS/BabylonNative/blob/master/Apps/Playground/Scripts/experience.js#L56-L58

To something like this:

```javascript
if (typeof chromeDevTools !== "undefined" && chromeDevTools.supportsInspector()) {
    chromeDevTools.startInspector(5643, "experience.js");
}
```

**Comment by rgerd** [comment]
Once we get #854 closed we can close this one out too.
