### ISSUE TITLE
Small bug on iOS regarding screen resolutions

### ISSUE THREAD

**Issue by davidebaltieri31** [BabylonJS/BabylonNative#681]
I've come across a small bug on iOS that presents itself when using AR on an iPhone 7 Plus (but should happen also on iPhones 6 Plus, 6s Plus and 8 Plus).
In those phones the native resolution and UIKit sizes (multiplied by the UIKit scale factor) differs.
I noticed it because 
1) I wasn't able to correctly match touch position on screen with the rendered scene in AR
2) The ground plane pointer I was drawing was not centered on the 7 Plus (raycasting from the screen center in experience.js) hinting that somehow the rendered viewport was bigger than the actual screen.

![IMG_20210412_160635](https://user-images.githubusercontent.com/5039687/114422400-89039a80-9bb6-11eb-9ad7-14e818857c6f.jpg)

On the phones I've listed the native scale factor is not equal to the UIKit one (see https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html)

A first solution I've found was to change XR.mm lines 641, 642
from
```
viewportSize.x = xrView.bounds.size.width * scale;
viewportSize.y = xrView.bounds.size.height * scale;
```
to
```
viewportSize.x = UIScreen.mainScreen.nativeBounds.size.width;
viewportSize.y = UIScreen.mainScreen.nativeBounds.size.height;
```

and scaling accordingly the touch points in ViewController.swift with the native scale.

It seems to solve most problems but I'm not sure if this change is enough. Are there other places in BabylonNative's code where it access the UIKit resolution instead of the native screen one?

**Comment by bghgary** [comment]
@CedricGuillemet or @Drigax any ideas?

**Comment by Drigax** [comment]
Interesting, @davidebaltieri31 do you have a minimum experience.js you can share to reproduce how you're creating your pointer?

I'm assuming that you're not using https://doc.babylonjs.com/typedoc/interfaces/babylon.nativeengineoptions#adapttodeviceratio,. right?

**Comment by Drigax** [comment]
Hey @davidebaltieri31, can you share a sample scene that I can take a look at? I'm not sure how you're initializing your scene.

**Comment by davidebaltieri31** [comment]
Sorry for the late answer,
I don't do anything much different from the demo application. Enabling ar and xrHitTest in the demo experience.js in this repo should reproduce what I see. I just use a textured plane instead of the basic box.

Initialization on iOS side (ViewController and LibNativeBridge) is similar to what is done in the demo app. I do have some changes there to solve other bugs I've found with the deallocation of the ViewController but shouldn't interfere with the first initialization.

**Comment by ryantrem** [comment]
@davidebaltieri31 in that bit of code you pasted above, but including the previous line, it is like this today:
```
auto scale = UIScreen.mainScreen.scale;
viewportSize.x = xrView.bounds.size.width * scale;
viewportSize.y = xrView.bounds.size.height * scale;
```

Can you try just changing it to:
```
auto scale = UIScreen.mainScreen.nativeScale;
viewportSize.x = xrView.bounds.size.width * scale;
viewportSize.y = xrView.bounds.size.height * scale;
```

**Comment by bghgary** [comment]
Just tested @ryantrem's fix on an iPhone 7 Plus and it works perfect. @ryantrem Can you verify that your suggested change works on other devices?
