### ISSUE TITLE
CMake 3.19 has been delisted from homebrew; Mac CI broken

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/BabylonNative#683]
It appears that homebrew has delisted 3.19, right in time to break our builds that depend on this version.

http://homebrew.bintray.com/bottles/cmake-3.19.6.mojave.bottle.tar.gz
now returns 403 - Forbidden when accessed.

**Comment by CedricGuillemet** [comment]
Fixed by https://github.com/BabylonJS/BabylonNative/pull/680 Closing.
