### ISSUE TITLE
Flutter support ?

### ISSUE THREAD

**Issue by gedw99** [BabylonJS/BabylonNative#691]
Would be awesome .

you basically have it close to supported already from what I can see in the App folder.
just a matter of exposing it via a flutter.

Flutter can load native on mobile and desktop easily and push FBO to the Flutter Tectute widget. Same widget that is used to play video.

Flutter gestures then send events back to native layer.

**Comment by bghgary** [comment]
I don't think anyone here knows flutter. We do try to make the code flexible enough to support any UI framework. Contributions would be welcome!

**Comment by Simbaclaws** [comment]
I would like to create a flutter FFI package that calls into native babylon API's...

However, flutter makes use of dart, not javascript.

It seems that babylon native has a lot of native code, and only a small part of it is javascript (probably translation layer).

I just need to translate the javascript side into dart and use that for the flutter package...

Can I perhaps get in contact with some of the people behind babylon to co-ordinate on this effort?

I don't expect you to know flutter or dart, but I would like to learn more about how babylon native itself works and how I can try to implement it.

There are other babylonjs implementations in flutter out there so I'm not the first in giving it a shot, but they're not truly native and are using non platform specific code, and I would like to create a single package that can be used cross platform natively.

Please let me know if the babylon team would be interested in such effort.

**Comment by bghgary** [comment]
> flutter makes use of dart, not javascript.
> 
> It seems that babylon native has a lot of native code, and only a small part of it is javascript (probably translation layer).
> 
> I just need to translate the javascript side into dart and use that for the flutter package...

I'm not exactly sure what you mean by this, but I think you are saying you want to project the Babylon.js API into dart. Babylon Native is intended to bring in JavaScript as Babylon.js (the main API) is all in JavaScript. The [Babylon.js API surface](https://doc.babylonjs.com/typedoc/modules/BABYLON) is not small. I doubt it would be practical to use Babylon.js from dart.

I would expect any integration with a UI framework to continue to use JavaScript for Babylon.js or it will get quite complicated.

**Comment by bghgary** [comment]
> I really want to setup native 3d rendering in flutter

Babylon Native can, in theory, integrate with Flutter as long as you use JavaScript as the language to interact with the Babylon.js API. The goal of Babylon Native is to be able to use the same rendering code used on the web in a native environment. This means that the code is written in JavaScript and may mean the integration requires bringing in a JavaScript runtime.

**Comment by gedw99** [comment]
https://pub.dev/packages/flutter_js

**Comment by ioridev** [comment]
https://github.com/CedricGuillemet/babylonnative_flutter

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this.
