### ISSUE TITLE
[Linux CI] Validation tests without UI

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#695]
There is a growing number of users asking for headless rendering on server on Linux. With this PR : https://github.com/BabylonJS/BabylonNative/pull/674
It becomes possible to create the engine without a window. A good test is to modify the Linux Validation tests to run with or without a window.
The unkown to clarify is how the backbuffer behaves, do we have to create a render target, how is the rendering loop working, does bgfx work without a swapchain and constently rendering ? ...

**Comment by bghgary** [comment]
xvfb can work for now. Will see if this is necessary in the future.

**Comment by bghgary** [comment]
Part of regression testing.

**Comment by bghgary** [comment]
This is working now.
