### ISSUE TITLE
BabylonNative should add initialization logic to correctly propagate the application name to the openxr runtime

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#709]
Right now we declare an application name of "Open XR Sample" for all xr components:
https://github.com/BabylonJS/BabylonNative/blob/e6ab99276c4bfcb632cedd9ef1905c3448fc8699/Dependencies/xr/Include/XR.h#L350

it feels like this value should be updated to use the actual application name or at least fixed for non openxr platforms.

Note, if we do update the application name, we should also make our application copy name more robust. right now we are not checking that the application name is longer than the allowed application name buffer:
https://github.com/BabylonJS/BabylonNative/blob/e6ab99276c4bfcb632cedd9ef1905c3448fc8699/Dependencies/xr/Source/OpenXR/XR.cpp#L219

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
