### ISSUE TITLE
BabylonNative windows playgrounds should be WACK compliant

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#723]
We have been looking at wack compliance for babylonnative and babylonreactnative, it seems like two things are currently blocking babylonnative wack compliance:

1. We have some restricted capabilities declared that don't seem needed: https://github.com/BabylonJS/BabylonNative/blob/9787408792d1488b8639a3d4f8cb4deeb40aa73d/Apps/Playground/UWP/Package.appxmanifest#L37
2. We have not updated the default windows store logos to be true babylon.js assets.

**Comment by bghgary** [comment]
> `broadFileSystemAccess`

This is because the playground can load arbitrary JS files that can load arbitrary assets on disk.

> default windows store logos

Since this is intended to be a sample test app, I don't think we need to do this. If some day this app becomes a bit more than this, then we should update the assets.

**Comment by tymlipari** [comment]
As an FYI, `broadFileSystemAccess` doesn't work on HoloLens SKUs, but so far it seems to not block the installation of a package with that capability and there aren't practical ways to use the kind of scenario referred to so I think this is okay.
