### ISSUE TITLE
Support Signed Byte and Unsigned Short Vertex Buffer Formats

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#729]
In BGFX:
- [x] Add the Int8 and Uint16 to the AttribType enum in bgfx.h
- [x] Add capabilities for BGFX_CAPS_VERTEX_ATTRIB_INT8 and BGFX_CAPS_VERTEX_ATTRIB_UINT16
- [x] Add the fulfilling format in the respective renderer_d3d11, d3d12, gl, mtl, and noop
 
In Babylon.js:
- [x] Add ATTRIB_TYPE_INT8 and ATTRIB_TYPE_UINT16 as readonly values in NativeEngine.
- [x] Fix up the switch case to route them correctly to native engine
 
In BabylonNative:
- [x] Define ATTRIB_TYPE_INT8 and ATTRIBT_TYPE_UINT16 to map to the enum values from bgfx.h

**Comment by bghgary** [comment]
All done!
