### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#73]
500Mb allocated while loading Sponza. It looks like a lambda capture. Any idea @bghgary ?
![image](https://user-images.githubusercontent.com/1312968/67374071-f665da80-f580-11e9-9f77-cebce76182be.png)

**Comment by bghgary** [comment]
My guess is this is loading textures. The lambda is because all of our code runs using arcana's dispatcher/task system. We need to drill down further to know what it is.

**Comment by CedricGuillemet** [comment]
@syntheticmagus Is there a reason we keep decompressed texture data in RAM allocated here ?https://github.com/BabylonJS/BabylonNative/blob/master/Library/Source/NativeEngine.cpp#L978

**Comment by bghgary** [comment]
I'm pretty sure this doesn't happen anymore. Please reopen if you still see this.
