### ISSUE TITLE
Autofocus of camera in AR

### ISSUE THREAD

**Issue by HedwigAR** [BabylonJS/BabylonNative#731]
I started this question on the Babylon Forum (https://forum.babylonjs.com/t/babylonreactnative-how-to-get-ar-camera-to-focus/20588)

**Is your feature request related to a problem? Please describe.**
Currently, on Android autofocus is automatically disabled (https://developers.google.com/ar/reference/java/com/google/ar/core/Config.FocusMode). This makes it so that looking at small objects close-by, the background is blurry and this takes away from the experience. I find myself waiting for it to focus. 

**Describe the solution you'd like**
It would be great if there was the option to enable autofocus in the camera in Babylon. So you could set it when creating the camera. 
If this is not possible, having it consistent with ARKit which (for iOS 11.3 and later) has this enabled by default (https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2942262-isautofocusenabled) would also save some confusion.

**Additional context**
I couldn't find any guidance on this in the OpenXR specification, neither did I find anything in the WebXR specification. This issue does come up with WebXR, but there's not been an answer to it (https://github.com/immersive-web/webxr/issues/1154). 
Usecases that would benefit from having autofocus are all usecases that need to have people viewing things close-by. For example, an ad with 3D objects on top of a magazine, viewing a smaller AR interactive model of industrial machinery on top of a table or any architectural scale model.

**Comment by HedwigAR** [comment]
C++ isn't something I have experience with. But I did find what the config in ARCore should look like, to give an idea.
```
            ArConfig *config;
            ArConfig_create(session, &config);
            ArConfig_setFocusMode(session, config, AR_FOCUS_MODE_AUTO);
            ArSession_configure(session, config);
```

Inserted at line 450 of Dependencies/xr/Source.ARCore.XR.cpp in the Initialize() function makes it autofocus. The config should then probably be destroyed when the session is.

**Comment by ryantrem** [comment]
This has been fixed (for now hard coded to have auto focus on - in the future we might plumb through an API so JS can control this).
