### ISSUE TITLE
GLBs packed via GLTFPack do not display correctly on Windows

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#738]
After packing a GLB with [GLTFPack](https://github.com/Alex-MSFT/meshoptimizer) with default settings the GLB does not display correctly in Windows, but does on Android, and Mac OSX, I have tested this with several GLBs and all display the same behavior.  The file appears to load successfully, and you can see vertex buffers being allocated and loaded, but no content is display in the playground.

Repro branch with an example Playground: https://github.com/Alex-MSFT/BabylonNative/tree/gltfpack_repro

**Comment by CedricGuillemet** [comment]
I could repro the issue with bgfx. I've open an issue : https://github.com/bkaradzic/bgfx/issues/2514
