### ISSUE TITLE
XR's `CreateAsync` on Android returns before XR window is visible

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#740]
**Describe the bug**
Creating an XR session in Babylon Native involves calling XR's `CreateAsync` method, which is supposed to return when it's time to start rendering to XR. At the moment, however, this method returns before the XR window is visible (in fact, I believe the sequence of events is such that `CreateAsync` returning *causes* the XR window to appear). This leads to visible artifacts as several frames are rendered to a window which is not visible while a different window is still visible. For more details, please review the original writeup of this observation in #649.

**To Reproduce**
1. Modify the Babylon Native Playground's experience.js to load an animated model (to make it easier to see errant behavior).
2. Enable AR in experience.js.
3. Launch the Playground and wait for AR to start, watching the loaded model closely.
4. For a few frames before the XR window becomes visible, you should see the rendered model "cycle" strangely as `eglSwapBuffers` is called without any instructions (including clear) having been sent to the backbuffer.

**Expected behavior**
The "cycling" behavior is caused by Babylon Native attempting to render to the XR frame without submitting any instructions to the backbuffer because it believes the backbuffer should be invisible after `CreateAsync` returns. Consequently, `CreateAsync` should not return until the window to which it should render actually appears, which will validate Babylon's assumptions.

**Other**
 - Platform: Android

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
