### ISSUE TITLE
cmake doesn't generate build solution on windows 10

### ISSUE THREAD

**Issue by waverider404** [BabylonJS/BabylonNative#747]
Cmake doesn't generate build solution after installing the new master branch on windows 10

![powershell_XV5op7YRbv](https://user-images.githubusercontent.com/34609417/118357678-64019f00-b549-11eb-8e9f-cffce4a8943d.png)

**Comment by waverider404** [comment]
[CMakeOutput.log](https://github.com/BabylonJS/BabylonNative/files/6486023/CMakeOutput.log)
[CMakeError.log](https://github.com/BabylonJS/BabylonNative/files/6486024/CMakeError.log)

**Comment by rgerd** [comment]
@waverider404 I have a fix out that I believe will resolve your issue. Just to be sure, since I couldn't get a local repro, could you also tell me:
1. The specific CMake command you ran to get this result
2. The output of `cmake -version`

**Comment by rgerd** [comment]
Reopening until we determine the issue has actually been resolved and we can figure out why the error was thrown in @waverider404's configuration

**Comment by waverider404** [comment]
It is working fine now, i used c

> @waverider404 I have a fix out that I believe will resolve your issue. Just to be sure, since I couldn't get a local repro, could you also tell me:
> 
> 1. The specific CMake command you ran to get this result
> 2. The output of `cmake -version`

It is working fine now
I used cmake -A Win32 .. 
and I am running cmake version 3.18.3

**Comment by rgerd** [comment]
@waverider404 
Great! I was able to get a repro, looks like it was the older CMake version (on top of the erroneous line). Good to know.
And thanks for the android build tip, we'll look into it. 

If you feel like downgrading your CMake version, reproducing the Android build bug, and filing a similar issue, it would be very helpful for us. 

Thanks!
