### ISSUE TITLE
iOS MtkView resize

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [BabylonJS/BabylonNative#753]
Hi there,

On iOS, I tried to resize (enter/exit fullscreen) the MTKView based on enable/disable constraints of the root window anchors.

```
    UIViewController *topController = [[[[UIApplication sharedApplication]delegate] window] rootViewController];
    self.fullScreenLayout = @[
        [inView.leadingAnchor constraintEqualToAnchor:topController.view.leadingAnchor],
        [inView.trailingAnchor constraintEqualToAnchor:topController.view.trailingAnchor],
        [inView.topAnchor constraintEqualToAnchor:topController.view.topAnchor],
        [inView.bottomAnchor constraintEqualToAnchor:topController.view.bottomAnchor]
    ];
```

```
    if (value == true) {
        [NSLayoutConstraint activateConstraints:self.fullScreenLayout];
    }
    else {
        [NSLayoutConstraint deactivateConstraints:self.fullScreenLayout];
    }
    [UIView animateWithDuration:0.5 animations:^{ [self->xrView.superview layoutIfNeeded]; } ];
```

Its failed on:
![Screenshot 2021-05-20 at 12 20 48](https://user-images.githubusercontent.com/63807677/118962672-e9c88480-b965-11eb-82a1-0185f83a0ea0.png)

Is there a way to pause the rendering or update the size view ?

Thanks in advance,
Best regards,
Eric

**Comment by bghgary** [comment]
> Is there a way to pause the rendering or update the size view ?

Pausing the rendering should be as simple as not calling the rendering functions (Graphics::StartRenderingCurrentFrame and Graphics::StopRenderingCurrentFrame).

There is an Graphics::UpdateSize function also.

**Comment by bghgary** [comment]
@EricBeetsOfficial-Opuscope Did this work for you? Do you need more help with this?

**Comment by EricBeetsOfficial-Opuscope** [comment]
Hi @bghgary,

Actually, it works (but not in the way I want..):
I set `mtkView.autoResizeDrawable = false;`, it allows to enter/exit fullscreen mode (based on anchors), but it changes the viewport resolution.
I would like to have a non-fullscreen with a "fullscreen resolution" viewport...
I still work on it ;)

**Comment by bghgary** [comment]
Ok, do you want to keep this issue open or can we close it?

**Comment by EricBeetsOfficial-Opuscope** [comment]
Not sure: if the normal behavior is to adapt the resolution of the viewport to the view, we can close :)
If we can choose the viewport resolution independently of the view resolution, it still an issue: \

**Comment by EricBeetsOfficial-Opuscope** [comment]
Actually, it's about the ratio of the viewport vs ratio of the UIView. So, indeed, we can close this issue
