### ISSUE TITLE
XR rendering is broken on platforms that don't update NativeXR window pointer

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#755]
**Describe the bug**
No rendering happens on platforms that don't call [`NativeXR::UpdateWindow`](https://github.com/BabylonJS/BabylonNative/blob/master/Plugins/NativeXr/Source/NativeXr.cpp#L442) due to a [change](https://github.com/BabylonJS/BabylonNative/commit/e2e409d6038c3d5e9f3c286c88f1741432230f84) that blocks eye texture creation if no window pointer is set. The only platform that calls `NativeXR::UpdateWindow` seems to be Android in [**BabylonNativeJNI.cpp**](https://github.com/BabylonJS/BabylonNative/blob/master/Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp#L239). 

On UWP/arm64, rendering is silently black, but on Win32/x64, there's a crash due to `m_sessionState->ActiveTextures` having size 0.

**To Reproduce**
Run a clean Win32 Playground with `vr = true` in **experience.js**.

**Comment by bghgary** [comment]
Change reverted.
