### ISSUE TITLE
Need a way to cache shader IL to avoid compilation slowdowns at runtime

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#777]
**Is your feature request related to a problem? Please describe.**
Currently, when we load in new shaders from Babylon.js, we have stuttered performance with the shader getting parsed and compiled at runtime.

**Describe the solution you'd like**
It would be nice to find a way for us to be able to package pre-compiled intermediate language binaries with our applications so we don't need to recompile at runtime when we already know what our target platform will be.

**Comment by bghgary** [comment]
Dupe of #1407
