### ISSUE TITLE
Framerate stutters when recompiling shaders

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#779]
**Describe the bug**
We're seeing framerate stutter on HoloLens when recompiling a shader that hasn't changed at all (same defines etc).

**To Reproduce**
An illustrative playground: https://www.babylonjs-playground.com/#ZWWEP8#1
Note that the performance in-browser is totally smooth while there is stuttering when running on BabylonNative, even on desktop. The stuttering is significantly pronounced on HoloLens.

**Expected behavior**
Some caching mechanism (at build or runtime) on the shader code would short-circuit the native-side compilation pipeline and simply provide pre-compiled bytecode.
For example, Chromium [implements a cache for shaders](https://source.chromium.org/chromium/chromium/src/+/master:gpu/ipc/host/shader_disk_cache.h).

**Comment by bghgary** [comment]
Related: #402

**Comment by bghgary** [comment]
Consider implementing a shader cache that persists across sessions.

**Comment by bghgary** [comment]
This is fixed by async shader compilation work.
