### ISSUE TITLE
`Graphics::Context` concept for advanced rendering scenarios

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#790]
In conversations surrounding #739, several advanced scenarios came up which revealed deficiencies in the abstractions currently available in the Graphics component. These deficiencies center around problems that arise during multi-render scenarios.

The "canonical" Babylon Native application is columnar in that, at any given time, it only has one instance of each of its major concepts.
 - One `Graphics` object.
 - One JavaScript thread/runtime/`Napi::Env`.
 - One `NativeEngine`.

In this simple case, the current abstractions are sufficient. However, for more complex scenarios, new abstractions will be needed to safely and usably expose rendering capabilities. In particular, not every app is guaranteed to have only one JavaScript thread/runtime/`Napi::Env`; many such instances can exist, and it must be possible for them to all independently and simultaneously run and render to their own (potentially even more numerous) `NativeEngine`s. Under these circumstances, some of the behavior currently encapsulated in the `FrameBufferManager` becomes problematic. A key responsibility of the `FrameBufferManager` is to manage the relationships between bgfx's `View` concept and Babylon's `FrameBuffer`s so that everything gets drawn to the correct targets in the correct order. If this is done improperly, bgfx will reorder rendering commands so that they can be batched by `View`, which can cause commands to execute out of the intended order and produce incorrect results. For example, consider a simple scene that renders a single object which casts a shadow using shadowmapping. The high-level Babylon commands when rendering this scene might be as follows:
1. Clear the main render target.
2. Clear the shadowmap render target.
3. Render the object from the light's perspective to the shadowmap render target.
4. Render the object from the camera's perspective to the main render target, using the shadowmap to render shadow.

With only two bgfx `View`s (one per render target), it is not possible to execute these commands in the specified order. (In this case, no visible artifact would result from doing step 1 after step 3, which _would_ allow this to be done with only two `View`s; however, this is not the case in general as it is possible, for example, for step 2 or 3 to take a dependency on the state of the main render target.) To render in the correct order, then, the `FrameBufferManager` must spread these operations out over three `View`s.
1. `View` 0 targets the main render target and entails only a clear.
2. `View` 1 targets the shadowmap render target and entails a clear and a draw call.
3. `View` 2 targets the main render target and entails **no** clear and a draw call.

This, however, is made much more complicated if there are multiple `NativeEngine`s drawing simultaneously across multiple threads. For example, consider a scenario where `NativeEngine` A is rendering the shadowmap scene described above using high-level Babylon commands A.1, A.2, A.3, and A.4, while a separate `NativeEngine` B on a different JavaScript thread/runtime/`Napi::Env` is rendering a simple scene with four objects using high-level Babylon commands B.1, B.2, B.3, B.4, and B.5 (a clear and four draw calls). Because of threading, it is possible for these commands to happen in a wide variety of orders including the following:
```
B.1, A.1, B.2, A.2, B.3, A.3, B.4, A.4, B.5
```
Because the current `FrameBufferManager` is a `Graphics`-unique object, all these commands would operate on the same `FrameBufferManager`. This framebuffer manager would thus be forced to spread these operations out across nine bgfx `View`s because the `View` must be incremented each time the target is changed to preserve command order. However, command order does not actually matter between `NativeEngine`s A and B -- they exist in separate contexts and so their commands cannot take cross-context dependencies -- so this scenario really only _needs_ four views: three for A and one for B. There are other problems with having multiple threads contending to interact with a single `FrameBufferManager`, too, as well as complications with having two `NativeEngine`s in the same JavaScript thread/runtime/`Napi::Env` manipulating what they think of as two graphics contexts (for example, what on the Web might be two different canvases) and possibly taking dependencies on the states they "leave" them in.

To solve these problems, it seems likely that a `Context` concept must be added to the Graphics component. This concept will be logically descended from the `Graphics::Impl`/`FrameBufferManager` and will likely replace those as the point of interaction for consuming components. `Context`s will be acquired from the `Graphics::Impl` (or whatever name the replacement for that takes) and will be responsible for brokering all interactions which require consistent state. There can be arbitrarily many of them -- you can have many owned by/used within a single JavaScript thread/runtime/`Napi::Env` -- but their relationship with threading may be complex, and I haven't fully comprehended it yet. On the one hand, they seem like they want to be fundamentally unsafe because they encapsulate state which includes inviolable ordering. On the other hand, however, they also seem like they want to be the source for `UpdateToken`s, which frequently must be acquired on one thread, then moved to another. Perhaps the `Context` is a mixed bag? Or perhaps `UpdateToken`s should evolve such that they can be _acquired_ on any thread, but they can only be _used_ (to get the `bgfx::Encoder`) on the thread to which their `Context` is bound? I'm not sure; I haven't fully comprehended it yet. This, and likely many other questions, will need to be answered in the course of adding this new `Context` concept to the Graphics component.

**Comment by SergioRZMasson** [comment]
Conversation happening on PR #1028
