### ISSUE TITLE
Metal Validation Layer reporting problems

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#792]
Xcode Metal validation layer reports issues with BabylonNative Validation Tests ap and Babylon React Native Playground app.
Rendering is correct but users asking for support are told to disable the validation layer. Which is not great.
Find out why errors are reported.

**Comment by ryantrem** [comment]
This was recently working with metal validation enabled, and we turned it on in the Babylon React Native Playground app, but I also noticed yesterday it is failing again. Must be a recent regression.

**Comment by CedricGuillemet** [comment]
Yes, I can repro with iOS Validation Tests. With the canvas PR in, the first error I see is related to stencil. I'll fix it before we can continue investigating.

**Comment by CedricGuillemet** [comment]
Did a Validation tests run on iOS device and MacOS. No issue reported.
