### ISSUE TITLE
Remove `document = {}` from playground sample app

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#793]
See https://github.com/BabylonJS/BabylonNative/blob/3ba8ff43e57431656d29034576d72b83137c4676/Apps/Playground/Win32/App.cpp#L146

This line exists because the next line loading `ammo.js` fails because there is an issue with the bootstrapping code trying to access `document` without checking its existence.

We should look into fixing the bootstrapping code in `ammo.js` and remove the `document = {}` eval call.

**Comment by CedricGuillemet** [comment]
Tested today and ammojs now handles properly `document`. The issue I have now is about loading ammo. I could make it work with await like here : https://github.com/BabylonJS/Babylon.js/blob/8605e6c652fc5593676e6510a130951fb4afa21d/packages/tools/playground/src/components/rendererComponent.tsx#L179

I've tested it with this code:
```
Ammo();
    setTimeout(() => {
        scene.enablePhysics(new BABYLON.Vector3(0, -10, 0), new BABYLON.AmmoJSPlugin());
        sphere.physicsImpostor = new BABYLON.PhysicsImpostor(sphere, BABYLON.PhysicsImpostor.SphereImpostor, { mass: 1, restitution: 0.9 }, scene);
        ground.physicsImpostor = new BABYLON.PhysicsImpostor(ground, BABYLON.PhysicsImpostor.BoxImpostor, { mass: 0, restitution: 0.9 }, scene);

    }, 2000);
```
@bghgary  @RaananW What is the good practice to load ammo in BN ?

**Comment by RaananW** [comment]
if that's an acceptable solution we could add a static init function (async) in both the ammo plugin and the havok plugin that takes the uninitialized engine (Ammo or Havok), initialize it and returns a new physics plugin (which must stay synchronous due to back-compat).

**Comment by CedricGuillemet** [comment]
@RaananW if I understand correctly, it would do the `await Ammo()` in the plugin itself ?

**Comment by CedricGuillemet** [comment]
I'm trying to make it work in experience.js before doing a PR on bjs but any time I try to use await, I get an Unknown failure in BN. Is it expected @bghgary ?

**Comment by bghgary** [comment]
Where are you using await? You can't use await at the top-level.
