### ISSUE TITLE
x86 Chakra build is broken

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#81]
Looks like something became incompatible as a result of the `Promise` work done for the OpenXR integration.

**Comment by bghgary** [comment]
We should also add a CI task to build x86.

**Comment by CedricGuillemet** [comment]
Default calling convention changed between x86 and x86_64. Fixed by adding __stdcall in static function definition. I'd add  x86 compilations to win32 and uwp.

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/100

**Comment by bghgary** [comment]
https://guides.github.com/features/issues/#notifications

> By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into master, it will also automatically close the issue.

I've added this to the PR.
