### ISSUE TITLE
[Canvas] different JS behavior for canvas & context destruction

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#810]
With JSC and Chakra, canvas and context are destroyed just after the dynamicTexture is disposed.
With V8, those 2 objects are not destroyed before the JS Runtime is destroyed. More and more rendertargets are created and kept in memory. After a while, bgfx can't create a new one.

**Comment by CedricGuillemet** [comment]
Related : https://forum.babylonjs.com/t/cant-clear-dynamictexture-to-transparent-in-babylonreactnative/28933/16

**Comment by bghgary** [comment]
Look at this with the shutdown scenarios.

**Comment by CedricGuillemet** [comment]
Issue can be mitigated by increasing the number of FrameBuffer. With a number big enough (4096+), Framebuffer are destroyed at some point. Setting it to 256 for now in the CI.

**Comment by CedricGuillemet** [comment]
Closing for now. reopen if a better solution is needed.
