### ISSUE TITLE
Unmaximizing the Babylon Native Playground on Win32 causes an interesting crash

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#817]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
It looks like this interrupts the render loop somehow. Maximizing and then unmaximizing the Playground appears to cause us to call `StartRenderingCurrentFrame` when `m_rendering` is already true.

**To Reproduce**
1. Run the Playground.
2. Maximize.
3. Unmaximize.

**Expected behavior**
Doesn't crash.

**Screenshots**
N/A

**Other**
 - Platform: Win32

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/823
