### ISSUE TITLE
Window::RecursiveWaitOrCall is performance-heavy

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#843]
Taking a CPU profile on HoloLens running a release-mode build shows that Window::RecursiveWaitOrCall is fairly heavy on performance-- most likely due to the high number of dispatch calls. It would be beneficial to reimplement this function using a worker thread that sleeps for the given timeout and then dispatches the function.

<img width="750" alt="recursive-wait-or-call" src="https://user-images.githubusercontent.com/4724014/126723217-65075757-3254-49c0-be49-8ce0e1816c18.PNG">

**Comment by docEdub** [comment]
Now implemented in https://github.com/BabylonJS/BabylonNative/pull/1146.
