### ISSUE TITLE
Camera texture is cleared before render in XR mode

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonNative#871]
**Describe the bug**
After the upgrade to Babylon.JS 5.0.0-alpha.37 the camera texture is rendering as blank when running in XR mode. This has been root caused to the [added clear in scene.ts](https://github.com/BabylonJS/Babylon.js/blob/0d93186a33ab7fdc2dde017e976d5788c8f24303/src/scene.ts#L4005) in this change in Babylon.js: https://github.com/BabylonJS/Babylon.js/pull/10762

**To Reproduce**
1. Enable AR mode in experience.js
2. Run the playground test app

**Expected behavior**
Camera texture renders behind 3D content.

**Screenshots**
<img src="https://user-images.githubusercontent.com/27031140/129946229-bf8529aa-0380-4533-bd2c-1f72f6e796cc.png" width="200"/>

**Other**
- Android, iOS

**Comment by EricBeetsOfficial-Opuscope** [comment]
UP 😛 
Any news from the BJS part ?

**Comment by bghgary** [comment]
Sorry, was on vacation. I believe all the parts are merged and this should be working. Can you verify?

**Comment by bghgary** [comment]
@RaananW Can you help?

**Comment by RaananW** [comment]
This should have been solved by now. Is it still failing in native?

**Comment by bghgary** [comment]
https://github.com/BabylonJS/Babylon.js/pull/11042 should resolve the last part. Once that is merged, we need a new npm package to pick up. Then we should be good to go.

**Comment by EricBeetsOfficial-Opuscope** [comment]
I just tested on Android and iOS, it works perfectly 👌
Thank you !!!!
