### ISSUE TITLE
[Android] Restart Activity with XR 

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#878]
Follow up https://forum.babylonjs.com/t/babylonnative-is-it-possible-to-restart-an-android-activity/23542/24

**Describe the bug**
Crash second time launching the playground activity when XR was active the first time.

**To Reproduce**
1. Clone this blanch https://github.com/EricBeetsOfficial-Opuscope/BabylonNative/tree/test/Android_lifecycle_activities
2. Build & run for Android
3. tap button 'Launch Playground'
4. wait for XR to be active
5. Get back to main activity
6. tap again 'Launch Playground'

**Expected behavior**
No crash 

**Other**
 - Android Only. ViewController life management is different on iOS.

**Comment by CedricGuillemet** [comment]
Is this related to https://github.com/BabylonJS/BabylonReactNative/issues/183 ?

**Comment by CedricGuillemet** [comment]
Crash happens when trying to render frame with an opengl invalid operation. It looks like the gl context is invalid. I commented XR rendering (surface creation/ gl context binding) and it still crashes.

**Comment by CedricGuillemet** [comment]
Here is a list of things I've tried to identify the reason why the openGL context is broken:
- BP on eglMakeCurrent -> no call stack
- removed all plugins but the mandatory ones to repro the bug
- removed XRSurfaceView in BabylonView.java -> XR is not rendered
- removed opengl rendering code paths in XR.cpp
- removed texture override in nativeXR.cpp
- removed asset creation in XR.cpp (textures, programs,...)
- create framebuffer in place instead of using a task
- tested other versions of arcore (1.22,1.25)

... and the bug still reproduces.

**Comment by CedricGuillemet** [comment]
- removed framebuffer creation from NativeXR.cpp and use kInvalid handle instead (back buffer)

still crashes.

**Comment by CedricGuillemet** [comment]
I've started removing ARCore calls from XR.cpp and `ArSession_update(xrContext->Session, xrContext->Frame);` is responsible for producing the context crash. I need to do more checks (with full rendering code uncommented) to confirm.

**Comment by CedricGuillemet** [comment]
Extracted comment from the function definition:
```
/// This call may cause off-screen OpenGL activity. Because of this, to avoid
/// unnecessary frame buffer flushes and reloads, this call should not be made
/// in the middle of rendering a frame or offscreen buffer.
```

**Comment by CedricGuillemet** [comment]
Obvious change to save/restore context/display/surface before and after the call doesn't work.

**Comment by CedricGuillemet** [comment]
Doing a bit of progress: Binding opengl context only and not the surface make it not crash in later use of the context.
```
EGLDisplay previousDisplay{ eglGetDisplay(EGL_DEFAULT_DISPLAY) };
EGLSurface previousDrawSurface{ eglGetCurrentSurface(EGL_DRAW) };
EGLSurface previousReadSurface{ eglGetCurrentSurface(EGL_READ) };
EGLContext previousContext{ eglGetCurrentContext() };
eglMakeCurrent(eglGetDisplay(EGL_DEFAULT_DISPLAY), EGL_NO_SURFACE, EGL_NO_SURFACE, previousContext);
ArSession_update(xrContext->Session, xrContext->Frame);
eglMakeCurrent(previousDisplay, previousDrawSurface, previousReadSurface, previousContext);
```
Now, there are a bunch of issues with engine destruction/re-initialization...

**Comment by CedricGuillemet** [comment]
PR https://github.com/BabylonJS/BabylonNative/pull/888

It fixes the issue for some configuration (mine at least). Need more tests with some Samsung device.

**Comment by bghgary** [comment]
Closing for now. If someone has a specific device that repros more, we can reopen.
