### ISSUE TITLE
Implement clearTimeout in Window polyfill

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/BabylonNative#893]
We should implement the clearTimeout function. This would enable the use of timeouts in Mocha.js tests. This should probably be done once #843 is finished, since that work will change the implementation of setTimeout.

**Comment by bghgary** [comment]
Related: https://github.com/BabylonJS/BabylonNative/pull/844

**Comment by docEdub** [comment]
Implemented in https://github.com/BabylonJS/BabylonNative/pull/1146.
