### ISSUE TITLE
Fix Console polyfill to allow Mocha.js reporters to work correctly

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/BabylonNative#894]
The current Console polyfill only implements a limited subset of console functionality. Currently, the built in Mocha.js reporters (which print test results to the console) will not work. We are using a custom reporter as a workaround, but eventually we should fix the polyfill.

**Comment by bghgary** [comment]
Relevant code: https://github.com/BabylonJS/BabylonNative/blob/master/Apps/UnitTests/Scripts/tests.js#L1-L16
