### ISSUE TITLE
Support D3D12 view instancing for multiview rendering on OpenXR

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#904]
We currently hand two framebuffers to Babylon.js per-frame, one for each eye, pointing to different layers in the color & depth texture arrays provided by the OpenXR runtime. Ideally, we would use one framebuffer per-frame with the entire texture arrays attached and render to it in one set of draw calls (instead of two, one per eye) using the [GL_OVR_multiview2 extension](https://developer.mozilla.org/en-US/docs/Web/API/OVR_multiview2). This will allow us to avoid two full renders per frame. In rendering-dominated scenarios, we could see up to a ~40% decrease in frame time, almost doubling our framerate.

Babylon.js currently [has support for WebXR Projection Layers](https://github.com/BabylonJS/Babylon.js/pull/11828), which means that there already exists a path in Babylon.js to render stereo views to a texture array in a single pass, although there still remains lots of work to get BabylonNative to provide the multiview render target and set up view instanced rendering. 

[D3D12 supports view instancing](https://microsoft.github.io/DirectX-Specs/d3d/ViewInstancing.html), which will allow us to use a built-in variable, `SV_ViewID` in our hlsl shaders that will closely match the `gl_ViewID_OVR` built-in variable provided by the GL_OVR_multiview2 extension.

Here's a breakdown of what would need to get done to connect these two:
* BabylonNative (1)
  - Make sure D3D12 rendering works in XR (for example [XrPlatform.h in OpenXR/Windows](https://github.com/BabylonJS/BabylonNative/blob/10a803267809f85b5437d2a754cfc3ed748e2ca2/Dependencies/xr/Source/OpenXR/Windows/XrPlatform.h) still depends on D3D11.
* SPIRV-Cross 
  - [Contribute another entry here](https://github.com/KhronosGroup/SPIRV-Cross/blob/131278458ea8eebe6a6e9c476fbcf71278726e1a/spirv_hlsl.cpp#L651) for `BuiltInViewIndex` that outputs `SV_ViewID` when using shader model 6.1 or greater.
* bgfx
  - When [creating the pipeline state object](https://github.com/BabylonJS/bgfx/blob/881de0d96438b3a391e3d548381094d38b6b5a1d/src/renderer_d3d12.cpp#L2858) on D3D12 for a pipeline that should use multiview, we need to add a `D3D12_VIEW_INSTANCING_DESC` to the PSO and set the `ViewInstanceCount` to 2.
    - The hardest part here will be finding a way to change the contract (possibly by adding a parameter to `getPipelineState`) so that we can send the view instance count to bgfx in a way that works for D3D12 but doesn't disturb things on all of the other rendering backends.
* BabylonNative (2)
  - Change [the framebuffers we make for XR rendering](https://github.com/BabylonJS/BabylonNative/blob/955134e5b08d4d674a66d316b1e6b7a38179f4de/Plugins/NativeXr/Source/NativeXr.cpp#L696-L709) to use texture arrays when `eyeCount > 1` and specify `multiview = true` for the multiview XR render targets that we hand off to Babylon.js (naturally this will be false on monocular/mobile devices)
  -  Leverage the new bgfx contract to create the Babylon shader's pipeline state object with view instancing for shaders with the multiview extension enabled, which we can detect with glslang.
* Babylon.js
  - Implement `bindMultiviewFramebuffer` for `NativeEngine`. This will likely just alias the existing `bindFramebuffer`.

**Comment by bghgary** [comment]
Closing for now. Reopen if we still want this.
