### ISSUE TITLE
[NativeCapture] Capturing a framebuffer crashes bgfx

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#916]
Capturing a framebuffer created on the JS side crashes bgfx because texture has not been registered with GraphicsImpl.
Quick repro:

```
var renderTarget = new BABYLON.RenderTargetTexture("depth", 1024, scene, true);
...
capture = new NativeCapture(renderTarget._renderTarget._framebuffer);

```

I did a quick workaround by adding:
```
m_graphicsImpl.AddTexture(texture->Handle, width, height, generateMips, 1, format);
```
in `NativeEngine::CreateFrameBuffer`. Is it the way to go @syntheticmagus  ?

**Comment by darraghjburke** [comment]
Even if I insert your workaround in line 1273 of NativeEngine, I'm still seeing:
`Assertion failed: bgfx::isTextureValid(0, false, 1, format, BGFX_TEXTURE_RT), file C:\Users\darraghburke\BabylonNative\Plugins\NativeEngine\Source\NativeEngine.cpp, line 1285`

My code is just:
```javascript
        var engine = new BABYLON.NativeEngine();
        var scene = new BABYLON.Scene(engine);
        var renderTarget = new BABYLON.RenderTargetTexture("depth", 1024, scene, true);
        var capture = new NativeCapture(renderTarget._renderTarget._framebuffer);
```

I'm on the latest version of master. Any thoughts?
