### ISSUE TITLE
ScreenSpaceReflectionPostProcess: Exception in HostFunction: ERROR: 0:8: 'step' : redefinition

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/BabylonNative#922]
Reporting back https://github.com/BabylonJS/Babylon.js/issues/11298 from @igorroman777 

**I just wanted to integrate ScreenSpaceReflectionPostProcess into babylonjs react native.!**

My Code is:
````
  var ssr = new ScreenSpaceReflectionPostProcess("ssr", scene, 1.0, camera);
      ssr.reflectionSamples = 32;
      ssr.strength = 2; 
      ssr.reflectionSpecularFalloffExponent = 3; 

````

**Repro**
- Current result:
` ERROR  BJS - [21:39:25]: Error: Exception in HostFunction: ERROR: 0:8: 'step' : redefinition 
ERROR: 1 compilation errors.  No code generated.`

**Android phone:**
 - Samsung
 - Babylonjs react native
 - Version:
     "@babylonjs/core": "5.0.0-alpha.44",
    "@babylonjs/loaders": "5.0.0-alpha.44",
    "@babylonjs/react-native": "0.4.0-alpha.33",

**Comment by CedricGuillemet** [comment]
There is a uniform called `step`
https://github.com/BabylonJS/Babylon.js/blob/5e6321d887637877d8b28b417410abbbeb651c6e/src/Shaders/screenSpaceReflection.fragment.fx#L14

It's a reserved keyword. Changing the name in the shader will fix it. I find it weird that there is no error reported by the browser.

**Comment by darraghjburke** [comment]
Hey @igorroman777,

The changes to support this feature will be nontrivial. This relies on the createMultipleRenderTarget function, which we don't currently support in Babylon Native. We want to support it eventually, but it isn't currently on our radar.

Is it a must-have for your project?

**Comment by CedricGuillemet** [comment]
some postprocess now works https://github.com/BabylonJS/BabylonNative/pull/1354
SSR not working yet

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.
