### ISSUE TITLE
Investigate D3D12 support

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#931]
We need D3D12 at least in order to support [view instancing](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_view_instancing_desc) for HoloLens performance.

**Comment by CedricGuillemet** [comment]
After some more tests with current bgfx version and a newer one I've found that some bug in current is fixed in newer (d3d12 front facing) but a whole new set of issues appear with latest bgfx.
I prefer to wait for a bgfx update before continuing testing and fixing.

**Comment by CedricGuillemet** [comment]
I've found a fix for the last issue I had: LOD PG was not working on CI because of indirect batching. PR on bgfx is open here:
https://github.com/bkaradzic/bgfx/pull/2672

**Comment by bghgary** [comment]
PR #826 is in.
