### ISSUE TITLE
Metal Validation Error with AR/iOS

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#932]
I've checked commit and it seems this commit breaks Metal Validation
https://github.com/BabylonJS/BabylonNative/commit/c79d748174cae8aa158de63f1e4f809b567105d6

Everything is ok with 
https://github.com/BabylonJS/BabylonNative/commit/b43087a5b26ac8d3dfcb7d1421249d7aed765e35

Run Playground with `ar = true;` in experience.js

![image](https://user-images.githubusercontent.com/1312968/138432089-ee212ebc-b21a-4682-9289-1e4d060bbcd5.png)

**Comment by ryantrem** [comment]
It seems like this still happens, though now it is harder to repro. It seems like I have to do something that affects timing, like interacting with the app (e.g. touch input) and after 5-10 seconds I am able to get a metal validation error that looks the same. I'm testing the built packages so it's a bit harder to see the stack, but it looks like it is probably the same thing:
```
#5	0x000000019cc03788 in MTLReportFailure ()
#6	0x000000019cb66d24 in _MTLMessageContextEnd ()
#7	0x00000001cfea5ee0 in -[MTLDebugTexture setPurgeableState:] ()
#8	0x00000001033de0e4 in ___lldb_unnamed_symbol2256$$libMTLCapture.dylib ()
#9	0x00000001026e6ee0 in invocation function for block in xr::System::Session::Impl::GetNextFrame(bool&, bool&, std::__1::function<arcana::task<void, std::exception_ptr> (void*)>) ()
#10	0x00000001033826b8 in ___lldb_unnamed_symbol732$$libMTLCapture.dylib ()
#11	0x00000001cfe000b0 in -[MTLToolsCommandBuffer invokeCompletedHandlers] ()
#12	0x000000019cb61fa0 in MTLDispatchListApply ()
#13	0x000000019cb62374 in -[_MTLCommandBuffer didCompleteWithStartTime:endTime:error:] ()
#14	0x00000001cecbe144 in -[IOGPUMetalCommandBuffer didCompleteWithStartTime:endTime:error:] ()
#15	0x000000019cb6204c in -[_MTLCommandQueue commandBufferDidComplete:startTime:completionTime:error:] ()
#16	0x00000001cecbdf04 in __IOGPUNotificationQueueSetDispatchQueue_block_invoke ()
```

**Comment by CedricGuillemet** [comment]
I did not repro. BN or BRN, iphone 11 and xcode 13.3.1

**Comment by bghgary** [comment]
I tried a few times to repro with BN, but wasn't able to.

**Comment by bghgary** [comment]
Closing for now until we can repro.
