### ISSUE TITLE
Various shaders fail to compile in Babylon Native

### ISSUE THREAD

**Issue by darraghjburke** [BabylonJS/BabylonNative#939]
This issue is tracking all the shaders that I am uncovering which don't compile in BabylonNative. We will address them as they become relevant. If you want to use any of these, please comment in the thread, and we will prioritize fixing it ASAP 

- [ ] ScreenSpaceCurvaturePostProcess throws from s_renderD3D11->m_device->CreatePixelShader()
- [ ] SpriteMap: throws from program.addShader()
- [ ] DigitalRainPostProcess (from PostProcess library): calls document.createElement()
- [ ] RefractionPostProcess: investigating
- [ ] ColorCorrectionPostProcess: investigating
- [ ] LensRenderingPipeline: investigating
- [ ] MotionBlurPostProcess: needs PrePassRenderer, which requires DrawBuffersExtension engine capability
- [ ] FxaaPostProcess: broken by y flip shader hack
- [ ] ScreenSpaceReflectionPostProcess: throws from program.addShader()

I'm adding unit tests for all of these in #940

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support these features.
