### ISSUE TITLE
Apparent memory leak

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#94]
Repro steps:
1. Launch default TestApp experience
2. Wait for experience to finish loading, then press "R" to recreate the Babylon Native Runtime.

Result:
Every time the Runtime is recreated, memory usage climbs.

Expected Behavior:
All Runtime resources should be discarded successfully when the Runtime is recreated, so there should be no leftovers to occupy memory after pressing "R".

**Comment by CedricGuillemet** [comment]
I'd added a couple missing finalizers (vertex array) like this one:
https://github.com/BabylonJS/BabylonNative/blob/master/Library/Source/NativeEngine.cpp#L614
But none of them is called when destroying napi env. Most of the allocated memory when refreshing is in Chakra so I guess there is a missing destruction there.

**Comment by CedricGuillemet** [comment]
JsDisposeRuntime(m_jsRuntime); fails with a JsErrorRuntimeInUse error code

**Comment by bghgary** [comment]
Yeah, I noticed that before which is why I made that a log and not a ThrowIfFailed. I'm unsure if we can tell the JS runtime to just throw everything away or there is something else leaking.

**Comment by syntheticmagus** [comment]
Ran into this today while working on the refactor. To get Chakra to shut down correctly, looks like we need to call `JsSetCurrentContext(JS_INVALID_REFERENCE)`, _a la_ [this example](https://github.com/microsoft/Chakra-Samples/blob/master/Chakra%20Samples/JSRT%20Win32%20Hosting%20Samples/Edge%20JSRT%20Samples/C%2B%2B/ChakraHost.cpp#L509).

However, doing so brings to the forefront a number of order-of-teardown problems that this leak was hiding. I'll open issues on those and post links to them here. Until we get those problems resolved, though, correctly shutting down Chakra will break execution even more invasively, and we wouldn't be able to confirm that this is actually the cause of the memory leak or not.
