### ISSUE TITLE
Excessive blocking on iOS impacts frame rate

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#943]
Sometimes iOS gets into a state (at least on my device) where it is blocked for up to ~23ms in `FinishRenderingCurrentFrame` waiting for the next metal drawable. I'm able to repro this in the BRN Playground by simply pulling up the app switcher and then going back to Playground. Once in this state, toggling engine view off/on restores normal rendering without the excessive blocking.

**Comment by bghgary** [comment]
This does not repro for both @ryantrem and I, so we are going to close for now. Reopen if someone sees this again.
