### ISSUE TITLE
toggling vr on crashes the app

### ISSUE THREAD

**Issue by waverider404** [BabylonJS/BabylonNative#954]
I wanted to try out the vr on my quest 2 using oculus airlink but i get this error

![devenv_WgGn2LWlMX](https://user-images.githubusercontent.com/34609417/143728061-afe1cea9-4bb5-4bb0-888c-48389fab9223.png)

**Comment by bghgary** [comment]
Short answer is that Oculus is not currently supported.

There are multiple open issue relating to Oculus:
#626
#379
#231

I'm not sure this issue adds anything more and thus I'm going to close. Please reopen if you think otherwise.
