### ISSUE TITLE
Refactor and Integration of DeviceInputSystem into BabylonNative (Part 2)

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/BabylonNative#956]
#### Required ####
- [ ] Add support for other devices/functionality
    - [ ] Evaluate and Implement Mouse detection for Unix and MacOS
    - [x] Mouse secondary buttons
    - [ ] Keyboard
    - [ ] Gamepads
    - [ ] Modify isDeviceAvailable to reflect availability of devices
- [ ] Convert Touch to work as single device
    - [ ] JS Side
    - [ ] Native side (as applicable)
- [ ] Evaluate next candidates for DOM conversion (and convert, if possible)
    - [ ] UI Elements
    - [ ] Tools

#### Secondary/Stretch Goals ####
- [ ] Make DeviceInputSystem more modular
    - [ ] Create custom device type
    - [ ] Break JS code into parts to minimize size of WebDeviceInputSystem
- [ ] Add multi-fetch polling functionality
- [ ] Create event recorder for testing (JS side)

**Comment by bghgary** [comment]
Closing for now. Reopen if we decide to support more input work.
