### ISSUE TITLE
[Shader Traverser] Exception with UniformTypeChangeTraverser 

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#959]
When changing uniform types to vec4/mat4, there is one case that is not handled by `UniformTypeChangeTraverser` here throws an exception here: https://github.com/BabylonJS/BabylonNative/blob/9b2bad35c4e020afde0d4355d7d817ebe0466afb/Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp#L369

This can be tested with https://playground.babylonjs.com/#ycy2il#0

before changing type, there is `float _alphaTest` and a test in the fragment shader : `if (alphaTest)`. After changing type, `_alphaTest` becomes a float4 but the if expression stays the same (hence the throw).

This was not happening with D3D11 before https://github.com/BabylonJS/BabylonNative/pull/826 . It does now, and for all other Graphics API.

cc @bghgary

**Comment by darraghjburke** [comment]
@syntheticmagus can you take a look at this one, since I am a bit occupied working on Babylon.js stuff at the moment?

**Comment by CedricGuillemet** [comment]
Reopening issue because the fix doesn't work with OpenGL.

**Comment by syntheticmagus** [comment]
@CedricGuillemet I repro that this Playground does not work on Android, but it does not look to me like this is the same issue. For one thing, the unimplemented code path which caused the original problem is now implemented, so unless the same shader source is parsed differently on different platforms it should not be running into the original issue. More significantly, however, in my repro I'm getting what appears to be a segfault, not the nice clean `throw` we were seeing from this issue. Is this really the same issue and I'm just misunderstanding what I'm seeing, or is this more accurately a separate issue that simply affects the same Playground?

**Comment by CedricGuillemet** [comment]
Technically, it's not the same throw.
Before the fix, it used to crash here for every platform:
https://github.com/BabylonJS/BabylonNative/blob/9b2bad35c4e020afde0d4355d7d817ebe0466afb/Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp#L369
Now, the crash happens here:
https://github.com/BabylonJS/BabylonNative/blob/e4a4d882af22768d2226fd1f2e178b46a20a1af3/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L24

I've put a break point and this code is executed on Android:
https://github.com/BabylonJS/BabylonNative/blob/e4a4d882af22768d2226fd1f2e178b46a20a1af3/Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp#L369

But at the end, the glsl code produced doesn't have the `.x` in the `if` statement and the shader looks like this:

```
uniform vec4 myUniform;

...
if (myUniform) {
...
}
...
```
