### ISSUE TITLE
CURL issues

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#96]
Centralising all the CURL issues here. This might be used as requirements for a CURL replacement.

- [ ] Support non-blocking curl
Our usage of libcurl is currently the blocking synchronous version. We should use the non-blocking asynchronous version.
- [ ] UWP with broad file system access in libcurl fails
For UWP, we have <rescap:Capability Name="broadFileSystemAccess" /> set in the manifest and have enabled in the settings to allow the app.
- [ ] Curl doesn't handle binary to text conversions. We need to deal with the BOM and text-encoding, etc. See [here](https://github.com/BabylonJS/BabylonNative/pull/60/files/1d6d173a4cbcef38b5c1f53f2ffdf69669c68a24..7aa2cb6e676172d869954e41787343720b61b819#diff-3aa27b499bbf2961cb08ba1efdb164f9R136).

libcurl eventually calls the C open API (which eventually calls CreateFileW), but this returns -1.

We currently have a fallback mechanism to use Windows::Storage::StorageFile::GetFileFromPathAsync instead, but it would be nice to see if we can get libcurl to work with broadFileSystemAccess.
~~Curl and local file access~~
~~To access local files in the APK (scripts/*.js), Android asks to use an asset manager. You can't open the file directly and basically, it's not even a file in the filesystem but a bunch of bytes in a zip. For now, I've added a function, per platform that does the job if curl doesn't succeed at loading the resource.~~
Issue moved to plugin https://github.com/BabylonJS/BabylonNative/issues/119
- [ ] Remove workaround for cURL integration in UWP
https://github.com/BabylonJS/BabylonNative/blob/ab9fd87a212eb574bd3c187f2eb46afaa22c57b5/Library/CMakeLists.txt#L48-L53
- [ ] CMake libcurl taking too much time
CMake 3min40 to generate solution per target on Azure with at least 2min30 taken only by libcurl
There must be some flags to change to speed up the solution generation time.
- [x] Security issue on Android with OpenSSL. I had to disable host and peer verification because of curl unable to check that. This is far beyond my knowledge and should be addressed by someone competent.
```
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0);
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
```

**Comment by bghgary** [comment]
We are no longer planning on using curl. Will be replaced with platform specific implementations.

**Comment by bghgary** [comment]
See #195
