### ISSUE TITLE
[XMLHttpRequest] onLoad/onError

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#971]
When trying to add sprites validation test scene, I've found that XMLHttpRequest polyfill is lacking onLoad/onError:
https://github.com/BabylonJS/Babylon.js/blob/944c968f2d474c7b0761edf5c64b58a9fb780662/src/Sprites/spriteManager.ts#L344

Is it safe for add accessors for those 2 members and add a corresponding event listener ?

**Comment by bghgary** [comment]
Why is this code (on the js side) not using Tools.LoadFile??

**Comment by bghgary** [comment]
We can certainly add more event listeners, but I think we should just fix the js side.

**Comment by CedricGuillemet** [comment]
Makes sense. I'll take care of that.

**Comment by CedricGuillemet** [comment]
Fixed with https://github.com/BabylonJS/Babylon.js/pull/11775
