### ISSUE TITLE
BoundingInfo.update often represents at least 10% of frame time

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#985]
This is quite a big chunk of frame time, and probably even more now since we've optimized a bunch of other things. It would be worth digging into this more and seeing if there are optimization opportunities here. See the discussion: https://github.com/BabylonJS/BabylonNative/discussions/983#discussioncomment-2045142

**Comment by CedricGuillemet** [comment]
Might be related to this :
https://github.com/BabylonJS/Babylon.js/pull/12030
In a recent demo project, getLOD was taking up to 25% of JS time.

**Comment by bghgary** [comment]
Closing for now. Please reopen if this is still an issue.
