### ISSUE TITLE
MSAA iOS/Android

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#988]
MSAA is disabled in the code for iOS and Android.  https://github.com/BabylonJS/BabylonNative/blob/5b5ad204466693ab849806616c063694d2986701/Core/Graphics/Source/GraphicsImpl.cpp#L40
On iOS, it caused an issue with Highlighting https://github.com/BabylonJS/BabylonReactNative/issues/215
An issue has been open on bgfx : https://github.com/bkaradzic/bgfx/issues/2620
On Android, it leads to a crash https://github.com/BabylonJS/BabylonNative/issues/507

Some partners will need MSAA and it must be re-enabled at some point.

**Comment by CedricGuillemet** [comment]
On Android, glBlitFramebuffer is broken with Mali chips : https://developer.arm.com/documentation/101897/0200/fragment-shading/multisampling-for-opengl-es

https://github.com/bkaradzic/bgfx/blob/89ae74122cdd8fc719ff467c2fbc377e45ea8b6c/src/renderer_gl.cpp#L3867

**Comment by bghgary** [comment]
Is there a workaround?

**Comment by CedricGuillemet** [comment]
Yes https://github.com/bkaradzic/bgfx/pull/2818

**Comment by bghgary** [comment]
@CedricGuillemet Is this fixed now?

**Comment by CedricGuillemet** [comment]
@bghgary No. There are issues on some devices. My guess is it's because of the size of the GPU internal framebuffer. It gets too big with MSAA. I have built some release .apk with variation on the MSAA technic, framebuffer size,.. I need to test. This will give me a better idea on how to fix it.

**Comment by bghgary** [comment]
I get there are issues on some devices, but MSAA is now enabled again right?

**Comment by CedricGuillemet** [comment]
yes.

**Comment by CedricGuillemet** [comment]
MSAA fixed with context config. Closing.
