### ISSUE TITLE
bgfx & instancing

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#992]
bgfx instancing is quite limited. See https://github.com/BabylonJS/BabylonNative/pull/990

Something should be done to be less restrictive.
 c/c other possibilities:

- modify bgfx to allow instance divisor per stream. It would be in sync with webGL. This tiny bit of work cover a change in API contract and also reimplementing instances for a few platforms (D3D11, D3D12, Metal, OpenGL, Vulkan) while keeping the backward compatibility. This also implies discussing the work with Branimir before.
- discard HW instancing and add loop on instance instead. As many submit call as mesh to render. Instance attributes need to be replaced by uniform. This means some work in Shader Traversers and also some questions: if a vertex buffer is used with a divisor ==1, how is it known when compiling shader that 1 (or more) particular attribute must be replaced by a uniform? Then, what's the performance will be? Especially on mobile.

**Comment by CedricGuillemet** [comment]
Another issue brought up in this PR : https://github.com/BabylonJS/BabylonNative/pull/1092

Instances are CPU mem only and we need to know if being able to move to GPU instead would improve perf.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature fully.
