### ISSUE TITLE
scene.pickWithRay is too slow to be run per-frame on HoloLens

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#999]
We're currently seeing scene.pickWithRay take up about 12 milliseconds per-frame when running a scene with the scene understanding world mesh enabled.

This problem isn't apparent on desktop WMR or on quest, and so it seems to be specific to using HoloLens on BabylonNative.

![pick-with-ray-profile](https://user-images.githubusercontent.com/4724014/153665121-180e4aa8-3ed5-4c11-89b5-3d42979f2160.png)

Here's a [sample playground](https://www.babylonjs-playground.com/#GCUDRF#7) with a typical world mesh I generated with a hololens.

Zipped cpuprofile from Chrome DevTools:
[full-xr-test.zip](https://github.com/BabylonJS/BabylonNative/files/8051419/full-xr-test.zip)

**Comment by bghgary** [comment]
We have GPU picking, so it should be okay now. We haven't tested it in native.
